'use client';
import {createContext,useCallback,useContext,useEffect,useState} from 'react';
import {readManagementSnapshot,seedSnapshot} from '../services/snapshot';
import {isAdministration,setMemberControl,setThreadControl} from '../utils/administration';
import type {Administration,MemberControl,ThreadControl} from '../types/administration';
import type {ManagementAccount} from '@/types/management-snapshot';
const key='alceix:platform-admin:demo:v1';
const empty:Administration={members:[],threads:[],audit:[]};
type ContextValue={accounts:ManagementAccount[];administration:Administration;ready:boolean;notice:string;notify:(s:string)=>void;refresh:()=>void;saveMember:(m:MemberControl,reason:string)=>boolean;saveThread:(t:ThreadControl)=>boolean};
const Context=createContext<ContextValue|null>(null);
export function PlatformProvider({children}:{children:React.ReactNode}){const [accounts,setAccounts]=useState(seedSnapshot),[administration,setAdministration]=useState(empty),[ready,setReady]=useState(false),[notice,notify]=useState('');const refresh=useCallback(()=>{const snapshot=readManagementSnapshot(localStorage);setAccounts(snapshot.accounts);const ids=snapshot.accounts.map(a=>a.id),threads=snapshot.accounts.flatMap(a=>a.threads.map(t=>t.id));try{const raw=localStorage.getItem(key);if(raw){const parsed:unknown=JSON.parse(raw);if(isAdministration(parsed,ids,threads))setAdministration(parsed);else {setAdministration(empty);notify('Ana yönetim kaydı okunamadı; inceleme verilerini kontrol edin.');}}else setAdministration(empty);}catch{setAdministration(empty);notify('Ana yönetim kaydı okunamadı.');}if(snapshot.issues.length)notify(`${snapshot.issues.length} geçersiz yerel kayıt atlandı; örnek kayıtlar gösteriliyor.`);setReady(true);},[]);useEffect(()=>{refresh();const handle=()=>refresh();window.addEventListener('storage',handle);window.addEventListener('alceix-workspace-update',handle);return()=>{window.removeEventListener('storage',handle);window.removeEventListener('alceix-workspace-update',handle);};},[refresh]);function persist(next:Administration){if(!ready||!isAdministration(next,accounts.map(a=>a.id),accounts.flatMap(a=>a.threads.map(t=>t.id)))){notify('Yönetim kaydı doğrulanamadı.');return false;}try{localStorage.setItem(key,JSON.stringify(next));setAdministration(next);notify('Yönetim işlemi demo kaydına işlendi.');return true;}catch{notify('Kaydedilemedi. Değişiklik uygulanmadı.');return false;}}function saveMember(control:MemberControl,reason:string){try{return persist(setMemberControl(administration,control,reason,accounts.map(a=>a.id),crypto.randomUUID(),new Date().toISOString()));}catch(e){notify(e instanceof Error?e.message:'İşlem tamamlanamadı.');return false;}}function saveThread(control:ThreadControl){try{return persist(setThreadControl(administration,control,accounts.flatMap(a=>a.threads.map(t=>t.id)),crypto.randomUUID(),new Date().toISOString()));}catch(e){notify(e instanceof Error?e.message:'İşlem tamamlanamadı.');return false;}}return <Context.Provider value={{accounts,administration,ready,notice,notify,refresh,saveMember,saveThread}}>{children}</Context.Provider>;}
export function usePlatform(){const c=useContext(Context);if(!c)throw new Error('Platform provider is required.');return c;}
