import type {Creator,CreatorPortfolio} from '../types/creator';
export type PublishedCreator={creator:Creator;portfolio:CreatorPortfolio;isAvailable:boolean};
export const creatorProfileKey=(id:string)=>`alceix:creator:${id}:published:v1`;
export function isPublishedCreator(value:unknown,creatorId:string):value is PublishedCreator {
 if(!value||typeof value!=='object')return false;const v=value as PublishedCreator,c=v.creator,p=v.portfolio;
 const text=(s:unknown,max:number)=>typeof s==='string'&&s.length<=max;
 const count=(n:unknown)=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=1000000000;
 const image=(s:unknown)=>typeof s==='string'&&/^\/(dropshipping|influencer|storefront\/gallery)\/[a-zA-Z0-9-]+\.(jpg|png|webp)$/.test(s);
 return !!c&&c.id===creatorId&&['name','handle','initials','format','location'].every(k=>text(c[k as keyof Creator],150))&&text(c.description,2000)&&['Instagram','TikTok','YouTube','Twitch'].includes(c.platform)&&['Moda','Yaşam','Teknoloji'].includes(c.category)&&['Kadın','Erkek','Karma'].includes(c.audience)&&[c.followers,c.views,c.fee].every(n=>count(n)&&Number.isSafeInteger(n))&&count(c.engagement)&&c.engagement<=100&&(c.photo===undefined||image(c.photo))&&Array.isArray(c.images)&&c.images.length<=6&&c.images.every(image)&&!!p&&text(p.bio,2000)&&text(p.experience,150)&&['languages','specialties'].every(k=>Array.isArray(p[k as 'languages'])&&p[k as 'languages'].length<=10&&p[k as 'languages'].every(s=>text(s,80)))&&Array.isArray(p.channels)&&p.channels.length<=6&&p.channels.every(ch=>ch&&text(ch.platform,30)&&text(ch.handle,100)&&[ch.followers,ch.views].every(n=>count(n)&&Number.isSafeInteger(n))&&count(ch.engagement)&&ch.engagement<=100)&&Array.isArray(p.contentMetrics)&&p.contentMetrics.length<=12&&p.contentMetrics.every(m=>m&&['Story','Reels','Post','Video'].includes(m.format)&&text(m.platform,30)&&[m.views,m.reach,m.likes,m.saves,m.count].every(n=>count(n)&&Number.isSafeInteger(n)))&&Array.isArray(p.audience)&&p.audience.length<=10&&p.audience.every(a=>a&&text(a.label,80)&&count(a.percent)&&a.percent<=100)&&Array.isArray(p.works)&&p.works.length<=30&&new Set(p.works.map(w=>w?.id)).size===p.works.length&&p.works.every(w=>w&&text(w.id,80)&&text(w.brand,150)&&text(w.title,150)&&['Story','Reels','Post','Video'].includes(w.format)&&image(w.image)&&/^\d{4}-\d{2}-\d{2}$/.test(w.date)&&text(w.description,2000)&&[w.views,w.reach,w.clicks].every(n=>count(n)&&Number.isSafeInteger(n))&&Array.isArray(w.deliverables)&&w.deliverables.length<=10&&w.deliverables.every(s=>text(s,150)))&&typeof v.isAvailable==='boolean';
}
