"use client";
import {useRef,useState} from 'react';
import type {AdminStore} from '../mocks/dashboard';
import type {Customer} from '../types/customer';
import type {EmailJob} from '../types/collaboration';
import {isEmailJobs,validEmail} from '../utils/collaboration';
import {useWorkspaceRecord} from '../hooks/use-workspace-record';
import {productMoney} from '../utils/product';
const empty:EmailJob[]=[];
export function BulkEmail({store,customers}:{store:AdminStore;customers:Customer[]}){
 const dialog=useRef<HTMLDialogElement>(null),jobs=useWorkspaceRecord(`alceix:email-jobs:${store.slug}`,empty,isEmailJobs);
 const [segment,setSegment]=useState('cart'),[subject,setSubject]=useState('Sepetiniz sizi bekliyor!'),[body,setBody]=useState('Merhaba {{ad}},\n{{magaza}} mağazamızdaki {{sepet}} tutarındaki sepetiniz sizi bekliyor. Ürünlerinizi inceleyip alışverişinizi tamamlayabilirsiniz.'),[notice,setNotice]=useState('');
 const recipients=customers.filter(c=>c.consent&&validEmail(c.email)&&(segment==='cart'?c.cartCents>0:segment==='vip'?c.spentCents>=500000:true));const preview=recipients[0];
 const personalize=(c:Customer)=>body.replaceAll('{{ad}}',c.name).replaceAll('{{magaza}}',store.name).replaceAll('{{sepet}}',productMoney(c.cartCents));
 return <><button className="co-secondary" onClick={()=>dialog.current?.showModal()}>Toplu E-posta · Sepet Kurtarma</button><dialog ref={dialog} className="ad-dialog co-dialog" aria-labelledby="email-heading"><div className="ad-dialog-heading"><h2 id="email-heading">Toplu E-posta Kampanyası</h2><button autoFocus aria-label="E-posta penceresini kapat" onClick={()=>dialog.current?.close()}>✕</button></div><p className="co-muted">İletişim izni bulunan müşteriler için kişiselleştirilmiş satış hatırlatmaları hazırlayın.</p><form className="co-form" onSubmit={e=>{e.preventDefault();if(!recipients.length){jobs.setError('Bu segmentte iletişim izni olan alıcı bulunmuyor.');return;}if(jobs.save([{id:crypto.randomUUID(),subject:subject.trim(),body:body.trim(),recipients:[...new Set(recipients.map(c=>c.email))],createdAt:new Date().toISOString()},...jobs.value].slice(0,100)))setNotice('E-posta kampanyası demo kuyruğuna eklendi. Gerçek e-posta gönderilmedi.');}}><label>Alıcı segmenti<select value={segment} onChange={e=>setSegment(e.target.value)}><option value="cart">Sepetini Terk Edenler</option><option value="vip">VIP Müşteriler</option><option value="all">İzinli Tüm Müşteriler</option></select></label><label>Konu<input maxLength={150} required value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>E-posta metni<textarea rows={5} maxLength={3000} required value={body} onChange={e=>setBody(e.target.value)}/></label><small className="co-muted">Kişiselleştirme: {'{{ad}}'} · {'{{magaza}}'} · {'{{sepet}}'}</small><details open><summary>{recipients.length} izinli alıcı · Alıcıları İncele</summary>{recipients.map(c=><div className="co-recipient" key={c.id}><strong>{c.name}</strong> · {c.email}<small> · Sepet: {productMoney(c.cartCents)}</small></div>)}</details>{preview&&<div className="co-summary"><h3>E-posta Önizlemesi · {preview.name}</h3><strong style={{fontSize:16}}>{subject}</strong><p className="co-preview">{personalize(preview)}</p></div>}{jobs.error&&<p className="co-error" role="alert">{jobs.error}</p>}{notice&&<p className="co-success" role="status">{notice}</p>}<button className="ad-button" disabled={!jobs.ready||!recipients.length}>Demo Gönderim Kuyruğuna Ekle</button><div className="co-demo">İzin vermeyen kişiler otomatik olarak hariç tutulur. Gerçek teslim, abonelikten çıkma ve sepet bağlantıları e-posta servisi bağlantısıyla çalışacak.</div></form><h3>Son Demo Kampanyaları</h3>{jobs.value.slice(0,5).map(j=><div className="co-row" key={j.id}><div><strong>{j.subject}</strong><small>{j.recipients.length} alıcı · {new Date(j.createdAt).toLocaleString('tr-TR')}</small></div><span className="co-badge">Demo Kuyruğu</span></div>)}</dialog></>;
}
