"use client";
import { useRef, useState } from "react";
import { useOrderWorkspace } from "../hooks/order-workspace";
import { carriers } from "../mocks/orders";
import { demoProducts } from "../mocks/products";
import { advanceOrder, canAdvanceOrder, orderSubtotal, orderTotal, paymentLabels, shipmentLabels } from "../utils/order";
import { productMoney as money } from "../utils/product";
import type { AdminOrder } from "../types/order";
export function OrderIcon({name}:{name:string}) {return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;}
export type OrderAction = "label" | "tracking" | "invoice" | "address" | "request" | "cancel" | "advance" | "packing" | "manual" | "shipping" | "rules" | "printer" | "customer";
const titles:Record<OrderAction,string>={label:"Kargo Barkodu & Etiket",tracking:"Gönderi Takibi",invoice:"Ödeme & Fatura Önizlemesi",address:"Teslimat Adresini Düzenle",request:"İade & Değişim Talebi",cancel:"Siparişi İptal Et",advance:"Sipariş Durumunu Güncelle",packing:"Toplu Paketleme Listesi",manual:"Manuel Sipariş Oluştur",shipping:"Kargo Entegrasyon Ayarları",rules:"Akıllı Kargo Kuralları",printer:"Barkod Yazıcı Formatı",customer:"Müşteri Bilgileri"};
export function useOrderActions(onNotice:(message:string)=>void) {
  const {orders,updateOrder,addOrder}=useOrderWorkspace();
  const dialog=useRef<HTMLDialogElement>(null);
  const [mode,setMode]=useState<OrderAction>("label");
  const [ids,setIds]=useState<string[]>([]);
  const [error,setError]=useState("");
  const [isDirty,setIsDirty]=useState(false);
  const [isDiscardPrompt,setIsDiscardPrompt]=useState(false);
  const [carrier,setCarrier]=useState(carriers[0]);
  const [address,setAddress]=useState("");
  const [city,setCity]=useState("");
  const [name,setName]=useState("");
  const [productId,setProductId]=useState(demoProducts[0].id);
  const [quantity,setQuantity]=useState("1");
  const [isPaid,setIsPaid]=useState(true);
  const [contract,setContract]=useState("");
  const [weight,setWeight]=useState("2");
  const [format,setFormat]=useState("100×150 mm");
  const [isExpress,setIsExpress]=useState(true);
  const [isNotification,setIsNotification]=useState(true);
  const selectedOrders=orders.filter(order=>ids.includes(order.id));
  const order=selectedOrders[0];
  function open(action:OrderAction,orderIds:string[]=[]){setMode(action);setIds(orderIds);setError("");setIsDirty(false);setIsDiscardPrompt(false);const selected=orders.find(order=>order.id===orderIds[0]);setCarrier(action==="label"&&isExpress&&selected&&orderTotal(selected)>100000?carriers[0]:selected?.carrier||carriers[0]);setAddress(selected?.address||"");setCity(selected?.city||"");if(action==="manual"){setName("");setProductId(demoProducts[0].id);setQuantity("1");setIsPaid(true);}dialog.current?.showModal();}
  function close(){if(isDirty){setIsDiscardPrompt(true);return;}dialog.current?.close();}
  function done(message:string){setIsDirty(false);setIsDiscardPrompt(false);dialog.current?.close();onNotice(message);}
  function createLabels(){if(!/^\d{1,3}(?:[.,]\d{1,2})?$/.test(weight)||Number(weight.replace(",","."))<=0){setError("Geçerli bir desi girin (ör. 2). ");return;}const eligible=selectedOrders.filter(order=>order.shipment==="preparing"&&order.payment==="paid");if(!eligible.length){setError("Etiket için ödenmiş ve hazırlanan bir sipariş seçin.");return;}eligible.forEach(order=>updateOrder(order.id,current=>({...current,carrier,tracking:current.tracking||`DEMO-${current.id}`})));setError("");onNotice(`${eligible.length} sipariş için demo etiket oluşturuldu. Gerçek taşıyıcı kaydı yoktur.`);}
  function manualSubmit(){const product=demoProducts.find(product=>product.id===productId)!;if(!name.trim()||!address.trim()||!city.trim()){setError("Müşteri adı, teslimat adresi ve il / ilçe alanlarını doldurun.");return;}if(!/^\d{1,2}$/.test(quantity)||Number(quantity)<1){setError("Adet 1–99 arasında tam sayı olmalı.");return;}const next:AdminOrder={id:`MAN-${Date.now()}`,createdAt:new Date().toISOString(),customer:name.trim(),email:"demo@example.com",phone:"Belirtilmedi",address:address.trim(),city:city.trim(),customerNote:"",internalNote:"Manuel demo sipariş",items:[{name:product.name,sku:product.sku,variant:product.variants[0]||"Standart",image:product.images[0],quantity:Number(quantity),unitCents:product.priceCents}],discountCents:0,shippingCents:0,shipment:"preparing",payment:isPaid?"paid":"pending",carrier,tracking:""};addOrder(next);done("Manuel demo sipariş listeye eklendi. Ödeme alınmadı, stok değiştirilmedi.");}
  const overlay=<dialog ref={dialog} className="ad-dialog ao-dialog" data-order-print={mode} data-order-format={format} aria-labelledby="order-action-title" onChange={()=>{if(["manual","address","shipping"].includes(mode))setIsDirty(true);}} onCancel={event=>{if(isDirty){event.preventDefault();setIsDiscardPrompt(true);}}}><div className="ad-dialog-heading"><span className="ad-icon-box blue"><OrderIcon name="local_shipping"/></span><button autoFocus aria-label="Sipariş penceresini kapat" onClick={close}><OrderIcon name="close"/></button></div><h2 id="order-action-title">{titles[mode]}</h2><p className="ad-demo-note">Demo çalışma alanı · Gerçek sipariş, kargo kaydı veya ödeme işlemi yapılmaz.</p>{isDiscardPrompt&&<div className="ao-discard" role="alert"><p>Kaydedilmemiş değişiklikleri bırakmak istiyor musunuz?</p><button className="ao-secondary" onClick={()=>setIsDiscardPrompt(false)}>Düzenlemeye Dön</button><button className="ao-danger" onClick={()=>{setIsDirty(false);setIsDiscardPrompt(false);dialog.current?.close();}}>Değişiklikleri Bırak</button></div>}{error&&<p role="alert" className="ao-error">{error}</p>}
    {mode==="manual"?<form onSubmit={event=>{event.preventDefault();manualSubmit();}}><label>Müşteri Adı<input value={name} maxLength={100} onChange={event=>setName(event.target.value)} placeholder="Örnek müşteri adı"/></label><label>Ürün<select value={productId} onChange={event=>setProductId(event.target.value)}>{demoProducts.map(product=><option key={product.id} value={product.id}>{product.name} · {money(product.priceCents)}</option>)}</select></label><div className="ao-form-pair"><label>Adet<input inputMode="numeric" value={quantity} onChange={event=>setQuantity(event.target.value)}/></label><label>Kargo Firması<select value={carrier} onChange={event=>setCarrier(event.target.value)}>{carriers.map(value=><option key={value}>{value}</option>)}</select></label></div><label>İl / İlçe<input value={city} maxLength={120} onChange={event=>setCity(event.target.value)}/></label><label>Teslimat Adresi<textarea value={address} maxLength={400} onChange={event=>setAddress(event.target.value)}/></label><label className="ao-check"><input type="checkbox" checked={isPaid} onChange={event=>setIsPaid(event.target.checked)}/>Demo ödeme durumu: Ödendi</label><small>Yalnızca bu sayfalar arasında gezinirken korunur. Sayfa yenilenince demo veriler sıfırlanır.</small><button className="ad-button" type="submit">Demo Sipariş Oluştur</button></form>:
    mode==="shipping"?<form onSubmit={event=>{event.preventDefault();if(!contract.trim()){setError("Bir örnek sözleşme adı yazın.");return;}done(`${carrier} için demo sözleşme ayarları kaydedildi. Taşıyıcı bağlantısı kurulmadı.`);}}><label>Taşıyıcı<select value={carrier} onChange={event=>setCarrier(event.target.value)}>{carriers.map(value=><option key={value}>{value}</option>)}</select></label><label>Sözleşme Adı<input value={contract} maxLength={80} placeholder="Örn. Mağaza sözleşmesi" onChange={event=>setContract(event.target.value)}/></label><div className="ao-info">API anahtarları bu önizlemede toplanmaz. Gerçek bağlantı, sunucu tarafında güvenli taşıyıcı entegrasyonu gerektirir.</div><button className="ad-button">Demo Ayarları Kaydet</button></form>:
    mode==="rules"?<div className="ao-rule-editor">{[{label:"Ekspres Otomasyonu",description:"1.000 TL üzeri demo siparişlerde Yurtiçi Kargo öner.",checked:isExpress,set:setIsExpress},{label:"WhatsApp Takip Mesajı",description:"Önizleme tercihi. Müşteriye gerçek mesaj gönderilmez.",checked:isNotification,set:setIsNotification}].map(rule=><div key={rule.label}><div><strong>{rule.label}</strong><p>{rule.description}</p></div><button role="switch" aria-checked={rule.checked} aria-label={rule.label} className="ao-switch" onClick={()=>rule.set(!rule.checked)}><span/></button></div>)}<button className="ad-button" onClick={()=>done("Demo kargo kural tercihleri bu önizlemede güncellendi.")}>Tercihleri Kaydet</button></div>:
    mode==="printer"?<div><label>Etiket Formatı<select value={format} onChange={event=>setFormat(event.target.value)}><option>100×150 mm</option><option>A4 · Tek Etiket</option></select></label><p className="ao-info">PDF kaydetmek için yazdırma ekranını kullanın. Donanım veya ZPL yazıcı bağlantısı yoktur.</p><button className="ad-button" onClick={()=>done(`Demo yazıcı formatı: ${format}`)}>Formatı Kaydet</button></div>:
    mode==="packing"?<div className="ao-print-document"><span className="ao-document-stamp">ÖRNEK PAKETLEME LİSTESİ</span>{selectedOrders.length?selectedOrders.map(order=><section key={order.id}><h3>#{order.id} · {order.customer}</h3>{order.items.map(line=><p key={line.sku}>{line.quantity} × {line.name} · {line.variant} · {line.sku}</p>)}</section>):<p>Önce listeden sipariş seçin.</p>}<button disabled={!selectedOrders.length} className="ad-button" onClick={()=>window.print()}><OrderIcon name="print"/>Yazdır / PDF Kaydet</button></div>:
    mode==="label"?<div><div className="ao-label-controls"><label>Kargo Firması<select value={carrier} onChange={event=>setCarrier(event.target.value)}>{carriers.map(value=><option key={value}>{value}</option>)}</select></label><label>Desi<input value={weight} inputMode="decimal" onChange={event=>setWeight(event.target.value)}/></label><button className="ad-button" onClick={createLabels}>Demo Barkod Üret</button></div><small>Etiket formatı: {format} · Gerçek gönderimde kullanılamaz.</small><div className="ao-print-document">{selectedOrders.map(order=><section className="ao-label" key={order.id}><span className="ao-document-stamp">DEMO ETİKET · GEÇERSİZ BARKOD</span><h3>{order.carrier} · #{order.id}</h3><strong>{order.customer}</strong><p>{order.address}</p>{order.tracking?<><div className="ao-barcode" aria-hidden="true"/><code>{order.tracking}</code></>:<p>Önce demo barkod oluşturun.</p>}</section>)}</div><button disabled={!selectedOrders.some(order=>!!order.tracking)} className="ad-button" onClick={()=>window.print()}><OrderIcon name="print"/>Etiketi Yazdır / PDF Kaydet</button></div>:
    order?<>{mode==="address"?<form onSubmit={event=>{event.preventDefault();if(!address.trim()||!city.trim()){setError("Adres ve il / ilçe alanlarını doldurun.");return;}updateOrder(order.id,current=>({...current,address:address.trim(),city:city.trim()}));done("Teslimat adresi demo siparişte güncellendi. Taşıyıcıya bilgi gönderilmedi.");}}><label>İl / İlçe<input maxLength={120} value={city} onChange={event=>setCity(event.target.value)}/></label><label>Teslimat Adresi<textarea maxLength={400} value={address} onChange={event=>setAddress(event.target.value)}/></label><button className="ad-button">Adresi Kaydet</button></form>:
    mode==="tracking"?<div><p className="ao-info">{order.carrier} · {order.tracking||"Takip kodu henüz oluşturulmadı"}</p><ol className="ao-timeline">{["Sipariş Alındı","Paketleniyor / Hazırlanıyor","Kargoya Verildi","Teslim Edildi"].map((label,index)=><li key={label} className={index<=(order.shipment==="delivered"?3:order.shipment==="shipped"?2:1)?"is-done":""}><OrderIcon name={index<=(order.shipment==="delivered"?3:order.shipment==="shipped"?2:1)?"check_circle":"radio_button_unchecked"}/><span>{label}<small>{index===2?order.carrier:"Örnek takip durumu"}</small></span></li>)}</ol><small>Canlı taşıyıcı verisi yoktur; siparişin demo durumu gösterilir.</small></div>:
    mode==="invoice"?<div className="ao-print-document"><span className="ao-document-stamp">ÖRNEK BELGE · MALİ GEÇERLİLİĞİ YOKTUR</span><h3>Alceix · #{order.id}</h3><p>{order.customer} · {order.address}</p><dl><div><dt>Ara toplam</dt><dd>{money(orderSubtotal(order))}</dd></div><div><dt>İndirim</dt><dd>−{money(order.discountCents)}</dd></div><div><dt>Kargo</dt><dd>{money(order.shippingCents)}</dd></div><div><dt>Genel toplam</dt><dd>{money(orderTotal(order))}</dd></div><div><dt>Ödeme durumu</dt><dd>{paymentLabels[order.payment]}</dd></div></dl><p>Bu bir e-fatura değildir. Vergi ve ödeme sağlayıcısı entegrasyonu bağlı değildir.</p><button className="ad-button" onClick={()=>window.print()}><OrderIcon name="print"/>Yazdır / PDF Kaydet</button></div>:
    mode==="customer"?<div><span className="ao-customer-avatar">{order.customer.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><h3>{order.customer}</h3><dl><div><dt>E-posta</dt><dd>{order.email}</dd></div><div><dt>Telefon</dt><dd>{order.phone}</dd></div><div><dt>Konum</dt><dd>{order.city}</dd></div></dl><small>Örnek müşteri kaydı. Müşteriye mesaj veya e-posta gönderilmez.</small></div>:
    mode==="request"?<div><h3>{order.request?.type==="exchange"?"Beden / Ürün Değişimi":"İade Talebi"}</h3><p className="ao-info">{order.request?.reason||"Bu sipariş için talep yok."}</p><p>Talep tutarı: <strong>{money(orderTotal(order))}</strong></p>{order.request?.status==="pending"?<div className="ao-dialog-actions"><button className="ao-danger" onClick={()=>{updateOrder(order.id,current=>({...current,request:current.request?{...current.request,status:"rejected"}:undefined}));done("Talep demo olarak reddedildi. Müşteriye bildirim gönderilmedi.");}}>Talebi Reddet</button><button className="ad-button" onClick={()=>{updateOrder(order.id,current=>({...current,request:current.request?{...current.request,status:"approved"}:undefined}));done("Talep demo olarak onaylandı. Para iadesi veya yeni gönderi oluşturulmadı.");}}>Talebi Onayla</button></div>:<p>Talep durumu: {order.request?.status==="approved"?"Onaylandı":order.request?.status==="rejected"?"Reddedildi":"Talep yok"}</p>}</div>:
    mode==="cancel"?<div><p>#{order.id} siparişinin demo kaydı iptal edilecek. Gerçek ödeme iadesi yapılmaz.</p>{order.shipment==="preparing"?<div className="ao-dialog-actions"><button className="ao-secondary" onClick={close}>Vazgeç</button><button className="ao-danger" onClick={()=>{updateOrder(order.id,current=>({...current,shipment:"cancelled"}));done("Sipariş demo olarak iptal edildi. Ödeme iadesi yapılmadı.");}}>İptali Onayla</button></div>:<p className="ao-error">Yalnızca hazırlanan sipariş iptal edilebilir. Kargodaki siparişler için iade süreci gerekir.</p>}</div>:
    <div><p>Mevcut durum: <strong>{shipmentLabels[order.shipment]}</strong></p>{canAdvanceOrder(order)?<><p>Yeni demo durum: <strong>{order.shipment==="preparing"?"Kargoya verildi":"Teslim edildi"}</strong></p><div className="ao-dialog-actions"><button className="ao-secondary" onClick={close}>Vazgeç</button><button className="ad-button" onClick={()=>{updateOrder(order.id,advanceOrder);done("Siparişin demo durumu güncellendi. Gerçek taşıyıcı işlemi yapılmadı.");}}>Durumu Onayla</button></div></>:<p className="ao-info">Devam etmek için ödeme durumu “Ödendi” olmalı ve hazırlanan siparişin demo etiketi bulunmalı. Teslim edilmiş veya iptal edilmiş sipariş değiştirilemez.</p>}</div>}</>:<p>Önce bir sipariş seçin.</p>}
  </dialog>;
  return {open,overlay};
}
