"use client";
import { useId, useRef, useState } from "react";
import Image from "next/image";
import type { CSSProperties } from "react";
import type { StoreDesign } from "../types/store-design";
import { demoProducts } from "../mocks/products";
import { productMoney as money } from "../utils/product";
import { accentForeground, youtubeVideoId } from "../utils/store-design";
export function DesignIcon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;}
const previewProducts=demoProducts.slice(0,6);
export function StoreDesignPreview({design,storeName}:{design:StoreDesign;storeName:string}) {
  const [query,setQuery]=useState("");const [category,setCategory]=useState("all");
  const [cart,setCart]=useState<Record<string,number>>({});const [mode,setMode]=useState<"search"|"cart"|"product"|"about"|"video">("search");
  const [productId,setProductId]=useState(previewProducts[0].id);const [videoId,setVideoId]=useState("");const [activeImage,setActiveImage]=useState(0);
  const dialog=useRef<HTMLDialogElement>(null);const productsRef=useRef<HTMLElement>(null);const dialogId=useId();
  const products=previewProducts.filter(product=>(category==="all"||product.category===category)&&product.name.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR")));
  const product=previewProducts.find(product=>product.id===productId)!;
  const count=Object.values(cart).reduce((sum,value)=>sum+value,0);
  const total=previewProducts.reduce((sum,product)=>sum+(cart[product.id]||0)*product.priceCents,0);
  function open(next:typeof mode){setMode(next);dialog.current?.showModal();}
  function browse(){setQuery("");setCategory("all");productsRef.current?.scrollIntoView({behavior:"auto",block:"nearest"});if(!design.sections.some(section=>section.visible&&(section.kind==="products"||section.kind==="collections")))open("search");}
  function add(id:string){setCart(current=>({...current,[id]:Math.min(99,(current[id]||0)+1)}));setMode("cart");dialog.current?.showModal();}
  function productCard(id:string){const item=previewProducts.find(product=>product.id===id)!;return <button key={id} className="av-product" onClick={()=>{setProductId(id);setActiveImage(0);open("product");}}><Image src={item.images[0]} width={240} height={240} alt={item.name}/><span>{item.name}</span><strong>{money(item.priceCents)}</strong></button>;}
  const style={"--av-accent":/^#[\da-f]{6}$/i.test(design.accent)?design.accent:"#0066ff","--av-on-accent":accentForeground(design.accent),"--av-link":accentForeground(design.accent)==="#102039"?"#102039":/^#[\da-f]{6}$/i.test(design.accent)?design.accent:"#0066ff","--av-bg":design.background==="beige"?"#faf6ef":"#ffffff",fontFamily:design.font==="serif"?"Georgia, 'Times New Roman', serif":design.font==="inter"?"Arial, Helvetica, sans-serif":"'Plus Jakarta Sans', sans-serif"} as CSSProperties;
  return <div className="av-shop" style={style} aria-label={`${storeName} vitrin önizlemesi`}>
    {design.announcement.enabled&&<div className={`av-announcement ${design.announcement.tone}`}><DesignIcon name="local_shipping"/>{design.announcement.text}</div>}
    <header className="av-header"><strong>{storeName}</strong><nav aria-label="Önizleme mağaza menüsü"><button aria-pressed={category==="all"} onClick={browse}>Yeni Gelenler</button><button aria-pressed={category==="Giyim"} onClick={()=>{setCategory("Giyim");open("search");}}>Giyim</button><button aria-pressed={category==="Aksesuar"} onClick={()=>{setCategory("Aksesuar");open("search");}}>Aksesuar</button><button onClick={()=>open("about")}>İletişim</button></nav><button aria-label="Vitrinde ürün ara" onClick={()=>open("search")}><DesignIcon name="search"/></button><button aria-label={`Önizleme sepeti, ${count} ürün`} onClick={()=>open("cart")}><DesignIcon name="shopping_bag"/><sup>{count}</sup></button></header>
    <div className="av-content">{design.sections.filter(section=>section.visible).map(section=><section key={section.id} className={`av-section av-block-${section.kind}`}>
      {section.kind==="hero"?<div className="av-hero-image"><Image src={design.hero.image} unoptimized={design.hero.image.startsWith("data:")} alt={design.hero.title||"Mağaza manşeti"} width={1200} height={700}/><div><span>YENİ SEZON · ÖZENLE SEÇİLDİ</span><h2>{design.hero.title}</h2><p>{design.hero.description}</p><button className="av-cta" onClick={browse}>{design.hero.buttonLabel}<DesignIcon name="arrow_forward"/></button></div></div>:
      section.kind==="collections"||section.kind==="products"?<><div className="av-section-heading"><h3>{section.title}</h3><button onClick={()=>open("search")}>Tümünü Gör <DesignIcon name="arrow_forward"/></button></div><p className="av-subtitle">{section.description}</p><div className="av-products" ref={node=>{if(section.kind==="products"||!productsRef.current)productsRef.current=node;}}>{(section.kind==="collections"?previewProducts.slice(0,3):products.slice(0,4)).map(item=>productCard(item.id))}</div>{section.kind==="products"&&!products.length&&<p className="av-empty">Aramanıza uygun ürün bulunamadı.</p>}</>:
      section.kind==="testimonials"?<><h3>{section.title}</h3><p className="av-subtitle">{section.description}</p><div className="av-reviews">{[{name:"Selin Y.",quote:"Hırkanın dokusu çok güzel, paketleme de özenliydi."},{name:"Burak D.",quote:"Siparişim hızlı ulaştı. Günlük kullanım için harika."}].map(review=><blockquote key={review.name}><span>★★★★★</span><p>{review.quote}</p><strong>{review.name}</strong><small>Örnek değerlendirme</small></blockquote>)}</div></>:
      section.kind==="instagram"?<><h3>{section.title}</h3><p className="av-subtitle">{section.description}</p><div className="av-gallery">{previewProducts.slice(0,4).map(item=><button key={item.id} onClick={()=>{setProductId(item.id);setActiveImage(0);open("product");}}><Image src={item.images[1]} width={150} height={150} alt={`${item.name} koleksiyon görseli`}/></button>)}</div><small className="av-source-note">Örnek görsel akışı · Instagram bağlantısı yoktur.</small></>:
      section.kind==="bento"?<div className="av-bento"><Image src="/dropshipping/cardigan.jpg" width={400} height={300} alt="Yeni sezon koleksiyonu"/><div><span>KOLEKSİYONA YAKINDAN BAKIN</span><h3>{section.title}</h3><p>{section.description}</p><button className="av-cta" onClick={browse}>Ürünleri Keşfet <DesignIcon name="arrow_forward"/></button></div></div>:
      section.kind==="video"?<><h3>{section.title}</h3><p className="av-subtitle">{section.description}</p><button className="av-video-button" disabled={!youtubeVideoId(section.videoUrl)} onClick={()=>{setVideoId(youtubeVideoId(section.videoUrl)||"");open("video");}}><DesignIcon name="play_circle"/>{youtubeVideoId(section.videoUrl)?"Videoyu İzle":"Bölüm ayarlarından YouTube bağlantısı ekleyin"}</button></>:
      <><h3>{section.title}</h3><p className="av-subtitle">{section.description}</p>{[{question:"Siparişim ne zaman kargoya verilir?",answer:"Bu örnek vitrinde kargo bilgileri demo olarak gösterilir. Gerçek teslimat süresini mağazanın politikası belirler."},{question:"Ürünleri nasıl iade edebilirim?",answer:"İade koşulları için mağazanın iletişim kanallarına başvurabilirsiniz. Bu önizleme gerçek iade talebi oluşturmaz."},{question:"Güvenle alışveriş yapabilir miyim?",answer:"Bu bir tasarım önizlemesidir; ödeme alınmaz. Gerçek ödeme sağlayıcısı entegrasyonu henüz bağlı değildir."}].map(faq=><details className="av-faq-item" key={faq.question}><summary>{faq.question}<DesignIcon name="expand_more"/></summary><p>{faq.answer}</p></details>)}</>}
    </section>)}</div><footer className="av-footer"><span><DesignIcon name="verified_user"/>Özenle seçilmiş ürünler</span><span><DesignIcon name="sync"/>Kolay iade bilgileri</span></footer>
    <dialog ref={dialog} className="ad-dialog av-dialog" aria-labelledby={dialogId} onClose={()=>setVideoId("")} onCancel={()=>setVideoId("")}><div className="ad-dialog-heading"><span className="ad-icon-box blue"><DesignIcon name={mode==="cart"?"shopping_bag":"storefront"}/></span><button autoFocus aria-label="Vitrin penceresini kapat" onClick={()=>dialog.current?.close()}><DesignIcon name="close"/></button></div><h2 id={dialogId}>{mode==="search"?"Ürünleri Keşfet":mode==="cart"?"Önizleme Sepeti":mode==="product"?product.name:mode==="video"?"Mağaza Videosu":"Mağaza & İletişim"}</h2><p className="ad-demo-note">Tasarım önizlemesi · Gerçek sipariş veya ödeme oluşturulmaz.</p>
    {mode==="search"?<><label className="av-search-label">Ürün Ara<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ürün adı…" maxLength={150}/></label><div className="av-category-buttons" role="group" aria-label="Önizleme ürün kategorileri">{["all","Giyim","Bakım","Ev & Yaşam","Aksesuar"].map(value=><button key={value} aria-pressed={category===value} onClick={()=>setCategory(value)}>{value==="all"?"Tümü":value}</button>)}</div><div className="av-products">{products.map(item=>productCard(item.id))}</div>{!products.length&&<p>Ürün bulunamadı.</p>}</>:mode==="product"?<div className="av-product-detail"><Image src={product.images[activeImage]} width={400} height={400} alt={product.name}/><div className="av-thumbnails">{product.images.map((src,index)=><button key={src} aria-label={`Ürün görseli ${index+1}`} aria-pressed={activeImage===index} onClick={()=>setActiveImage(index)}><Image src={src} width={50} height={50} alt=""/></button>)}</div><p>{product.description}</p><strong>{money(product.priceCents)}</strong><small>Örnek seçenek: {product.variants[0]} · SKU: {product.sku}</small><button className="ad-button" onClick={()=>add(product.id)}>Demo Sepete Ekle</button></div>:mode==="cart"?<><div className="av-cart-lines">{previewProducts.filter(item=>cart[item.id]).map(item=><div key={item.id}><Image src={item.images[0]} width={45} height={45} alt=""/><span><strong>{item.name}</strong><small>{money(item.priceCents)} × {cart[item.id]}</small></span><button aria-label={`${item.name} adedini azalt`} onClick={()=>setCart(current=>({...current,[item.id]:Math.max(0,(current[item.id]||0)-1)}))}>−</button><button aria-label={`${item.name} adedini artır`} onClick={()=>setCart(current=>({...current,[item.id]:Math.min(99,(current[item.id]||0)+1)}))}>+</button></div>)}</div>{!count?<p>Önizleme sepetiniz boş.</p>:<p className="av-cart-total">Örnek toplam <strong>{money(total)}</strong></p>}<button className="ad-button" onClick={()=>{setMode("search");setCategory("all");setQuery("");}}>Alışverişe Devam Et</button></>:mode==="video"&&videoId?<iframe title="Mağaza YouTube videosu" src={`https://www.youtube-nocookie.com/embed/${videoId}`} allow="fullscreen; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin"/>:<div><h3>{storeName}</h3><p>Özenle seçilmiş ürünler ve zamansız tasarımlar. İletişim kanalları mağaza profil ayarlarından yönetilir.</p><small>Bu önizlemede müşteriye mesaj gönderilmez.</small></div>}</dialog>
  </div>;
}
