import Link from "next/link";
import { MarketingPage } from "@/components/layout/marketing-page";
import { PageIntro } from "@/components/layout/page-intro";
import { PartnerLogos } from "@/components/layout/partner-logos";
import { routes } from "@/config/routes";

const services = [
  { name: "Meta", icon: "share", title: "Kitlenizle doğru yerde buluşun.", description: "Sosyal ticaret ve reklam araçlarıyla ürünlerinizi keşfedilebilir hale getirin. Mağazanız ile sosyal medya çalışmalarını bir arada düşünün.", tag: "Sosyal Ticaret & Reklam" },
  { name: "Mastercard", icon: "credit_card", title: "Alışverişin ödeme adımı.", description: "Kartlı ödeme deneyimi, alışveriş yolculuğunun temel parçalarından biridir. Müşterilerinize açık ve anlaşılır bir ödeme akışı sunun.", tag: "Kartlı Ödeme Ağı" },
  { name: "iyzads", icon: "trending_up", title: "Ürünleriniz için yeni kitleler.", description: "Dijital reklam çalışmalarını mağaza hedeflerinizle birleştirin. Kampanya performansını takip ederek içeriklerinizi ve ürün seçkinizi geliştirin.", tag: "Dijital Reklam" },
  { name: "tami", icon: "point_of_sale", title: "Ticaretin finansal bağlantısı.", description: "Ödeme ve tahsilat süreçlerinizi iş modelinize uygun şekilde planlayın. Sunulan ödeme seçenekleri ve koşullarını hesabınıza özel değerlendirin.", tag: "Ödeme Çözümleri" },
  { name: "AWS", icon: "cloud_done", title: "Büyümeye eşlik eden altyapı.", description: "Bulut teknolojileri, mağaza deneyiminin arkasındaki altyapıyı destekler. E-ticaret operasyonlarını ölçeklenebilir bir yaklaşımla ele alın.", tag: "Bulut Altyapısı" },
  { name: "Lojistik Ağı", icon: "local_shipping", title: "Vitrinden müşterinizin kapısına.", description: "Ürün seçimi kadar teslimat deneyimi de önemlidir. Tedarik, paketleme ve gönderi takibini bütün bir operasyon olarak planlayın.", tag: "Kargo & Operasyon" },
];

export function PartnersScreen() {
  return <MarketingPage>
    <PageIntro eyebrow="İş Ortaklarımız" title={<>Güçlü bağlantılar.<br /><span>Birlikte büyüyen ticaret.</span></>} description="Sosyal ticaret, ödeme, reklam ve lojistik. Alceix ekosistemindeki iş ortaklarımızla e-ticaret yolculuğunuzun her adımını bir araya getiriyoruz."><div className="mt-7"><Link className="public-button" href={routes.register}>Ekosisteme Katılın<span className="material-symbols-outlined text-[18px]" aria-hidden="true">north_east</span></Link></div></PageIntro>
    <section className="public-section"><div className="public-container"><PartnerLogos /><div className="mt-16"><span className="public-eyebrow">Tek Ekosistem, Birçok Bağlantı</span><h2 className="mt-3">Ticaretin her adımında<br />doğru uzmanlık.</h2><p className="public-section-description">İşinizi büyütürken ihtiyaç duyduğunuz çözümleri keşfedin. Her hizmetin kullanım koşulları ve kapsamı ilgili sağlayıcıya göre değişir.</p></div><div className="partner-service-grid">{services.map((item) => <article className="partner-service" key={item.name}><div className="w-full flex items-center justify-between gap-3"><span className="public-icon"><span className="material-symbols-outlined" aria-hidden="true">{item.icon}</span></span><span className="text-label-sm font-bold text-primary">{item.name}</span></div><h3>{item.title}</h3><p>{item.description}</p><span className="partner-service-tag">{item.tag}</span></article>)}</div></div></section>
    <section className="public-section public-section-soft"><div className="public-container partner-logistics"><div><span className="public-eyebrow">Entegre Lojistik</span><h2 className="mt-3">Siparişinizin yolculuğu<br />buradan devam eder.</h2><p className="public-section-description">Yurtiçi ve uluslararası gönderiler için taşıyıcı seçeneklerini keşfedin. Mağazanızın ihtiyaçlarına göre teslimat, gönderi takibi ve tedarik süreçlerini planlayın.</p><Link className="public-button mt-6" href={routes.suppliers}>Tedarik Ağını Keşfedin<span className="material-symbols-outlined text-[18px]" aria-hidden="true">arrow_forward</span></Link></div><div className="carrier-grid">{["Yurtiçi Kargo", "MNG Kargo", "Aras Kargo", "Sendeo", "DHL Express"].map((carrier) => <div key={carrier}>{carrier}</div>)}</div></div></section>
    <section className="public-section"><div className="public-container public-help"><div><span className="public-eyebrow">Birlikte Daha Fazlası</span><h2 className="mt-3">Siz de iş ortağımız olun.</h2><p>Üretici, marka veya çözüm sağlayıcısı mısınız?<br />Alceix ekosisteminde birlikte neler yapabileceğimizi konuşalım.</p></div><div className="public-help-actions"><Link className="public-button" href={routes.supplierApplication}>Tedarikçimiz Ol</Link><a className="public-button public-button-light" href="mailto:destek@alceix.com">İş Birliği İçin Yazın</a></div></div></section>
  </MarketingPage>;
}
