'use client';
import Link from 'next/link';
import {useState} from 'react';
import {platformRoutes as r} from '@/config/platform-routes';
import {useOperations} from '../components/operations-provider';
import {usePlatform} from '../components/provider';
import {Heading,Dialog,Field,Empty,Pagination,useFilters} from '../components/ui';
import {kindLabels,safePage} from '../utils/administration';
export function PlatformMessages(){const {accounts,administration,ready}=usePlatform(),{params,set}=useFilters(),q=params.get('q')||'',flagged=params.get('flagged')==='yes',kind=['store','supplier','creator'].includes(params.get('kind')||'')?params.get('kind'):'all';const list=accounts.flatMap(a=>a.threads.map(t=>({...t,account:a}))).filter(t=>(kind==='all'||t.account.kind===kind)&&(!flagged||administration.threads.some(c=>c.threadId===t.id&&c.flagged))&&`${t.account.name} ${t.partner} ${t.messages.map(m=>m.body).join(' ')}`.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))),page=safePage(params.get('page'),list.length);return <><Heading title="Platform Görüşmeleri" description="Mağaza, tedarikçi ve influencer hesaplarının kayıtlı görüşmelerini incele."/><div className="pa-toolbar"><input aria-label="Görüşme ara" value={q} onChange={e=>set('q',e.target.value)} placeholder="Üye, firma veya mesaj içeriği…"/><select aria-label="Görüşme hesap türü" value={kind||'all'} onChange={e=>set('kind',e.target.value)}><option value="all">Tüm Hesap Türleri</option>{Object.entries(kindLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select aria-label="Görüşme inceleme durumu" value={flagged?'yes':'all'} onChange={e=>set('flagged',e.target.value)}><option value="all">Tüm Görüşmeler</option><option value="yes">İncelemeye Alınanlar</option></select></div>{!ready?<Empty>Görüşmeler yükleniyor…</Empty>:list.length?<section className="ad-card pa-panel">{list.slice((page-1)*8,page*8).map(t=><article className="pa-row" key={t.id}><div><h3>{t.account.name} ↔ {t.partner}</h3><p className="pa-muted">{kindLabels[t.account.kind]} · {t.messages.length} mesaj</p><p className="pa-preline">{t.messages.at(-1)?.body.slice(0,140)}</p>{administration.threads.some(c=>c.threadId===t.id&&c.flagged)&&<span className="pa-pill review">İncelemede</span>}</div><Link className="ad-button light" href={r.thread(t.id)}>Görüşme Detayı</Link></article>)}</section>:<Empty>Bu filtrelerde görüşme bulunamadı.</Empty>}<Pagination total={list.length}/><p className="pa-note">Görüşmeler bu tarayıcıdaki demo kayıtlardır. Farklı tarafların bağımsız demo sohbetleri otomatik birleştirilmez; mesajlar bu ekrandan değiştirilmez.</p></>;}
export function PlatformThread({threadId}:{threadId:string}){const {can}=useOperations();const {accounts,administration,ready,saveThread}=usePlatform(),[editing,setEditing]=useState(false),[error,setError]=useState('');const account=accounts.find(a=>a.threads.some(t=>t.id===threadId)),thread=account?.threads.find(t=>t.id===threadId);if(!ready)return <Empty>Görüşme yükleniyor…</Empty>;if(!thread||!account)return <Empty>Görüşme bulunamadı veya bu tarayıcıda kayıtlı değil. <Link className="pa-link" href={r.messages}>Görüşmelere Dön</Link></Empty>;const control=administration.threads.find(t=>t.threadId===thread.id);return <><Link className="pa-link" href={r.messages}>← Platform Görüşmeleri</Link><Heading title={`${account.name} ↔ ${thread.partner}`} description="Kayıtlı konuşma ve yönetici incelemesi"><button className="ad-button" disabled={!can('messages',true)} onClick={()=>setEditing(true)}>{control?.flagged?'İncelemeyi Güncelle':'İncelemeye Al'}</button><Link className="ad-button light" href={thread.panelUrl}>Hesabın Mesaj Ekranı ↗</Link></Heading><div className="pa-detail-grid"><section className="ad-card pa-panel"><h2>Konuşma Kaydı</h2><div role="log" aria-label="Platform görüşme mesajları">{thread.messages.map((m,i)=><article className="pa-message" key={m.id+String(i)}><strong>{m.sender}</strong><p>{m.body}</p></article>)}</div></section><aside><section className="ad-card pa-panel"><h2>Görüşme Bilgileri</h2><dl className="pa-kv"><div><dt>Hesap</dt><dd><Link className="pa-link" href={r.member(account.kind,account.slug)}>{account.name}</Link></dd></div><div><dt>Partner</dt><dd>{thread.partner}</dd></div><div><dt>Mesaj Adedi</dt><dd>{thread.messages.length}</dd></div><div><dt>İnceleme Durumu</dt><dd>{control?.flagged?'İncelemede':'İnceleme Açık Değil'}</dd></div></dl><p className="pa-preline">{control?.note||'Henüz yönetici inceleme notu yok.'}</p><p className="pa-note">Bu alan görüşmeye mesaj göndermez. İnceleme notları yalnızca ana yönetim demo kaydında tutulur.</p></section></aside></div>{editing&&<Dialog title="Görüşme İnceleme Kaydı" close={()=>setEditing(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),note=String(f.get('note')||'').trim();if(note.length<5){setError('En az 5 karakterlik inceleme notu girin.');return;}if(can('messages',true)&&saveThread({threadId:thread.id,flagged:f.get('flagged')==='on',note})){setEditing(false);setError('');}}}><label className="pa-checkbox"><input type="checkbox" name="flagged" defaultChecked={control?.flagged??true}/>İnceleme açık</label><Field label="Yönetici İnceleme Notu"><textarea name="note" autoFocus required minLength={5} maxLength={2000} defaultValue={control?.note||''}/></Field>{error&&<p className="pa-error" role="alert">{error}</p>}<button className="ad-button">İncelemeyi Kaydet</button></form></Dialog>}</>;}
