'use client';
import {useState} from 'react';
import {useOperations} from '../components/operations-provider';
import {Dialog,Empty,Field,Heading} from '../components/ui';
import {pageLabels,roleLabels,rolePages,validEmail} from '../utils/operations';
import type {Staff,StaffRole,PageKey} from '../types/operations';
export function PlatformTeam(){const {operations,commit,can,ready,preview}=useOperations(),[editing,setEditing]=useState<Staff|null>(null),[error,setError]=useState('');function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),email=String(f.get('email')||'').trim().toLowerCase();if(!name||!validEmail(email)||operations.staff.some(s=>s.email.toLowerCase()===email&&s.id!==editing.id)){setError('Ad ve benzersiz e-posta adresini kontrol edin.');return;}const next={...editing,name,email};if(commit({...operations,staff:[...operations.staff.filter(s=>s.id!==next.id),next]},'team',`${name} ekip yetkileri kaydedildi`))setEditing(null);}
 return <><Heading title="Alceix Ekip & Yetki Yönetimi" description="Çalışanları davet et, görevlerini ve görebilecekleri sayfaları belirle."><button className="ad-button" disabled={!can('team',true)||!ready} onClick={()=>{setError('');setEditing({id:crypto.randomUUID(),name:'',email:'',role:'support',status:'invited',pages:[...rolePages.support],write:true});}}>+ Çalışan Ekle</button></Heading><div className="pa-note">Davetler ve rol görünümü yerel demodur. Gerçek e-posta daveti ve sunucu yetkilendirmesi bağlı değildir. Ana yönetici kaydı korunur.</div>{!ready?<Empty>Ekip yükleniyor…</Empty>:<section className="ad-card pa-panel">{operations.staff.map(s=><article className="pa-row" key={s.id}><div><h3>{s.name}</h3><p className="pa-muted">{s.email} · {roleLabels[s.role]} · {s.status==='active'?'Aktif':s.status==='invited'?'Davet Hazırlandı':'Pasif'}</p><p>{s.pages.map(p=>pageLabels[p]).join(' · ')}</p><span className="pa-pill">{s.write?'Düzenleyebilir':'Yalnızca Görüntüleme'}</span></div><div className="pa-actions">{s.status==='active'&&<button className="ad-button light" onClick={()=>preview(s.id)}>Rolü Önizle</button>}{s.id!=='owner'&&<button className="ad-button light" disabled={!can('team',true)} onClick={()=>{setError('');setEditing({...s,pages:[...s.pages]});}}>Düzenle</button>}</div></article>)}</section>}{editing&&<Dialog title="Çalışan & Sayfa Yetkileri" close={()=>setEditing(null)}><form onSubmit={save}><Field label="Ad Soyad"><input name="name" required maxLength={100} defaultValue={editing.name}/></Field><Field label="E-posta"><input name="email" type="email" required maxLength={254} defaultValue={editing.email}/></Field><Field label="Rol"><select value={editing.role} onChange={e=>{const role=e.target.value as StaffRole;setEditing({...editing,role,pages:[...rolePages[role]]});}}>{Object.entries(roleLabels).filter(([v])=>v!=='owner').map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field><Field label="Çalışan Durumu"><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Staff['status']})}><option value="invited">Davet Hazırlandı</option><option value="active">Demo Aktif</option><option value="paused">Pasif</option></select></Field><fieldset className="pa-permissions"><legend>Görebileceği Sayfalar</legend>{Object.entries(pageLabels).map(([p,label])=><label key={p} className="pa-checkbox"><input type="checkbox" checked={editing.pages.includes(p as PageKey)} onChange={e=>setEditing({...editing,pages:e.target.checked?[...editing.pages,p as PageKey]:editing.pages.filter(x=>x!==p)})}/>{label}</label>)}</fieldset><label className="pa-checkbox"><input type="checkbox" checked={editing.write} onChange={e=>setEditing({...editing,write:e.target.checked})}/>Seçilen sayfalarda düzenleme izni</label>{error&&<p className="pa-error" role="alert">{error}</p>}<button className="ad-button">Çalışanı Kaydet</button></form></Dialog>}</>;
}
