import Image from "next/image";
import Link from "next/link";
import { MarketingPage } from "@/components/layout/marketing-page";
import { routes } from "@/config/routes";
import { ContactForm } from "../components/contact-form";
import { contact, contactQuestions } from "../config/contact";
import "../contact.css";

function Icon({ name }: { name: string }) { return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>; }
const channels = [
  { icon: "storefront", title: "E-Ticaret & Satış Masası", description: "Mağaza kurulumu, ürün vitrini ve satış yolculuğunuz.", href: routes.register, action: "Mağaza açmayı keşfedin" },
  { icon: "local_shipping", title: "B2B Tedarikçi & Dropshipping", description: "Ürün kataloğu ve tedarik iş birlikleriniz için doğru adres.", href: routes.suppliers, action: "Tedarik ağını inceleyin" },
  { icon: "campaign", title: "Influencer & Marka İş Birlikleri", description: "İçerik üreticileri ve markaları buluşturan yeni fırsatlar.", href: routes.influencer, action: "İş birliği seçeneklerini görün" },
  { icon: "support_agent", title: "Teknik Destek & Entegrasyon", description: "Yaşadığınız sorunu ve mağaza adresinizi ekibimizle paylaşın.", href: `mailto:${contact.email}`, action: contact.email },
] as const;

export function ContactScreen() {
  return <MarketingPage className="contact-page">
    <section className="contact-hero"><div className="public-container">
      <div className="public-breadcrumb"><Link href={routes.home}>Ana Sayfa</Link><span aria-hidden="true">›</span><span>İletişim & Destek</span></div>
      <div className="contact-hero-copy"><span className="contact-tag"><Icon name="support_agent" /> Birlikte daha ileriye</span><h1>Sorularınız mı Var?<br /><span>Uzman Ekibimiz</span> Yanınızda.</h1><p>E-ticaret dünyasında, mağazanızın her adımında yanınızdayız.<br />Aklınızdaki soruları paylaşın; birlikte bir sonraki adımı planlayalım.</p></div>
      <div className="contact-highlights">{[{ icon: "forum", title: "Tek noktadan iletişim", text: "Talebinizi doğru ekiple paylaşın" }, { icon: "verified_user", title: "Size özel yönlendirme", text: "İhtiyacınıza uygun başlangıç" }, { icon: "schedule", title: "Her zaman talep oluşturun", text: "Mesajınızı dilediğiniz an hazırlayın" }].map(item => <div key={item.title}><span className="public-icon"><Icon name={item.icon} /></span><div><b>{item.title}</b><small>{item.text}</small></div></div>)}</div>
    </div></section>
    <section className="contact-content public-container" aria-label="İletişim kanalları"><ContactForm /><aside className="contact-channels">
      <div className="contact-live"><div className="contact-live-top"><Icon name="chat" /><span>Destek kanalı</span></div><h2>WhatsApp & Canlı Destek</h2><p>Mağazanızla ilgili sorularınızı paylaşın. Size en uygun iletişim kanalını birlikte belirleyelim.</p><a className="public-button" href="#contact-form">Destek Talebi Hazırla <span aria-hidden="true">→</span></a><small>WhatsApp bağlantısı yakında.</small></div>
      {channels.map(channel => <article className="contact-card contact-channel" key={channel.title}><span className="public-icon"><Icon name={channel.icon} /></span><div><h3>{channel.title}</h3><p>{channel.description}</p><Link href={channel.href}>{channel.action} <span aria-hidden="true">↗</span></Link></div></article>)}
      <div className="contact-note"><Icon name="lock" /><p>Hesap güvenliğiniz için şifrenizi veya ödeme bilgilerinizi mesajınıza eklemeyin.</p></div>
    </aside></section>
    <section className="contact-offices public-container"><div className="contact-section-heading"><div><span className="public-eyebrow">Teknoloji & iş birliği</span><h2>Ofislerimiz & Yerleşkelerimiz</h2></div><p>İş birliği fikirlerinizi birlikte konuşalım.<br />Ziyaretinizden önce randevu oluşturun.</p></div><div className="contact-office-grid">
      <article className="contact-card contact-office"><div className="contact-office-photo"><Image src="/about/image-0.webp" width={800} height={600} sizes="(max-width: 760px) 90vw, 600px" alt="Modern ofis ve ortak çalışma alanı" /><span className="contact-photo-tag">Maslak · İstanbul</span><div><h3>Birlikte üretiyor, birlikte büyüyoruz.</h3><p>Fikirlerinizi bir sonraki adımla buluşturalım.</p></div></div><div className="contact-office-info"><p><Icon name="location_on" />{contact.address}</p><p><Icon name="schedule" />{contact.hours}</p><div><a href={`mailto:${contact.email}?subject=Ofis%20ziyareti%20randevusu`} className="public-button public-button-light">Ziyaret Randevusu Al ↗</a><a href={contact.map} target="_blank" rel="noopener noreferrer">Yol Tarifi Al ↗</a></div></div></article>
      <div className="contact-office-side"><article className="contact-card contact-map-card"><div className="contact-map-heading"><h3>Harita Konumu</h3><a href={contact.map} target="_blank" rel="noopener noreferrer">Haritada Aç ↗</a></div><a href={contact.map} target="_blank" rel="noopener noreferrer" className="contact-map" aria-label="Maslak ofisi için Google Maps yol tarifini aç"><svg viewBox="0 0 500 210" aria-hidden="true"><rect width="500" height="210" fill="#edf3ed" /><path d="M390 0C345 56 462 90 396 143S422 185 398 210H500V0Z" fill="#b8d6f7" /><g fill="none" stroke="#fff" strokeWidth="15"><path d="M-30 45L480 172M34 210L305 -25M0 163L360 92M133 0L194 210" /></g><g fill="none" stroke="#d8dced" strokeWidth="4"><path d="M-30 45L480 172M34 210L305 -25M0 163L360 92M133 0L194 210" /></g><g fill="#d4e7cb"><rect x="30" y="70" width="64" height="35" rx="7"/><rect x="270" y="30" width="55" height="45" rx="7"/><rect x="230" y="152" width="90" height="39" rx="7"/></g><circle cx="248" cy="107" r="36" fill="#0066ff" opacity=".12"/><circle cx="248" cy="107" r="17" fill="#0066ff"/><circle cx="248" cy="107" r="6" fill="white"/><text x="275" y="113" fill="#384b6d" fontSize="17" fontWeight="700">Maslak</text></svg><span>İstanbul · Maslak</span></a><small className="contact-muted">Bölge görseli temsilidir. Tam adres için haritayı açın.</small></article>
      <article className="contact-card contact-office-mini"><span className="public-icon"><Icon name="lightbulb" /></span><div><h3>İş Birliği & İnovasyon</h3><p>Yeni bir fikriniz mi var? Alceix ekibiyle paylaşın.</p><a href="#contact-form">Fikrinizi Anlatın →</a></div></article><article className="contact-card contact-office-mini"><span className="public-icon"><Icon name="handshake" /></span><div><h3>Markanız için Birlikte Planlayalım</h3><p>İş ortaklığı ve kurumsal çözümlerimizi keşfedin.</p><Link href={routes.partners}>İş Ortaklarımız →</Link></div></article></div>
    </div></section>
    <section className="contact-faq public-container"><div><span className="public-eyebrow">Sık sorulan sorular</span><h2>Hızlı Cevaplar & Çözüm Rehberi</h2><p>İlk adımınızdan iş birliğinize, merak ettiklerinize kısa cevaplar.</p></div><div>{contactQuestions.map(item => <details className="faq-item" key={item.question}><summary>{item.question}<Icon name="expand_more" /></summary><p className="faq-answer">{item.answer}</p></details>)}</div><Link href={routes.faq}>Tüm Sık Sorulan Sorular →</Link></section>
    <section className="public-container contact-final"><div><span className="contact-tag">Bir mesaj uzağınızdayız</span><h2>Hâlâ sorularınız mı var?</h2><p>İlk mağazanızdan yeni iş birliklerine, Alceix yanınızda.</p></div><div><Link href={routes.register} className="public-button">Hemen Ücretsiz Başla →</Link><a href="#contact-form" className="public-button contact-final-secondary">Destek Talebi Hazırla</a></div></section>
  </MarketingPage>;
}
