"use client";
import Link from 'next/link';
import {useRef,useState} from 'react';
import {routes} from '@/config/routes';
import {recoveryEmailIssue} from '../utils/auth-validation';
export function PasswordRecoveryForm(){
 const [email,setEmail]=useState(''),[error,setError]=useState(''),[stage,setStage]=useState<'email'|'review'>('email');const emailInput=useRef<HTMLInputElement>(null);
 return <div className="auth-card"><Link className="auth-back" href={routes.login}><span className="material-symbols-outlined" aria-hidden="true">arrow_back</span>Girişe Dön</Link><span className="auth-recovery-icon material-symbols-outlined" aria-hidden="true">lock_reset</span><h2>Şifremi unuttum</h2><p className="auth-subtitle">Hesabınızın e-posta adresini girin, şifre yenileme isteğinizi hazırlayın.</p>{stage==='email'?<form className="auth-form" onSubmit={event=>{event.preventDefault();const issue=recoveryEmailIssue(email);setError(issue);if(!issue)setStage('review');}}><div className="auth-field"><label htmlFor="recovery-email">E-posta Adresi</label><div className="auth-input"><input ref={emailInput} id="recovery-email" name="email" type="email" required maxLength={254} autoComplete="email" placeholder="ornek@eposta.com" value={email} aria-invalid={!!error} aria-describedby={error?'recovery-error':'recovery-hint'} onChange={event=>{setEmail(event.target.value);setError('');}}/></div><small id="recovery-hint">Kayıt olurken kullandığınız adresi yazın.</small></div>{error&&<p id="recovery-error" className="auth-error" role="alert">{error}</p>}<button className="public-button w-full" type="submit">Şifre Yenileme İsteği Hazırla<span className="material-symbols-outlined" aria-hidden="true">arrow_forward</span></button><p className="auth-demo-hint">Demo önizleme · Şifre sıfırlama servisi henüz bağlı değil.</p></form>:<section className="auth-recovery-review" aria-label="Şifre yenileme isteği"><span className="material-symbols-outlined" aria-hidden="true">mark_email_read</span><h3>İsteğiniz hazır</h3><p><strong>{email.trim()}</strong> adresi için şifre yenileme akışını hazırladınız.</p><div className="auth-message" role="status">Bu demo ekranında e-posta gönderilmedi ve şifreniz değiştirilmedi. Gerçek sıfırlama bağlantısı, hesap servisi bağlandığında gönderilecek.</div><button className="auth-edit-email" type="button" onClick={()=>{setStage('email');requestAnimationFrame(()=>emailInput.current?.focus());}}>E-posta Adresini Değiştir</button><Link className="public-button w-full" href={routes.login}>Giriş Sayfasına Dön</Link></section>}<p className="auth-card-foot">Yardıma mı ihtiyacınız var? <a href="mailto:destek@alceix.com">Destek ekibine yazın</a></p></div>;
}
