'use client';
import {useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import type {Review,ReviewEntity} from '../types/review';
import {initialReviews,reviewProfiles,kindLabels} from '../mocks/reviews';
import {isReviews,saveReview,replyToReview,ratingSummary,reviewQuery} from '../utils/review';
import '../reviews.css';
export function ReviewsScreen({owner,scope,eligibleTargets}:{owner:ReviewEntity;scope:string;eligibleTargets?:ReviewEntity[]}) {
 const key=`alceix:reviews:${scope}:v1`;const [reviews,setReviews]=useState<Review[]>(()=>initialReviews(owner));const [ready,setReady]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');const [replying,setReplying]=useState('');const dialog=useRef<HTMLDialogElement>(null);const params=useSearchParams();
 const view=params.get('view')==='all'?'all':params.get('view')==='given'?'given':'received';const kind=['store','supplier','creator'].includes(params.get('kind')||'')?params.get('kind')!:'all';const rawRating=Number(params.get('rating'));const rating=Number.isInteger(rawRating)&&rawRating>=1&&rawRating<=5?rawRating:0;const q=params.get('q')||'';const sort=['high','low'].includes(params.get('sort')||'')?params.get('sort')!:'newest';const eligible=(eligibleTargets||reviewProfiles.filter(p=>p.kind!==owner.kind)).filter(p=>p.id!==owner.id);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const saved:unknown=JSON.parse(raw);if(isReviews(saved))setReviews(saved);else setNotice('Kayıt okunamadı; örnek değerlendirmeler gösteriliyor.');}}catch{setNotice('Tarayıcı kaydı okunamadı.');}setReady(true);},[key]);
 function persist(next:Review[]){if(!isReviews(next)){setError('Değerlendirme kaydı geçersiz.');return false;}try{localStorage.setItem(key,JSON.stringify(next));setReviews(next);setError('');return true;}catch{setError('Tarayıcıya kaydedilemedi. Tekrar deneyin.');return false;}}
 function param(k:string,v:string){const u=new URL(window.location.href);const query=reviewQuery(u.search,k,v);window.history.replaceState(null,'',u.pathname+(query?'?'+query:''));}
 const received=reviews.filter(r=>r.target.id===owner.id),summary=ratingSummary(received);const filtered=reviews.filter(r=>(view==='all'||view==='received'&&r.target.id===owner.id||view==='given'&&r.author.id===owner.id)&&(kind==='all'||r.target.kind===kind)&&(!rating||r.rating===rating)&&`${r.body} ${r.target.name} ${r.author.name}`.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).sort((a,b)=>sort==='high'?b.rating-a.rating:sort==='low'?a.rating-b.rating:b.createdAt.localeCompare(a.createdAt));const max=Math.max(1,Math.ceil(filtered.length/6));const raw=Number(params.get('page')||1);const page=Number.isSafeInteger(raw)&&raw>0?Math.min(raw,max):1;
 return <div className="rv-page"><header className="rv-heading"><div><span className="ad-eyebrow">GÜVEN & İŞ BİRLİĞİ · {owner.name}</span><h1>Yorumlar & Değerlendirmeler</h1><p>Mağaza, tedarikçi ve influencer profillerinin 5 üzerinden değerlendirmelerini inceleyin.</p></div><button className="ad-button" disabled={!ready||!eligible.length} onClick={()=>{setError('');dialog.current?.showModal();}}>+ Değerlendirme Yaz</button></header>
 <section className="rv-summary ad-card"><div><small>PROFİL PUANINIZ</small><strong>{summary.average.toLocaleString('tr-TR',{maximumFractionDigits:1})}<span>/ 5</span></strong><span className="rv-stars" aria-label={`${summary.average} / 5`}>★★★★★</span><p>{summary.count} örnek değerlendirme</p></div><div className="rv-bars">{summary.distribution.map(d=><div key={d.rating}><span>{d.rating} ★</span><progress value={d.count} max={Math.max(1,summary.count)} aria-label={`${d.rating} yıldız: ${d.count} yorum`}/><b>{d.count}</b></div>)}</div><div className="rv-summary-note"><h2>Güvenle birlikte büyüyün</h2><p>Gelen yorumlara yanıt verin, iş birliği deneyiminizi paylaşın.</p><span className="ad-pill blue">Yerel demo değerlendirmeleri</span><small>Puanlar temsili örnektir. Gerçek alışveriş ve iş birliği doğrulaması backend bağlantısı gerektirir.</small></div></section>
 <nav className="rv-tabs" aria-label="Değerlendirme görünümü">{[['received','Gelen Yorumlar'],['given','Yaptığım Değerlendirmeler'],['all','Tüm Profiller']].map(([v,l])=><button key={v} aria-pressed={view===v} onClick={()=>param('view',v)}>{l}</button>)}</nav><div className="rv-toolbar"><input aria-label="Yorum ara" placeholder="Yorum, firma veya kişi ara…" value={q} onChange={e=>param('q',e.target.value.slice(0,120))}/><select aria-label="Profil türü" value={kind} onChange={e=>param('kind',e.target.value)}><option value="all">Tüm Profil Türleri</option>{Object.entries(kindLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Yıldız puanı" value={rating} onChange={e=>param('rating',e.target.value)}><option value={0}>Tüm Puanlar</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} yıldız</option>)}</select><select aria-label="Yorum sıralaması" value={sort} onChange={e=>param('sort',e.target.value)}><option value="newest">En Yeni</option><option value="high">Puan: Yüksek</option><option value="low">Puan: Düşük</option></select></div>
 <div className="rv-list">{filtered.slice((page-1)*6,page*6).map(r=><article key={r.id} className="ad-card rv-review"><header><span className="rv-avatar">{r.author.name.slice(0,2).toUpperCase()}</span><div><h2>{r.author.name}</h2><small>{kindLabels[r.author.kind]} · {r.author.city}</small></div><div className="rv-rating"><span className="rv-stars" aria-label={`${r.rating} / 5`}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span><small>{new Date(r.createdAt).toLocaleDateString('tr-TR')}</small></div></header><div className="rv-target"><span className="ad-pill blue">{kindLabels[r.target.kind]}</span><b>{r.target.name}</b><span>Örnek iş birliği</span></div><p>{r.body}</p>{r.reply&&<blockquote><b>{r.target.name} yanıtı</b><p>{r.reply}</p></blockquote>}<footer>{r.target.id===owner.id&&<button onClick={()=>{setReplying(replying===r.id?'':r.id);setError('');}}>{r.reply?'Yanıtı Düzenle':'Yanıt Yaz'}</button>}<button disabled={r.reported} onClick={()=>{if(persist(reviews.map(x=>x.id===r.id?{...x,reported:true}:x)))setNotice('Demo inceleme kaydı oluşturuldu. Yorum gizlenmedi.');}}>{r.reported?'İnceleme Kaydı Oluşturuldu':'İnceleme Talep Et'}</button></footer>{replying===r.id&&<form onSubmit={e=>{e.preventDefault();try{if(persist(replyToReview(reviews,owner.id,r.id,String(new FormData(e.currentTarget).get('reply'))))){setReplying('');setNotice('Yanıt yerel değerlendirmeye kaydedildi.');}}catch(c){setError(c instanceof Error?c.message:'Yanıt kaydedilemedi.');}}}><label htmlFor={`reply-${r.id}`}>Profil Yanıtınız</label><textarea id={`reply-${r.id}`} name="reply" defaultValue={r.reply} maxLength={1000} minLength={2} required/><button className="ad-button">Yanıtı Kaydet</button></form>}</article>)}</div>{!filtered.length&&<div className="ad-card rv-empty"><h2>Değerlendirme bulunamadı</h2><p>Filtreleri değiştirin veya ilk iş birliği yorumunuzu yazın.</p></div>}<div className="rv-pagination"><span>{filtered.length} yorum · Sayfa {page} / {max}</span><button disabled={page===1} onClick={()=>param('page',String(page-1))}>Önceki</button><button disabled={page===max} onClick={()=>param('page',String(page+1))}>Sonraki</button></div>{error&&<p role="alert" className="rv-error">{error}</p>}{notice&&<div role="status" className="rv-notice">{notice}<button aria-label="Bildirimi kapat" onClick={()=>setNotice('')}>×</button></div>}
 <dialog ref={dialog} className="ad-dialog" aria-label="Değerlendirme Yaz"><div className="ad-dialog-heading"><h2>İş Birliğini Değerlendir</h2><button autoFocus aria-label="Pencereyi kapat" onClick={()=>dialog.current?.close()}>×</button></div><form className="rv-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),target=eligible.find(t=>t.id===String(f.get('target')));if(!target)return;try{if(persist(saveReview(reviews,owner,target,Number(f.get('rating')),String(f.get('body')),eligible.map(t=>t.id)))){dialog.current?.close();param('view','given');setNotice('Değerlendirme yerel demo kaydına eklendi; gerçek profile gönderilmedi.');}}catch(c){setError(c instanceof Error?c.message:'Değerlendirme kaydedilemedi.');}}}><label>Değerlendirilecek Profil<select name="target">{eligible.map(t=><option key={t.id} value={t.id}>{t.name} · {kindLabels[t.kind]}</option>)}</select></label><label>Puan · 5 Üzerinden<select name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5 {'★'.repeat(n)}</option>)}</select></label><label>İş Birliği Yorumunuz<textarea name="body" minLength={10} maxLength={2000} rows={4} required placeholder="Ürün, teslimat veya içerik deneyiminizi paylaşın…"/></label><small>Örnek bağlantılar kullanılır. Aynı profile tekrar yazmak önceki değerlendirmeyi günceller.</small>{error&&<p role="alert" className="rv-error">{error}</p>}<button className="ad-button">Demo Değerlendirmeyi Kaydet</button></form></dialog></div>;
}
