import type {Review,ReviewEntity} from '../types/review';
const entity=(v:unknown):v is ReviewEntity=>{if(!v||typeof v!=='object')return false;const r=v as Record<string,unknown>;return ['id','name','city'].every(k=>typeof r[k]==='string'&&(r[k] as string).length>0&&(r[k] as string).length<=150)&&['store','supplier','creator'].includes(String(r.kind));};
export function isReviews(value:unknown):value is Review[]{return Array.isArray(value)&&value.length<=200&&new Set(value.map(r=>r?.id)).size===value.length&&value.every(r=>r&&typeof r==='object'&&typeof r.id==='string'&&r.id.length<=80&&entity(r.target)&&entity(r.author)&&r.target.id!==r.author.id&&Number.isInteger(r.rating)&&r.rating>=1&&r.rating<=5&&typeof r.body==='string'&&r.body.trim().length>=10&&r.body.length<=2000&&typeof r.reply==='string'&&r.reply.length<=1000&&typeof r.createdAt==='string'&&Number.isFinite(Date.parse(r.createdAt))&&typeof r.reported==='boolean');}
export function saveReview(reviews:Review[],author:ReviewEntity,target:ReviewEntity,rating:number,body:string,eligibleIds:string[]):Review[]{
 if(author.id===target.id||!eligibleIds.includes(target.id))throw new Error('Yalnızca iş ilişkisi bulunan diğer profilleri değerlendirebilirsiniz.');
 if(!Number.isInteger(rating)||rating<1||rating>5||body.trim().length<10||body.length>2000)throw new Error('1–5 yıldız seçin ve 10–2000 karakterlik yorum yazın.');
 const existing=reviews.find(r=>r.author.id===author.id&&r.target.id===target.id);if(!existing&&reviews.length>=200)throw new Error('Yerel değerlendirme limiti doldu.');
 const review:Review={id:existing?.id||crypto.randomUUID(),author,target,rating,body:body.trim(),createdAt:existing?.createdAt||new Date().toISOString(),reply:existing?.reply||'',reported:existing?.reported||false};return existing?reviews.map(r=>r.id===existing.id?review:r):[review,...reviews];
}
export function replyToReview(reviews:Review[],ownerId:string,id:string,reply:string):Review[]{const review=reviews.find(r=>r.id===id);if(!review||review.target.id!==ownerId||reply.trim().length<2||reply.length>1000)throw new Error('Yalnızca kendi profilinize gelen yoruma 2–1000 karakterlik yanıt yazabilirsiniz.');return reviews.map(r=>r.id===id?{...r,reply:reply.trim()}:r);}
export function ratingSummary(reviews:Review[]){return {average:reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:0,count:reviews.length,distribution:[5,4,3,2,1].map(rating=>({rating,count:reviews.filter(r=>r.rating===rating).length}))};}

export function reviewQuery(current:string,key:string,value:string):string {const next=new URLSearchParams(current);if(value&&(value!=="all"||key==="view")&&value!=="0")next.set(key,value);else next.delete(key);if(key!=="page")next.delete("page");return next.toString();}
