"use client";
import {useState} from "react";
import {money} from "../utils/workspace";
export function SupplierChart() {
 const [month,setMonth]=useState(false);const [selected,setSelected]=useState(3);
 const labels=month?["1 Eyl","5 Eyl","10 Eyl","15 Eyl","20 Eyl","25 Eyl","30 Eyl"]:["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"];
 const values=(month?[18400,22800,19600,27400,24200,31000,28400]:[2800,4600,3900,5200,4800,6900,5600]).map(v=>v*100);
 const max=month?3500000:800000;const points=values.map((v,i)=>({x:65+i*133,y:180-v/max*150}));
 const path=points.reduce((s,p,i)=>i?`${s} C ${points[i-1].x+66} ${points[i-1].y}, ${p.x-66} ${p.y}, ${p.x} ${p.y}`:`M ${p.x} ${p.y}`,"");
 return <section id="supplier-report" className="ad-card ad-chart"><div className="ad-section-heading"><div><span className="ad-eyebrow">TEDARİK SATIŞLARINIZIN PERFORMANSI</span><h2>B2B satışların genel görünümü</h2><p>Alceix mağazalarına sağladığınız ürünlerin örnek gelir akışı.</p></div><div className="ad-period"><button aria-pressed={!month} onClick={()=>setMonth(false)}>Bu hafta</button><button aria-pressed={month} onClick={()=>setMonth(true)}>Bu ay</button></div></div><div className="ad-chart-summary"><strong>{money(values.reduce((s,v)=>s+v,0))}</strong><span className="ad-pill green">Örnek tedarik geliri</span></div><div className="ad-chart-scroll"><svg viewBox="0 0 930 220" role="img" aria-label="Örnek B2B satış gelirleri"><defs><linearGradient id="supplier-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#2464ee" stopOpacity=".2"/><stop offset="1" stopColor="#2464ee" stopOpacity="0"/></linearGradient></defs>{[30,80,130,180].map(y=><line key={y} x1="65" x2="865" y1={y} y2={y} stroke="#e8edf8" strokeDasharray="5 7"/>)}<path d={`${path} L 863 180 L 65 180 Z`} fill="url(#supplier-chart-fill)"/><path d={path} fill="none" stroke="#2e65f1" strokeWidth="3"/><circle cx={points[selected].x} cy={points[selected].y} r="6" fill="#2e65f1" stroke="white" strokeWidth="3"/>{points.map((p,i)=><g key={labels[i]}><text x={p.x} y="209" textAnchor="middle" fill="#7c8ba4" fontSize="12">{labels[i]}</text><rect x={p.x-45} y="10" width="90" height="175" fill="transparent" onPointerEnter={()=>setSelected(i)}/></g>)}</svg></div><div className="ad-chart-days">{labels.map((label,i)=><button key={label} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{label}</button>)}</div><p className="ad-chart-selected" aria-live="polite">{labels[selected]} · <b>{money(values[selected])}</b> örnek tedarik geliri</p></section>;
}
