import type {TeamMember,ChatMessage,OpenCampaign,SupplierReview,EmailJob} from '../types/collaboration';
import {validEmail} from './profile';
export {validEmail,isProfile} from './profile';
import {creators} from '../mocks/influencer';
import {suppliers} from '../mocks/suppliers';
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const str=(v:unknown,max=2000):v is string=>typeof v==='string'&&v.length<=max;
export function isTeam(v:unknown):v is TeamMember[]{return Array.isArray(v)&&v.length<=50&&v.every(m=>record(m)&&str(m.id,100)&&str(m.name,80)&&str(m.email,254)&&validEmail(m.email as string)&&['owner','editor','support','viewer'].includes(String(m.role))&&['active','invited'].includes(String(m.status)))&&v.filter(m=>m.role==='owner'&&m.status==='active').length===1&&new Set(v.map(m=>m.email.toLowerCase())).size===v.length;}
export function isThread(id:string){if(id.split(':').length!==2)return false;const [kind,key]=id.split(':');return kind==='supplier'?suppliers.some(s=>s.id===key):kind==='creator'&&creators.some(c=>c.id===key);}
export function containsExternalContact(text:string){return /(?:https?:|www\.|\b[\w.+-]+@[\w.-]+\.[a-z]{2,}|(?:\+?\d[\s().-]*){10,}|whatsapp|telegram)/i.test(text);}
export function isMessages(v:unknown):v is ChatMessage[]{return Array.isArray(v)&&v.length<=500&&v.every(m=>record(m)&&str(m.id,100)&&str(m.thread,100)&&isThread(m.thread as string)&&str(m.text,2000)&&!!m.text&&!containsExternalContact(m.text as string)&&str(m.createdAt,40)&&Number.isFinite(Date.parse(m.createdAt as string)));}
export function isOpenCampaigns(v:unknown):v is OpenCampaign[]{return Array.isArray(v)&&v.length<=100&&v.every(c=>record(c)&&str(c.id,100)&&str(c.title,100)&&!!c.title&&str(c.brief,2000)&&str(c.format,80)&&Number.isSafeInteger(c.budgetCents)&&Number(c.budgetCents)>0&&Number(c.budgetCents)<=100000000&&str(c.deadline,10)&&/^\d{4}-\d{2}-\d{2}$/.test(c.deadline as string)&&Number.isFinite(Date.parse(c.deadline as string))&&Number.isInteger(c.slots)&&Number(c.slots)>0&&Number(c.slots)<=10&&['open','closed'].includes(String(c.status))&&Array.isArray(c.applications)&&c.applications.length<=creators.length&&c.applications.every(a=>record(a)&&creators.some(p=>p.id===a.creatorId)&&['new','accepted','rejected'].includes(String(a.status))&&str(a.note,500))&&new Set(c.applications.map(a=>a.creatorId)).size===c.applications.length&&c.applications.filter(a=>a.status==='accepted').length<=Number(c.slots));}
export function isReviews(v:unknown):v is SupplierReview[]{return Array.isArray(v)&&v.length<=suppliers.length&&v.every(r=>record(r)&&suppliers.some(s=>s.id===r.supplierId)&&str(r.storeName,100)&&Number.isInteger(r.rating)&&Number(r.rating)>=1&&Number(r.rating)<=5&&str(r.text,1000)&&!!r.text&&str(r.createdAt,40)&&Number.isFinite(Date.parse(r.createdAt)))&&new Set(v.map(r=>r.supplierId)).size===v.length;}
export function isEmailJobs(v:unknown):v is EmailJob[]{return Array.isArray(v)&&v.length<=100&&v.every(j=>record(j)&&str(j.id,100)&&str(j.subject,150)&&!!j.subject&&str(j.body,3000)&&!!j.body&&Array.isArray(j.recipients)&&j.recipients.length<=500&&j.recipients.every((e:unknown)=>typeof e==='string'&&validEmail(e))&&str(j.createdAt,40)&&Number.isFinite(Date.parse(j.createdAt as string)));}
export function isConnections(v:unknown):v is string[]{return Array.isArray(v)&&v.length<=suppliers.length&&v.every(id=>suppliers.some(s=>s.id===id));}
export function isPrices(v:unknown):v is Record<string,number>{return record(v)&&Object.entries(v).every(([key,price])=>/^[a-z-]+:urun-[1-4]$/.test(key)&&suppliers.some(s=>key.startsWith(s.id+':'))&&Number.isSafeInteger(price)&&Number(price)>0&&Number(price)<=100000000);}
