'use client';
import Link from 'next/link';
import Image from 'next/image';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {influencerRoutes as r} from '@/config/influencer-routes';
import {useCreatorWorkspace} from './workspace-provider';
import {Icon} from './ui';
import '../influencer-admin.css';
export function InfluencerShell({children}:{children:React.ReactNode}){const {workspace,creatorId,notice,notify}=useCreatorWorkspace(),path=usePathname(),[open,setOpen]=useState(false);useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);const c=workspace.profile.creator;const nav=[['dashboard','dashboard','Genel Bakış'],['profile','person','Profil & Portföy Yönetimi'],['offers','handshake','İş Birliği Teklifleri'],['history','history','Geçmiş İş Birlikleri'],['shipments','local_shipping','Ürün & Kargo Takibi'],['reviews','reviews','Yorumlar & Değerlendirmeler'],['messages','forum','Mesajlar']] as const;return <div className="influencer-admin">{open&&<button className="ad-menu-backdrop" onClick={()=>setOpen(false)} aria-label="Menüyü kapat"/>}<aside className={`ad-sidebar ${open?'is-open':''}`}><Link className="ad-brand" href="/"><Image src="/marketing/alceix-logo.webp" width={72} height={27} alt="Alceix"/></Link><div className="ad-store-switch"><span className="ad-avatar">{c.initials}</span><div><strong>{c.name}</strong><small>İçerik üretici · {c.location}</small></div></div><nav aria-label="Influencer paneli">{nav.map(([key,icon,label])=>{const url=r[key](creatorId),active=key==='dashboard'?path===url:path.startsWith(url);return <Link key={key} href={url} className={active?'is-active':''} aria-current={active?'page':undefined} onClick={()=>setOpen(false)}><Icon name={icon}/>{label}</Link>;})}</nav><div className="ad-sidebar-bottom"><Icon name="verified_user"/><div><strong>Demo çalışma alanı</strong><small>İşlemler bu tarayıcıda saklanır</small></div></div></aside><div className="ad-workspace"><header className="ad-topbar"><div className="ad-topbar-left"><button className="ad-mobile-toggle" aria-label="Menü" aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name="menu"/></button><Image className="ad-top-logo" src="/marketing/alceix-logo.webp" width={62} height={24} alt="Alceix"/><span className={`ad-pill ${workspace.profile.isAvailable?'green':'blue'}`}>{workspace.profile.isAvailable?'İş birliklerine açık':'İş birliklerine kapalı'}</span><Link className="ad-preview" href={r.preview(creatorId)}><Icon name="visibility"/>Portföy Önizleme</Link></div><Link className="ad-account" href={r.profile(creatorId)} aria-label="Profilimi yönet"><span className="ad-account-name">{c.name}<small>İçerik üretici</small></span><span className="ad-avatar">{c.initials}</span></Link></header><main className="ad-main">{children}<footer className="ad-footer"><span>Alceix · Influencer çalışma alanı</span><span>Örnek veriler · Gerçek gönderim ve ödeme yapılmaz</span></footer></main></div>{notice&&<div className="ad-notice" role="status">{notice}<button onClick={()=>notify('')} aria-label="Bildirimi kapat"><Icon name="close"/></button></div>}</div>;}
