'use client';
import Image from 'next/image';
import {useEffect,useRef,useState} from 'react';
import {PanelHeading,PanelDialog,Icon} from '../components/panel-ui';
import {useSupplierWorkspace} from '../components/workspace-provider';
import {useSupplierTools} from '../hooks/use-supplier-tools';
import {studioImages} from '../mocks/tools';
export function SupplierStudio(){const {workspace,update,notify,ready}=useSupplierWorkspace();const {tools,updateTools,ready:toolsReady}=useSupplierTools();const [productId,setProductId]=useState(''),[mode,setMode]=useState('Manken Giydirme'),[gender,setGender]=useState('Kadın'),[scene,setScene]=useState('Minimalist Stüdyo'),[size,setSize]=useState('M'),[pose,setPose]=useState('Doğal Ayakta'),[ratio,setRatio]=useState('4:5'),[prompt,setPrompt]=useState('Doğal gün ışığı, yumuşak gölgeler ve ürünün dokusunu öne çıkaran sade bir çekim.'),[variant,setVariant]=useState(0),[activeId,setActiveId]=useState(''),[busy,setBusy]=useState(false),[before,setBefore]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const product=workspace.products.find(p=>p.id===productId)||workspace.products[0];const entry=tools.gallery.find(g=>g.id===activeId)||tools.gallery[0];const image=entry?.image||studioImages[variant];
 function produce(){if(!product||busy||!ready||!toolsReady)return;if(tools.credits<8||tools.gallery.length>96){notify('En az 8 demo kredi gerekir. Galeri en fazla 100 görsel tutar.');return;}setBusy(true);const source=product;timer.current=setTimeout(()=>{const id=crypto.randomUUID();updateTools(t=>({...t,credits:t.credits-8,gallery:[...studioImages.map((image,i)=>({id:`${id}-${i}`,productId:source.id,name:source.name,image,scene,mode})),...t.gallery]}));setActiveId(`${id}-0`);setVariant(0);setBusy(false);timer.current=null;notify('4 örnek varyasyon hazırlandı. Gerçek AI üretimi veya ücret tahsilatı yapılmadı.');},500);}
 function apply(){const target=entry?.productId||product?.id;if(!target||!workspace.products.some(p=>p.id===target)){notify('Ürün katalogda bulunamadı.');return;}update(w=>({...w,products:w.products.map(p=>p.id===target?{...p,image}:p)}));notify('Örnek görsel yerel B2B kataloğunun ana fotoğrafı yapıldı; mağazalara iletilmedi.');}
 async function download(){try{const r=await fetch(image);if(!r.ok)throw new Error();const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='alceix-tedarikci-ornek-gorsel.'+(blob.type.includes('png')?'png':'jpg');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{notify('Örnek görsel indirilemedi.');}}
 const choices=(label:string,values:string[],current:string,set:(value:string)=>void)=><fieldset className="sp-options"><legend>{label}</legend><div>{values.map(v=><button type="button" key={v} aria-pressed={current===v} onClick={()=>set(v)}>{v}</button>)}</div></fieldset>;
 return <><PanelHeading title="AI Sanal Manken & Ürün Görsel Stüdyosu" description="Tedarik kataloğunuzun ürün görsellerini hazırlayın. Bu ekran örnek görsellerle çalışan bir stüdyo demosudur." actions={<><PanelDialog title="Demo Kredi Yönetimi" trigger={`${tools.credits} Demo Kredi`}>{close=><><p>4 örnek varyasyon: 8 demo kredi. Ücretli satın alma yapılmaz.</p><button className="ad-button" disabled={!toolsReady||tools.credits>9900} onClick={()=>{updateTools(t=>({...t,credits:t.credits+100}));close();}}>100 Demo Kredi Ekle</button></>}</PanelDialog><PanelDialog title="Görsel Galerisi" trigger={`Galeri (${tools.gallery.length})`}>{close=><div className="sp-gallery">{tools.gallery.map(g=><button key={g.id} onClick={()=>{setActiveId(g.id);close();}}><Image src={g.image} alt={g.name} width={140} height={180}/><small>{g.name}</small></button>)}{!tools.gallery.length&&<p>İlk örnek varyasyonunuzu hazırlayın.</p>}</div>}</PanelDialog></>}/>
 <div className="sp-studio"><div className="sp-stack"><div className="sa-tabs">{['Manken Giydirme','Sahne & Işık','Netleştirme'].map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div><section className="ad-card sa-content-card"><h2>Kaynak Ürün Görseli</h2><label className="sp-search">Katalogdan Seç<select value={product?.id||''} onChange={e=>{setProductId(e.target.value);setBefore(false);}}>{workspace.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label>{product&&<div className="sa-product-cell sp-soft"><Image src={product.image} alt={product.name} width={58} height={70}/><div><b>{product.name}</b><small>{product.stock} adet · B2B katalog</small></div></div>}</section><section className="ad-card sa-content-card"><h2>Sanal Manken & Tipoloji</h2>{choices('Manken Cinsiyeti',['Kadın','Erkek','Unisex'],gender,setGender)}{choices('Beden Ölçüsü',['S','M','L','XL'],size,setSize)}{choices('Poz & Kamera Açısı',['Doğal Ayakta','Yürüyüş','Kumaş Detayı','Oturur Poz'],pose,setPose)}<p className="sa-note">Seçimler üretim talebi önizlemesine kaydedilir; demo fotoğrafları fiziksel olarak değiştirmez.</p></section><section className="ad-card sa-content-card"><h2>Sahne & Işık Atmosferi</h2><div className="sp-scenes">{['Minimalist Stüdyo','Doğal Gün Işığı','Katalog Saf Beyaz','Şehir Sokakları'].map((s,i)=><button key={s} aria-pressed={scene===s} onClick={()=>setScene(s)}><Image src={studioImages[i]} alt={s} width={170} height={100}/><span>{s}</span></button>)}</div><label className="sp-search">Detaylı Ortam İpucu<textarea rows={3} value={prompt} maxLength={1000} onChange={e=>setPrompt(e.target.value)}/></label><label className="sp-search">En / Boy Oranı<select value={ratio} onChange={e=>setRatio(e.target.value)}><option>4:5</option><option>1:1</option><option>9:16</option></select></label></section><button className="ad-button" disabled={busy||!ready||!toolsReady||!product} onClick={produce}><Icon name="auto_awesome"/>{busy?'Örnek Varyasyonlar Hazırlanıyor…':'4 Demo Varyasyonu Hazırla · 8 Kredi'}</button><p className="sa-note">Gerçek AI servisi, 4K render ve kredi tahsilatı henüz bağlı değildir.</p></div>
 <section className="ad-card sa-content-card"><div className="sp-chat-heading"><h2>Son Üretim Sonucu <span className="ad-pill blue">Demo</span></h2><button className="ad-button light" onClick={()=>setBefore(!before)}>Öncesi / Sonrası</button></div><div className="sp-result"><Image src={before?(product?.image||image):image} alt={before?'Kaynak ürün':'Temsili stüdyo sonucu'} width={600} height={760} priority/><span className="ad-pill blue">{before?'Kaynak Görsel':'Örnek Görsel · Gerçek AI üretimi değil'}</span></div><div className="sa-actions"><PanelDialog title="Görsel Önizleme" trigger="Büyüt">{()=> <Image className="sp-zoom" src={image} alt="Örnek sonuç" width={600} height={760}/>}</PanelDialog><button className="ad-button light" onClick={download}>Görseli İndir</button><button className="ad-button" disabled={!ready} onClick={apply}>B2B Kataloğuna Aktar</button></div><h3>Tüm Varyasyonlar</h3><div className="sp-variants">{studioImages.map((src,i)=><button key={src} aria-pressed={variant===i} onClick={()=>{setVariant(i);const group=entry?.id.slice(0,-2);const found=tools.gallery.find(g=>g.id===`${group}-${i}`);setActiveId(found?.id||'');}}><Image src={src} alt={`Örnek varyasyon ${i+1}`} width={140} height={170}/><small>{['Stüdyo','Katalog','Koleksiyon','Ürün'][i]}</small></button>)}</div><p className="sa-note">{entry?.name||product?.name} · {scene} · {mode} · {gender} / {size} / {pose} · {ratio}</p></section></div><section className="sp-gap"><h2>Daha Önce Hazırlananlar</h2><div className="sp-gallery">{tools.gallery.slice(0,8).map(g=><button key={g.id} onClick={()=>setActiveId(g.id)}><Image src={g.image} alt={g.name} width={150} height={190}/><small>{g.name}</small></button>)}</div>{!tools.gallery.length&&<p>Henüz üretim kaydı yok.</p>}</section></>;
}
