'use client';
import Image from 'next/image';
import {ProductEditor,type AdminProduct} from '@/modules/admin-editors';
import {useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {useSupplierWorkspace} from '../components/workspace-provider';
import {PanelHeading,downloadCsv,Icon} from '../components/panel-ui';
import {money} from '../utils/workspace';
import {csvCell} from '../utils/tools';
import type {WholesaleProduct} from '../types/supplier-admin';
export function SupplierProducts(){const {company,workspace,update,notify,ready}=useSupplierWorkspace();const params=useSearchParams();const q=params.get('q')||'';const tab=['active','critical','draft'].includes(params.get('filter')||'')?params.get('filter'):'all';const category=params.get('category')||'all';const sort=params.get('sort')==='price'?'price':'recent';const rawPage=Number(params.get('page')||1);const [editing,setEditing]=useState<WholesaleProduct|null>(null),[editorVersion,setEditorVersion]=useState(0),[minimum,setMinimum]=useState(1);const dialog=useRef<HTMLDialogElement>(null);
 function param(k:string,v:string){const u=new URL(window.location.href);if(v&&v!=='all')u.searchParams.set(k,v);else u.searchParams.delete(k);if(k!=='page')u.searchParams.delete('page');window.history.replaceState(null,'',u.pathname+u.search);}
 const filtered=workspace.products.filter(p=>(p.name+' '+p.sku).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))&&(category==='all'||category===p.category)&&(tab==='all'||tab==='active'&&p.active||tab==='draft'&&!p.active||tab==='critical'&&p.stock<5));const sorted=sort==='price'?[...filtered].sort((a,b)=>a.costCents-b.costCents):filtered;const pageCount=Math.max(1,Math.ceil(sorted.length/6)),page=Math.min(pageCount,Number.isSafeInteger(rawPage)&&rawPage>0?rawPage:1);const shown=sorted.slice((page-1)*6,page*6);
 function edit(p:WholesaleProduct|null){setEditing(p);setMinimum(p?.minimum||1);setEditorVersion(v=>v+1);}
 function toEditor(p:WholesaleProduct):AdminProduct{return {...p.details,id:p.id,name:p.name,category:p.category,sku:p.sku,barcode:p.details?.barcode||'',priceCents:p.costCents,costCents:p.details?.costCents||0,stock:p.stock,variants:p.details?.variants||['Standart'],images:[p.image,...(p.details?.images||[]).filter(image=>image!==p.image)],status:p.active?'live':'draft',model:'own',seoTitle:p.details?.seoTitle||p.name,seoDescription:p.details?.seoDescription||'',createdAt:'2026-10-01T00:00:00Z',description:p.details?.description||'Üretici firmadan Alceix mağazalarına B2B tedarik.'};}
 function save(product:AdminProduct):string|undefined {
 if(!Number.isSafeInteger(minimum)||minimum<1||minimum>1000000)return 'Minimum sipariş adedi 1–1.000.000 arasında tam sayı olmalı.';
 if(product.status==='live'&&product.priceCents<=0||product.priceCents>100000000||product.stock>1000000||!product.images.length)return 'Tedarik fiyatını, görseli ve stok limitini kontrol edin.';
 if(workspace.products.some(p=>p.id!==product.id&&p.sku.toLocaleLowerCase('tr')===product.sku.toLocaleLowerCase('tr')))return 'Bu SKU başka bir üründe kullanılıyor.';
 if(!editing&&workspace.products.length>=100)return 'Demo katalog limiti 100 ürün.';
 const record:WholesaleProduct={id:product.id,name:product.name,sku:product.sku,category:product.category,image:product.images[0],costCents:product.priceCents,stock:product.stock,minimum,active:product.status==='live',details:product};
 const next={...workspace,products:editing?workspace.products.map(p=>p.id===editing.id?record:p):[record,...workspace.products]};
 try{localStorage.setItem(`alceix:supplier:${company.id}:workspace:v1`,JSON.stringify(next));}catch{return 'Tarayıcı depolaması yetersiz. Daha küçük görsellerle yeniden deneyin; ürün kaydedilmedi.';}
 update(()=>next);notify('Ürün yerel B2B kataloğuna kaydedildi.');return;
 }
 const exportProducts=()=>downloadCsv('alceix-b2b-katalog.csv',[['Ürün','SKU','Tedarik Fiyatı (TL)','Stok','Minimum Adet','Yayın'],...filtered.map(p=>[p.name,p.sku,p.costCents/100,p.stock,p.minimum,p.active?'Yayında':'Taslak'])].map(r=>r.map(csvCell).join(';')).join('\n'));
 return <><PanelHeading title="Ürünler & B2B Tedarik Kataloğu" description="Tedarik fiyatlarınızı, minimum sipariş adetlerini ve stokları tek yerden yönetin." actions={<><button className="ad-button light" onClick={exportProducts}><Icon name="download"/>Filtrele & Dışa Aktar</button><button className="ad-button" disabled={!ready} onClick={()=>edit(null)}>+ Yeni Ürün Ekle</button></>}/><div className="ad-card sa-content-card sa-tabs sp-gap">{[['all','Tüm Ürünler',workspace.products.length],['active','Yayında (B2B)',workspace.products.filter(p=>p.active).length],['critical','Kritik Stok',workspace.products.filter(p=>p.stock<5).length],['draft','Taslaklar',workspace.products.filter(p=>!p.active).length]].map(([value,label,count])=><button key={value} aria-pressed={tab===value} onClick={()=>param('filter',String(value))}>{label} <span className="ad-pill blue">{count}</span></button>)}</div><div className="sa-toolbar"><input aria-label="Ürün ara" placeholder="Ürün adı, SKU veya stok kodu ara…" value={q} onChange={e=>param('q',e.target.value.slice(0,120))}/><select aria-label="Kategori" value={category} onChange={e=>param('category',e.target.value)}><option value="all">Tüm Kategoriler</option>{[...new Set(workspace.products.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Ürün sıralaması" value={sort} onChange={e=>param('sort',e.target.value)}><option value="recent">Katalog Sırası</option><option value="price">Fiyat: Artan</option></select></div>
 <div className="sp-products-table sa-table-scroll"><table><thead><tr><th>Ürün Detayı</th><th>Tedarik Fiyatı (Birim)</th><th>Stok / Minimum</th><th>B2B Yayın</th><th>İşlemler</th></tr></thead><tbody>{shown.map(p=><tr key={p.id}><td><div className="sa-product-cell"><Image src={p.image} alt={p.name} width={60} height={70} unoptimized={p.image.startsWith("data:")}/><div><b>{p.name}</b><small><span className="ad-pill blue">{p.category}</span> · SKU: {p.sku}</small></div></div></td><td><strong>{money(p.costCents)}</strong><small>Alceix mağazasının alış fiyatı</small></td><td><span className={`ad-pill ${p.stock<5?'red':'green'}`}>{p.stock} adet</span><small>Minimum sipariş: {p.minimum}</small>{p.stock<5&&<button className="sa-text-button" onClick={()=>{update(w=>({...w,products:w.products.map(i=>i.id===p.id?{...i,stock:Math.min(1000000,i.stock+10)}:i)}));notify('Yerel demo stoğuna 10 adet eklendi.');}}>+10 Stok Ekle</button>}</td><td><button className="sp-toggle" role="switch" aria-checked={p.active} aria-label={`${p.name} B2B yayını`} onClick={()=>{if(!p.active&&p.costCents<=0){edit(p);return;}update(w=>({...w,products:w.products.map(i=>i.id===p.id?{...i,active:!i.active}:i)}));}}><i/>{p.active?'Yayında':'Taslak'}</button></td><td><button className="ad-button light" aria-label={`${p.name} düzenle`} onClick={()=>edit(p)}><Icon name="edit"/>Düzenle</button></td></tr>)}</tbody></table>{!shown.length&&<p className="sa-empty">Bu filtrede ürün bulunamadı.</p>}</div><div className="sp-chat-heading sp-gap"><p>{filtered.length} ürün · Sayfa {page} / {pageCount}</p><div className="sa-actions"><button className="ad-button light" disabled={page===1} onClick={()=>param('page',String(page-1))}>Önceki</button><span className="ad-pill blue">{page}</span><button className="ad-button light" disabled={page===pageCount} onClick={()=>param('page',String(page+1))}>Sonraki</button></div></div><p className="sa-note">Yayın ve stok değişiklikleri yerel demo kataloğunda saklanır. Alıcılar yalnızca bağlı Alceix mağazalarıdır.</p>
 {editorVersion>0&&<ProductEditor key={editorVersion} dialogRef={dialog} initial={editing?toEditor(editing):undefined} categories={[...new Set(['Triko','Basic','Aksesuar',...workspace.products.map(p=>p.category)])]} b2b minimum={minimum} onMinimumChange={setMinimum} onSave={save}/>}</>;
}
