'use client';
import Link from 'next/link';
import {supplierRoutes} from '@/config/supplier-routes';
import {useState} from 'react';
import Image from 'next/image';
import {useSearchParams} from 'next/navigation';
import {useSupplierWorkspace} from '../components/workspace-provider';
import {PanelHeading,Stats,PanelDialog,downloadCsv} from '../components/panel-ui';
import {useSupplierTools} from '../hooks/use-supplier-tools';
import {carriers} from '../mocks/tools';
import {createWholesaleOrder,money} from '../utils/workspace';
import {csvCell} from '../utils/tools';
export function SupplierOrders(){const {company,workspace,update,notify,ready}=useSupplierWorkspace();const {tools,updateTools,ready:toolsReady}=useSupplierTools();const params=useSearchParams();const q=params.get('q')||'';const filter=['preparing','shipped','delivered','cancelled'].includes(params.get('status')||'')?params.get('status'):'all';const [selected,setSelected]=useState<string[]>([]);const [error,setError]=useState('');
 const counts=(status:string)=>workspace.orders.filter(o=>o.status===status).length;const orders=workspace.orders.filter(o=>(o.id+' '+o.tracking+' '+workspace.stores.find(s=>s.id===o.buyerStoreId)?.name).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))&&(filter==='all'||o.status===filter));
 function param(k:string,v:string){const u=new URL(window.location.href);if(v&&v!=='all')u.searchParams.set(k,v);else u.searchParams.delete(k);window.history.replaceState(null,'',u.pathname+u.search);}
 function exportOrders(){const ids=workspace.orders.filter(o=>selected.includes(o.id));if(!ids.length){notify('Önce listeden sipariş seçin.');return;}downloadCsv('alceix-b2b-paketleme.csv',[['Sipariş','Alıcı Mağaza','Ürün','Adet','Takip'],...ids.map(o=>[o.id,workspace.stores.find(s=>s.id===o.buyerStoreId)?.name||'',workspace.products.find(p=>p.id===o.productId)?.name||'',o.quantity,o.tracking])].map(r=>r.map(csvCell).join(';')).join('\n'));}
 return <><PanelHeading title="B2B Sipariş & Kargo Yönetimi" description="Bağlı Alceix mağazalarının siparişlerini hazırlayın, kargo ve teslimat süreçlerini takip edin." actions={<><button className="ad-button light" onClick={exportOrders}>Toplu Paketleme Listesi · CSV</button><PanelDialog title="Alceix Mağazasına Sipariş Oluştur" trigger="+ B2B Sipariş Oluştur">{close=><form className="sa-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(workspace.orders.length>=1000)throw new Error('Demo sipariş limiti doldu.');const order=createWholesaleOrder(workspace,String(f.get('buyer')),String(f.get('product')),Number(f.get('quantity')),`B2B-${crypto.randomUUID().slice(0,8)}`);update(w=>({...w,orders:[order,...w.orders],products:w.products.map(p=>p.id===order.productId?{...p,stock:p.stock-order.quantity}:p)}));setError('');close();notify('Demo B2B siparişi kaydedildi; gerçek mağazaya iletilmedi.');}catch(c){setError(c instanceof Error?c.message:'Sipariş oluşturulamadı.');}}}><label>Alıcı Mağaza<select name="buyer">{workspace.stores.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ürün<select name="product">{workspace.products.filter(p=>p.active&&p.stock>=p.minimum).map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.costCents)} · Min. {p.minimum}</option>)}</select></label><label>Adet<input name="quantity" type="number" min="1" defaultValue={1} required/></label>{error&&<p role="alert" className="sa-error">{error}</p>}<button className="ad-button" disabled={!ready}>Demo Siparişi Kaydet</button></form>}</PanelDialog></>}/>
 <Stats items={[{label:'Kargoya Hazırlanacak',value:String(counts('preparing')),note:'Paketlenmeyi bekleyen B2B siparişler',icon:'inventory'},{label:'Yoldaki Gönderiler',value:String(counts('shipped')),note:'Örnek kargo takip akışı',icon:'local_shipping'},{label:'Tamamlanan Siparişler',value:String(counts('delivered')),note:'Yerel teslimat kayıtları',icon:'verified'},{label:'Bağlı Mağazalar',value:String(workspace.stores.filter(s=>s.active).length),note:'Alıcılar yalnızca aktif Alceix mağazaları',icon:'store'}]}/>
 <section className="ad-card sa-content-card sp-gap"><h2>Kargo Bağlantıları <span className="ad-pill green">Demo tercih</span></h2><p>Taşıyıcınızı seçin. Gerçek etiket üretimi ve taşıyıcı API bağlantısı henüz yok.</p><div className="sp-carriers">{carriers.map(c=><button key={c} aria-pressed={tools.carrier===c} disabled={!toolsReady} onClick={()=>updateTools(t=>({...t,carrier:c}))}>{c}<small>{tools.carrier===c?'Seçili taşıyıcı':'Entegrasyon bekliyor'}</small></button>)}</div></section>
 <section className="ad-card sa-content-card"><div className="sa-tabs sp-gap">{[['all','Tüm Siparişler'],['preparing','Hazırlanıyor'],['shipped','Kargoda / Yolda'],['delivered','Teslim Edildi'],['cancelled','İptal Edildi']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>param('status',value)}>{label} · {value==='all'?workspace.orders.length:counts(value)}</button>)}</div><div className="sa-toolbar"><input aria-label="Sipariş ara" value={q} placeholder="Sipariş no, takip kodu veya Alceix mağazası…" onChange={e=>param('q',e.target.value.slice(0,120))}/><button className="ad-button light" onClick={()=>{param('q','');param('status','all');}}>Filtreleri Temizle</button></div><div className="sa-table-scroll"><table><thead><tr><th>Seç</th><th>Sipariş</th><th>Alıcı Mağaza</th><th>Ürün</th><th>Tutar</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{orders.map(o=>{const p=workspace.products.find(p=>p.id===o.productId);return <tr key={o.id}><td><input type="checkbox" aria-label={`${o.id} siparişini seç`} checked={selected.includes(o.id)} onChange={e=>setSelected(e.target.checked?[...selected,o.id]:selected.filter(id=>id!==o.id))}/></td><td><b>#{o.id}</b><small>{o.tracking||'Takip bekleniyor'}</small></td><td>{workspace.stores.find(s=>s.id===o.buyerStoreId)?.name}</td><td><div className="sa-product-cell">{p&&<Image src={p.image} alt={p.name} width={42} height={52}/>}<div>{p?.name}<small>{o.quantity} adet</small></div></div></td><td><b>{money(o.quantity*o.unitCostCents)}</b></td><td><span className={`ad-pill ${o.status==='delivered'?'green':'blue'}`}>{o.status==='preparing'?'Paket Hazırlanıyor':o.status==='shipped'?'Kargoda':o.status==='cancelled'?'İptal Edildi':'Teslim Edildi'}</span></td><td><Link className="ad-button light" href={supplierRoutes.order(company.slug,o.id)}>Detay & Kargo →</Link></td></tr>;})}</tbody></table>{!orders.length&&<p className="sa-empty">Sipariş bulunamadı.</p>}</div><p>{selected.length} sipariş seçili</p></section></>;
}
