'use client';
import {useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {supplierRoutes} from '@/config/supplier-routes';
import {useSupplierWorkspace} from '../components/workspace-provider';
import {useSupplierTools} from '../hooks/use-supplier-tools';
import {PanelDialog,Icon,downloadCsv} from '../components/panel-ui';
import {money,cancelWholesaleOrder} from '../utils/workspace';
import {csvCell} from '../utils/tools';
import '@/modules/admin-editors/orders.css';
export function SupplierOrderDetail({orderId}:{orderId:string}) {
 const {company,workspace,update,notify,ready}=useSupplierWorkspace();const {tools}=useSupplierTools();
 const [error,setError]=useState('');const order=workspace.orders.find(o=>o.id===orderId);
 if(!ready)return <p role="status">Sipariş hazırlanıyor…</p>;if(!order)notFound();
 const product=workspace.products.find(p=>p.id===order.productId)!;const buyer=workspace.stores.find(s=>s.id===order.buyerStoreId)!;
 const status=order.status==='preparing'?'Paketleniyor':order.status==='shipped'?'Kargoda':order.status==='cancelled'?'İptal Edildi':'Teslim Edildi';const total=order.unitCostCents*order.quantity;
 const patch=(change:Partial<typeof order>)=>update(w=>({...w,orders:w.orders.map(o=>o.id===orderId?{...o,...change}:o)}));
 const exportSummary=()=>downloadCsv(`${order.id}-siparis-ozeti.csv`,[['Sipariş','Mağaza','Ürün','Adet','Birim Tedarik Fiyatı','Toplam','Durum','Takip'],[order.id,buyer.name,product.name,order.quantity,order.unitCostCents/100,total/100,status,order.tracking]].map(row=>row.map(csvCell).join(';')).join('\n'));
 return <><header className="ao-detail-heading"><div><div><Link href={supplierRoutes.orders(company.slug)}><Icon name="arrow_back"/>Siparişler</Link><span>/</span><h1>Sipariş #{order.id}</h1><span className="ad-pill blue">{status}</span></div><p>Alceix B2B · {buyer.name} · {order.quantity} adet</p></div><div><button className="ad-button light" onClick={exportSummary}>Sipariş Özeti · CSV</button>{order.status==='shipped'&&<PanelDialog title="Teslimatı Onayla" trigger="Demo Teslimatı Onayla">{close=><><p>Bu işlem yalnızca örnek siparişin durumunu günceller.</p><button className="ad-button" onClick={()=>{patch({status:'delivered'});close();notify('Demo teslimat onaylandı.');}}>Teslim Edildi Olarak Kaydet</button></>}</PanelDialog>}</div></header>
 <div className="ao-detail-layout"><div className="ao-detail-main"><section className="ad-card ao-detail-card"><div className="ao-section-title"><h2><Icon name="shopping_bag"/>Sipariş Edilen Ürünler</h2><small>1 kalem / {order.quantity} adet</small></div><div className="ao-detail-product"><Image src={product.image} alt={product.name} width={60} height={70} unoptimized={product.image.startsWith('data:')}/><div><strong>{product.name}</strong><p>SKU: {product.sku}</p><small>{money(order.unitCostCents)} × {order.quantity} adet</small></div><b>{money(total)}</b></div></section>
 <section className="ad-card ao-detail-card"><div className="ao-section-title"><h2><Icon name="local_shipping"/>Kargo & Gönderim</h2><span className="ad-pill blue">{tools.carrier}</span></div><div className="ao-shipment-box"><div><small>TAKİP NUMARASI</small><strong>{order.tracking||'Henüz oluşturulmadı'}</strong><p>Alceix B2B · Demo gönderi</p></div><PanelDialog title="Kargo Takibi & Etiket Önizlemesi" trigger="Gönderi Takibini Aç">{close=><><p>{tools.carrier} · {order.tracking||'Takip bekleniyor'}</p><p className="sa-note">Gerçek etiket, taşıyıcı kaydı veya teslimat kanıtı oluşturulmaz.</p>{order.status==='preparing'?<form className="sa-form" onSubmit={e=>{e.preventDefault();const tracking=String(new FormData(e.currentTarget).get('tracking')).trim();if(tracking.length<4){setError('En az 4 karakterli takip numarası girin.');return;}patch({tracking,status:'shipped'});setError('');close();notify('Demo gönderi kaydedildi.');}}><label>Örnek Takip Numarası<input name="tracking" maxLength={80} required/></label>{error&&<p role="alert" className="sa-error">{error}</p>}<button className="ad-button">Gönderiyi Kaydet</button></form>:<button className="ad-button light" onClick={exportSummary}>Örnek Gönderi Özeti İndir</button>}</>}</PanelDialog></div>
 {order.status!=='cancelled'&&<><ol className="ao-horizontal-timeline">{['Sipariş Alındı','Paketleniyor','Kargoya Verildi','Teslim Edildi'].map((label,i)=><li key={label} className={i<=(order.status==='delivered'?3:order.status==='shipped'?2:1)?'is-done':''}>{label}</li>)}</ol><div className="ao-shipment-progress" role="progressbar" aria-label="Sipariş ilerlemesi" aria-valuemin={0} aria-valuemax={100} aria-valuenow={order.status==='delivered'?100:order.status==='shipped'?75:50}><span style={{width:order.status==='delivered'?'100%':order.status==='shipped'?'75%':'50%'}}/></div></>}</section>
 <section className="ad-card ao-detail-card"><div className="ao-section-title"><h2><Icon name="payments"/>Tedarik & Fatura Özeti</h2><button className="ao-text-button" onClick={exportSummary}>Özet İndir</button></div><dl className="ao-payment-summary"><div><dt>Birim Tedarik Fiyatı</dt><dd>{money(order.unitCostCents)}</dd></div><div><dt>Adet</dt><dd>{order.quantity}</dd></div><div className="ao-total"><dt>Genel Toplam</dt><dd>{money(total)}</dd></div></dl><div className="ao-payment-note">Sipariş anındaki fiyat korunur. Gerçek ödeme, vergi, kargo bedeli veya fatura kesilmedi.</div></section></div>
 <aside className="ao-detail-aside"><section className="ad-card ao-detail-card"><div className="ao-section-title"><h2><Icon name="storefront"/>Alıcı Mağaza</h2><span className="ad-pill green">Alceix B2B</span></div><Link className="ao-customer-button" href={supplierRoutes.stores(company.slug)}><span className="ao-customer-avatar">{buyer.name.slice(0,2).toUpperCase()}</span><span><strong>{buyer.name}</strong><small>{buyer.city}</small></span><Icon name="open_in_new"/></Link><Link className="ao-text-button" href={`${supplierRoutes.messages(company.slug)}?${new URLSearchParams({store:buyer.id})}`}>Mağazaya Mesaj Yaz →</Link></section>
 <section className="ad-card ao-detail-card"><div className="ao-section-title"><h2><Icon name="location_on"/>Teslimat & Adres</h2><PanelDialog title="Teslimat Adresini Düzenle" trigger="Düzenle">{close=><form className="sa-form" onSubmit={e=>{e.preventDefault();const address=String(new FormData(e.currentTarget).get('address')).trim();if(order.status!=='preparing'){setError('Gönderi başladıktan sonra adres değiştirilemez.');return;}if(address.length<10){setError('En az 10 karakterli örnek adres girin.');return;}patch({address});setError('');close();notify('Demo teslimat adresi kaydedildi.');}}><label>Örnek Teslimat Adresi<textarea name="address" defaultValue={order.address||`Örnek Mahallesi, Demo Sokak No:42 · ${buyer.city}`} maxLength={500} required/></label>{error&&<p role="alert" className="sa-error">{error}</p>}<button className="ad-button" disabled={order.status!=='preparing'}>Adresi Kaydet</button></form>}</PanelDialog></div><div className="ao-address">{order.address||`Örnek Mahallesi, Demo Sokak No:42 · ${buyer.city}`}<strong>{buyer.city} / Türkiye</strong></div><small className="ao-address-label">FATURA BİLGİLERİ</small><div className="ao-address">Alceix mağazası · B2B alıcı<p>Gerçek vergi veya kimlik bilgisi tutulmaz.</p></div></section>
 <section className="ad-card ao-detail-card"><div className="ao-section-title"><h2><Icon name="chat"/>Mağaza & Paketleme Notu</h2></div><blockquote>Alceix mağazasına yönelik örnek B2B sipariş.</blockquote><form key={order.id} onSubmit={e=>{e.preventDefault();patch({internalNote:String(new FormData(e.currentTarget).get('note')).trim()});notify('Paketleme notu kaydedildi.');}}><label htmlFor="supplier-order-note">Dahili Firma Notu</label><textarea id="supplier-order-note" name="note" defaultValue={order.internalNote||''} maxLength={500} placeholder="Paketleme ekibi için not…"/><button className="ao-secondary">Notu Kaydet</button></form></section>
 <section className="ad-card ao-detail-card ao-danger-zone"><h2>Sipariş İşlemleri</h2><p>Yalnızca hazırlanan siparişler iptal edilebilir; adet stoğa geri eklenir.</p>{order.status==='preparing'?<PanelDialog title="Siparişi İptal Et" trigger="Siparişi İptal Et">{close=><><p>#{order.id} iptal edilecek ve {order.quantity} adet ürün stoğa iade edilecek.</p><button className="ad-button" onClick={()=>{try{const next=cancelWholesaleOrder(workspace,order.id);update(()=>next);close();notify('Demo sipariş iptal edildi; stok iade edildi.');}catch{setError('Sipariş iptal edilemedi.');}}}>İptali Onayla</button>{error&&<p role="alert">{error}</p>}</>}</PanelDialog>:<p className="sa-note">Bu siparişin mevcut durumunda iptal kullanılamaz.</p>}</section></aside></div></>;
}
