'use client';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {useSupplierWorkspace} from '../components/workspace-provider';
import {PanelHeading,Stats,PanelDialog,downloadCsv,Icon} from '../components/panel-ui';
import {useSupplierTools} from '../hooks/use-supplier-tools';
import {money} from '../utils/workspace';
import {csvCell} from '../utils/tools';
export function SupplierFinance(){const {workspace,update,notify,ready}=useSupplierWorkspace();const {tools,updateTools,ready:toolsReady}=useSupplierTools();const params=useSearchParams();const query=params.get('q')||'';const filter=params.get('filter')==='delivered'?'delivered':'all';const [error,setError]=useState('');const [amount,setAmount]=useState(1000);
 const total=workspace.orders.filter(o=>o.status!=='cancelled').reduce((s,o)=>s+o.quantity*o.unitCostCents,0),delivered=workspace.orders.filter(o=>o.status==='delivered').reduce((s,o)=>s+o.quantity*o.unitCostCents,0);
 const orders=workspace.orders.filter(o=>o.status!=='cancelled'&&(o.id+' '+workspace.stores.find(s=>s.id===o.buyerStoreId)?.name).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))&&(filter==='all'||o.status==='delivered'));
 function param(k:string,v:string){const url=new URL(window.location.href);if(v&&v!=='all')url.searchParams.set(k,v);else url.searchParams.delete(k);window.history.replaceState(null,'',url.pathname+url.search);}
 function statement(){downloadCsv('alceix-tedarikci-ekstre.csv',[['Sipariş','Alceix mağazası','Tedarik tutarı (TL)','Durum'],...orders.map(o=>[o.id,workspace.stores.find(s=>s.id===o.buyerStoreId)?.name||'',o.quantity*o.unitCostCents/100,o.status])].map(row=>row.map(csvCell).join(';')).join('\n'));}
 return <><PanelHeading title="Cüzdan & Finans Yönetimi" description="Alceix mağazalarına yaptığınız satışlar, hakediş özeti ve banka bilgileriniz." actions={<><button className="ad-button light" onClick={statement}><Icon name="download"/>Ekstre İndir · CSV</button><PanelDialog title="Hakediş Talebi Önizlemesi" trigger="Hakediş Talebi Hazırla">{close=><><p>Teslim edilen örnek satış: <b>{money(delivered)}</b></p><p className="sa-note">Gerçek ödeme ve banka transferi bağlı değil. Bu işlem yalnızca önizleme oluşturur.</p><button className="ad-button" onClick={()=>{notify('Hakediş talebi önizlemesi hazırlandı; para aktarılmadı.');close();}}>Önizlemeyi Hazırla</button></>}</PanelDialog></>}/>
 <Stats items={[{label:'Teslim edilen satış',value:money(delivered),note:'Örnek hakediş · Banka bakiyesi değildir',icon:'account_balance_wallet'},{label:'Bekleyen satış',value:money(total-delivered),note:'Hazırlanan ve kargodaki siparişler',icon:'local_shipping'},{label:'Toplam B2B satış',value:money(total),note:'Bağlı mağazaların demo siparişleri',icon:'trending_up'},{label:'Ödeme altyapısı',value:'Demo',note:'Canlı finans bağlantısı bekleniyor',icon:'verified_user'}]}/>
 <div className="sp-with-aside"><section className="ad-card sa-content-card"><h2>Hakediş & İşlem Geçmişi</h2><div className="sa-toolbar"><input aria-label="İşlem ara" placeholder="Sipariş veya mağaza ara…" value={query} onChange={e=>param('q',e.target.value.slice(0,120))}/><select aria-label="Hakediş filtresi" value={filter} onChange={e=>param('filter',e.target.value)}><option value="all">Tüm İşlemler</option><option value="delivered">Teslim Edilenler</option></select></div><div className="sa-table-scroll"><table><thead><tr><th>Sipariş / Mağaza</th><th>Brüt Tedarik Tutarı</th><th>Durum</th><th>Hakediş</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>#{o.id}</b><small>{workspace.stores.find(s=>s.id===o.buyerStoreId)?.name}</small></td><td><b>{money(o.quantity*o.unitCostCents)}</b></td><td><span className={`ad-pill ${o.status==='delivered'?'green':'blue'}`}>{o.status==='delivered'?'Teslim edildi':o.status==='shipped'?'Kargoda':'Hazırlanıyor'}</span></td><td>{o.status==='delivered'?'Örnek tutar':'Teslimat bekliyor'}</td></tr>)}</tbody></table>{!orders.length&&<p className="sa-empty">İşlem bulunamadı.</p>}</div><p className="sa-note">Komisyon ve ödeme vadesi henüz belirlenmedi; tutarlar siparişin kayıt anındaki tedarik fiyatıdır.</p></section>
 <aside className="sp-stack"><section className="ad-card sa-content-card"><h2>Kayıtlı Banka Hesabı</h2><div className="sp-soft"><span className="ad-pill green">Örnek Hesap</span><h3>{workspace.companyName}</h3><small>IBAN NUMARASI</small><p>{workspace.iban?workspace.iban.slice(0,6)+' •••• •••• '+workspace.iban.slice(-4):'Henüz tanımlanmadı'}</p></div><label className="sp-check"><input type="checkbox" disabled={!toolsReady} checked={tools.automaticPayout} onChange={e=>updateTools(t=>({...t,automaticPayout:e.target.checked}))}/>Haftalık aktarım tercihi · Demo</label><PanelDialog title="Örnek Banka Hesabını Düzenle" trigger="IBAN Düzenle / Hesap Ekle">{close=><form className="sa-form" onSubmit={e=>{e.preventDefault();const iban=String(new FormData(e.currentTarget).get('iban')).replace(/\s/g,'').toUpperCase();if(!/^TR\d{24}$/.test(iban)){setError('TR ile başlayan 26 karakterli örnek IBAN girin.');return;}update(w=>({...w,iban}));setError('');notify('Örnek IBAN kaydedildi; banka doğrulaması yapılmadı.');close();}}><p className="sa-note">Yalnızca örnek veri kullanın.</p><label>Örnek IBAN<input name="iban" defaultValue={workspace.iban} maxLength={34} required/></label>{error&&<p role="alert" className="sa-error">{error}</p>}<button className="ad-button" disabled={!ready}>Hesabı Kaydet</button></form>}</PanelDialog></section><section className="ad-card sa-content-card"><h2>Kesinti Simülatörü</h2><p>Seçtiğiniz oranla örnek hesaplama yapın. Gerçek sözleşme tutarı değildir.</p><PanelDialog title="Örnek Komisyon Hesabı" trigger="Simülatörü Aç">{()=> <div className="sa-form"><label>Brüt Tutar (TL)<input type="number" min="0" max="1000000" value={amount} onChange={e=>setAmount(Math.max(0,Math.min(1000000,Number(e.target.value))))}/></label><p>Örnek %3 kesinti: <b>{money(Math.round(amount*3))}</b></p><p>Örnek net: <b>{money(Math.round(amount*97))}</b></p><p className="sa-note">%3 yalnızca simülasyon oranıdır.</p></div>}</PanelDialog></section><section className="ad-card sa-content-card"><h2>Maliye & Belgeler</h2><p>E-fatura entegrasyonu bekleniyor.</p><button className="ad-button light" onClick={statement}>Örnek İşlem Dökümü</button></section></aside></div></>;
}
