'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supplierRoutes} from '@/config/supplier-routes';
import {PanelHeading} from '../components/panel-ui';
import {useSupplierWorkspace} from '../components/workspace-provider';
import {internalMessageIssue} from '../utils/tools';
export function SupplierMessages(){const {company,workspace,update,notify,ready}=useSupplierWorkspace();const params=useSearchParams();const store=workspace.stores.find(s=>s.id===params.get('store'))||workspace.stores[0];const [text,setText]=useState(''),[q,setQ]=useState(''),[error,setError]=useState('');
 function select(id:string){const u=new URL(window.location.href);u.searchParams.set('store',id);window.history.replaceState(null,'',u.pathname+u.search);setText('');setError('');}
 return <><PanelHeading title="Mesajlar & Mağaza Görüşmeleri" description="Ürün, stok ve sipariş görüşmelerinizi bağlı Alceix mağazalarıyla aynı yerde sürdürün."/><section className="ad-card sp-conversations"><aside><label className="sp-search">Mağaza Ara<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Mağaza adı…"/></label><div className="sp-contact-list">{workspace.stores.filter(s=>s.name.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).map(s=><button key={s.id} aria-pressed={store?.id===s.id} onClick={()=>select(s.id)}><b>{s.name}</b><small>{s.city} · {s.active?'Bağlı mağaza':'Duraklatıldı'}</small></button>)}</div></aside><div className="sp-chat-panel">{store?<><div className="sp-chat-heading"><div><h2>{store.name}</h2><p>Alceix mağazası · {store.city}</p></div><Link className="ad-button light" href={supplierRoutes.stores(company.slug)}>Bağlantıyı İncele</Link></div><p className="sa-note">Görüşmeler Alceix içinde sürdürülür. Demo mesajları bu tarayıcıda saklanır; gerçek mağazaya gönderilmez.</p><div className="sa-messages" aria-live="polite">{workspace.messages.filter(m=>m.storeId===store.id).map(m=><article className={`sa-bubble ${m.author}`} key={m.id}><small>{m.author==='supplier'?workspace.companyName:store.name}</small><p>{m.text}</p></article>)}{!workspace.messages.some(m=>m.storeId===store.id)&&<p className="sa-empty">Henüz mesaj yok. İlk görüşmenizi başlatın.</p>}</div><form className="sa-form" onSubmit={e=>{e.preventDefault();const issue=internalMessageIssue(text);if(issue||!store.active||workspace.messages.length>=1000){setError(issue||'Görüşme için aktif mağaza bağlantısı gerekir veya kayıt limiti dolmuştur.');return;}update(w=>({...w,messages:[...w.messages,{id:crypto.randomUUID(),storeId:store.id,text:text.trim(),author:'supplier'}]}));setText('');setError('');notify('Mesaj yerel demo görüşmesine eklendi; dışarı gönderilmedi.');}}><label>Mesajınız<textarea rows={3} value={text} maxLength={2000} onChange={e=>setText(e.target.value)} placeholder="Ürün veya sipariş hakkında yazın…"/></label>{error&&<p className="sa-error" role="alert">{error}</p>}<button disabled={!ready||!store.active||!text.trim()} className="ad-button">Demo Görüşmesine Ekle →</button></form></>:<p className="sa-empty">Bağlı mağazanız bulunmuyor.</p>}</div></section></>;
}
