'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {routes} from '@/config/routes';
import {PanelHeading,Stats,PanelDialog} from '../components/panel-ui';
import {useSupplierTools} from '../hooks/use-supplier-tools';
import {useSupplierWorkspace} from '../components/workspace-provider';
export function SupplierSupport(){const {tools,updateTools,ready}=useSupplierTools();const {notify}=useSupplierWorkspace();const params=useSearchParams();const query=params.get('q')||'';const filter=params.get('status')==='closed'?'closed':params.get('status')==='open'?'open':'all';const ticket=tools.tickets.find(t=>t.id===params.get('ticket'))||tools.tickets[0];const [reply,setReply]=useState(''),[error,setError]=useState('');
 function param(k:string,v:string){const u=new URL(window.location.href);if(v&&v!=='all')u.searchParams.set(k,v);else u.searchParams.delete(k);window.history.replaceState(null,'',u.pathname+u.search);}
 const tickets=tools.tickets.filter(t=>(t.id+' '+t.subject).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))&&(filter==='all'||t.status===filter));
 return <><PanelHeading title="Destek Talepleri & Yardım Masası" description="Katalog, B2B sipariş, finans ve firma taleplerinizi tek merkezden yönetin." actions={<><Link className="ad-button light" href={routes.faq}>S.S.S. & Bilgi Bankası</Link><PanelDialog title="Yeni Destek Talebi" trigger="+ Yeni Destek Talebi">{close=><form className="sa-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const subject=String(f.get('subject')).trim(),message=String(f.get('message')).trim();if(subject.length<5||message.length<20||tools.tickets.length>=100){setError('En az 5 karakterli konu ve 20 karakterli açıklama yazın. Talep limiti 100.');return;}const id=`TD-${crypto.randomUUID().slice(0,8)}`;updateTools(t=>({...t,tickets:[{id,subject,category:String(f.get('category')),priority:f.get('priority')==='high'?'high':'normal',status:'open',messages:[{id:crypto.randomUUID(),author:'supplier',text:message}]},...t.tickets]}));param('ticket',id);setError('');close();notify('Destek talebi yerel demo alanına eklendi; ekibe iletilmedi.');}}><label>Konu<input name="subject" maxLength={120} required/></label><label>Kategori<select name="category"><option>Stok & API</option><option>B2B Sipariş & Kargo</option><option>Cüzdan & Finans</option><option>Ekip & Hesap</option></select></label><label>Öncelik<select name="priority"><option value="normal">Normal</option><option value="high">Yüksek</option></select></label><label>Açıklama<textarea name="message" maxLength={2000} rows={4} required/></label>{error&&<p role="alert" className="sa-error">{error}</p>}<button className="ad-button" disabled={!ready}>Demo Talebi Kaydet</button></form>}</PanelDialog></>}/>
 <Stats items={[{label:'Açık Talepler',value:`${tools.tickets.filter(t=>t.status==='open').length} Aktif Talep`,note:'Yerel destek kayıtları',icon:'inbox'},{label:'Yanıt Süresi',value:'Demo Ortamı',note:'Gerçek SLA veya süre ölçümü yok',icon:'timer'},{label:'Çözülen Talepler',value:`${tools.tickets.filter(t=>t.status==='closed').length} Çözüldü`,note:'Kapatılmış örnek talepler',icon:'verified'},{label:'Canlı Destek',value:'Bağlantı Bekliyor',note:'Destek servisi henüz bağlı değil',icon:'support_agent'}]}/>
 <div className="ad-card sa-content-card sa-toolbar"><input aria-label="Talep ara" placeholder="Talep no veya konu ara…" value={query} onChange={e=>param('q',e.target.value.slice(0,120))}/><select aria-label="Talep durumu" value={filter} onChange={e=>param('status',e.target.value)}><option value="all">Durum: Tümü</option><option value="open">Açık</option><option value="closed">Çözüldü</option></select></div>
 <div className="sp-support"><aside className="sp-ticket-list">{tickets.map(t=><button className={`ad-card ${ticket?.id===t.id?'is-selected':''}`} key={t.id} onClick={()=>{param('ticket',t.id);setReply('');setError('');}}><small>#{t.id} · {t.category}</small><h3>{t.subject}</h3><p>{t.messages[t.messages.length-1]?.text.slice(0,140)}</p><span className={`ad-pill ${t.status==='closed'?'green':'blue'}`}>{t.status==='closed'?'Çözüldü':t.priority==='high'?'Yüksek Öncelik':'Açık'}</span></button>)}{!tickets.length&&<p className="sa-empty">Talep bulunamadı.</p>}</aside><section className="ad-card sa-content-card">{ticket?<><span className="ad-pill blue">#{ticket.id}</span><h2>{ticket.subject}</h2><p>{ticket.category} · {ticket.status==='open'?'Açık':'Çözüldü'}</p><div className="sa-messages">{ticket.messages.map(m=><article key={m.id} className={`sa-bubble ${m.author==='support'?'supplier':'store'}`}><small>{m.author==='support'?'Alceix Demo Destek':'Firma yöneticisi'}</small><p>{m.text}</p></article>)}</div><form className="sa-form" onSubmit={e=>{e.preventDefault();if(reply.trim().length<2||ticket.messages.length>=200){setError('Yanıtınızı yazın. Görüşme limiti 200 mesaj.');return;}updateTools(t=>({...t,tickets:t.tickets.map(i=>i.id===ticket.id?{...i,messages:[...i.messages,{id:crypto.randomUUID(),text:reply.trim(),author:'supplier'}]}:i)}));setReply('');setError('');notify('Yanıt yerel demo görüşmesine eklendi; destek ekibine gönderilmedi.');}}><label>Yanıtınız<textarea value={reply} maxLength={2000} disabled={ticket.status==='closed'} onChange={e=>setReply(e.target.value)} rows={3}/></label>{error&&<p role="alert" className="sa-error">{error}</p>}<div className="sa-actions"><button className="ad-button" disabled={!ready||ticket.status==='closed'||!reply.trim()}>Demo Yanıtı Ekle</button><button type="button" className="ad-button light" onClick={()=>{updateTools(t=>({...t,tickets:t.tickets.map(i=>i.id===ticket.id?{...i,status:i.status==='closed'?'open':'closed'}:i)}));notify('Yerel talep durumu güncellendi.');}}>{ticket.status==='open'?'Talebi Çözüldü Olarak Kapat':'Talebi Yeniden Aç'}</button></div></form></>:<p>İlk destek talebinizi oluşturun.</p>}</section></div></>;
}
