'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {influencerRoutes as r} from '@/config/influencer-routes';
import {useCreatorWorkspace} from '../components/workspace-provider';
import {Heading,Field,Empty} from '../components/ui';
import {brands} from '../mocks/workspace';
import {messageIssue} from '../utils/workspace';
export function CreatorMessages(){const {workspace,ready,save,notify,creatorId}=useCreatorWorkspace(),params=useSearchParams(),[body,setBody]=useState(''),[error,setError]=useState('');const brand=brands.find(b=>b.id===params.get('brand'))||brands[0];return <><Heading title="Mesajlar & İş Birlikleri" description="Mağazalar ve tedarikçilerle ürün, brief ve teslim görüşmelerini Alceix içinde sürdür."/><section className="ad-card ic-chat"><nav aria-label="Firma görüşmeleri">{brands.map(b=><Link href={r.messages(creatorId)+'?brand='+b.id} key={b.id} aria-current={brand.id===b.id} onClick={()=>{setBody('');setError('');}}>{b.name}<small className="ic-muted" style={{display:'block'}}>{b.city} · {b.kind==='store'?'Mağaza':'Tedarikçi'}</small></Link>)}</nav><div className="ic-conversation"><h2>{brand.name}</h2><p className="ic-note">Harici iletişim bilgilerini paylaşmadan görüş. Bu demo mesajları yalnızca bu tarayıcıda saklanır.</p><div className="ic-bubbles" role="log" aria-label="Görüşme mesajları">{workspace.messages.filter(m=>m.brandId===brand.id).map(m=><div key={m.id} className={`ic-bubble ${m.author==='creator'?'mine':''}`}><small>{m.author==='creator'?'Sen':brand.name}</small><p>{m.body}</p></div>)}{!workspace.messages.some(m=>m.brandId===brand.id)&&<Empty>İlk görüşmeni başlat.</Empty>}</div><form onSubmit={e=>{e.preventDefault();const issue=messageIssue(body);if(issue){setError(issue);return;}if(save({...workspace,messages:[...workspace.messages,{id:crypto.randomUUID(),brandId:brand.id,body:body.trim(),author:'creator'}]})){setBody('');setError('');notify('Mesaj demo görüşmesine kaydedildi. Gerçek gönderim yapılmadı.');}}}><Field label="Mesajın"><textarea required minLength={2} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="İş birliği hakkında yaz…"/></Field>{error&&<p className="ic-error" role="alert">{error}</p>}<button className="ad-button" disabled={!ready}>Demo Mesajını Kaydet</button></form></div></section></>;}
