"use client";
import {usePublishedCreator} from "@/modules/creator-directory";
import Image from 'next/image';
import Link from 'next/link';
import { useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import {replaceLocalQuery} from "../utils/local-query";
import { AdminShell } from '../components/admin-shell';
import type { AdminStore } from '../mocks/dashboard';
import type { Creator, CreatorPortfolio } from '../types/influencer';
import { storeRoutes } from '@/config/store-routes';
import '../influencer.css';
import '../creator-detail.css';
const number=(n:number)=>new Intl.NumberFormat('tr-TR').format(n);
const money=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n/100);
function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;}
export function CreatorDetailScreen({store,creator:initialCreator,portfolio:initialPortfolio}:{store:AdminStore;creator:Creator;portfolio:CreatorPortfolio}) {
 const {creator,portfolio}=usePublishedCreator(initialCreator,initialPortfolio);
 const params=useSearchParams(),dialog=useRef<HTMLDialogElement>(null);
 const [notice,setNotice]=useState(''),[work,setWork]=useState(portfolio.works[0]);
 const raw=params.get('format')||'',format=['Story','Reels','Post','Video'].includes(raw)?raw:'';
 const works=portfolio.works.filter(w=>!format||w.format===format);
 function filter(value:string){const next=new URLSearchParams(params.toString());if(value)next.set('format',value);else next.delete('format');replaceLocalQuery(`${storeRoutes.creator(store.slug,creator.id)}${next.size?`?${next}`:''}#portfolio`);}
 const overlay=<dialog ref={dialog} className="ad-dialog cp-work-dialog" aria-labelledby="cp-work-title"><div className="ad-dialog-heading"><span className="ad-icon-box blue"><Icon name="collections"/></span><button autoFocus aria-label="Portföy penceresini kapat" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></div><h2 id="cp-work-title">{work.title}</h2><p className="cp-muted">{work.brand} · {work.format} · Örnek çalışma</p><Image src={work.image} alt={work.title} width={700} height={450}/><p>{work.description}</p><div className="cp-work-results"><Metric label="Görüntüleme" value={number(work.views)}/><Metric label="Erişim" value={number(work.reach)}/><Metric label="Bağlantı Tıklaması" value={number(work.clicks)}/></div><h3>Teslim Edilen İçerikler</h3><ul>{work.deliverables.map(d=><li key={d}><Icon name="check_circle"/>{d}</li>)}</ul><p className="cp-muted">Bu görseller ve sonuçlar portföy tasarımını göstermek için hazırlanmış örneklerdir; gerçek marka referansı değildir.</p><Link className="im-secondary" href={storeRoutes.messages(store.slug,`creator:${creator.id}`)}>Sohbeti Aç</Link><Link className="ad-button im-full" href={storeRoutes.influencerOffer(store.slug,creator.id)}>Benzer Bir İş Birliği Hazırla<Icon name="arrow_forward"/></Link></dialog>;
 return <AdminShell store={store} active="influencer" overlay={overlay} onNotice={setNotice}>
  <div className="cp-breadcrumb"><Link href={storeRoutes.influencer(store.slug)}><Icon name="arrow_back"/>İçerik Üreticilerine Dön</Link><span>Influencer Portföyü / {creator.name}</span></div>
  <section className="ad-card cp-hero"><div className="cp-hero-banner"><span><Icon name="auto_awesome"/>ALCEIX CREATOR PORTFOLIO</span><span className="ad-pill blue">Örnek Profil</span><div className="cp-cover-decoration" aria-hidden="true">✦</div></div><div className="cp-hero-body">{creator.photo?<Image className="cp-avatar" src={creator.photo} alt={creator.name} width={100} height={100}/>:<span className="cp-avatar cp-initials">{creator.initials}</span>}<div className="cp-identity"><div><h1>{creator.name}</h1><span className="ad-pill green">{creator.category} İçerik Üreticisi</span></div><p>{creator.description}</p><div className="cp-meta"><span><Icon name="location_on"/>{creator.location}, Türkiye</span><span><Icon name="work_history"/>{portfolio.experience}</span><span><Icon name="language"/>{portfolio.languages.join(' / ')}</span></div></div><div className="cp-hero-actions"><Link className="ad-button" href={storeRoutes.influencerOffer(store.slug,creator.id)}><Icon name="handshake"/>İş Birliği Hazırla</Link><button className="im-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}${storeRoutes.creator(store.slug,creator.id)}`);setNotice('Portföy bağlantısı kopyalandı.');}catch{setNotice('Bağlantı kopyalanamadı. Adres çubuğundaki bağlantıyı kullanabilirsiniz.');}}}><Icon name="link"/>Profili Paylaş</button></div></div></section>
  <nav className="cp-section-nav" aria-label="Portföy bölümleri"><a href="#about">Hakkında</a><a href="#social">Sosyal Medya</a><a href="#statistics">İçerik İstatistikleri</a><a href="#portfolio">Portföy & Yapılan İşler</a><a href="#audience">Hedef Kitle</a></nav>
  <div className="cp-layout"><div className="cp-main">
  <section id="about" className="ad-card cp-section"><header><span className="ad-icon-box blue"><Icon name="person"/></span><div><h2>Hakkında</h2><p>İçerik tarzı, uzmanlık ve çalışma yaklaşımı</p></div></header><p className="cp-bio">{portfolio.bio}</p><div className="cp-tags">{portfolio.specialties.map(t=><span key={t}>{t}</span>)}</div><div className="cp-about-facts"><div><small>Yaşadığı Şehir</small><strong><Icon name="location_on"/>{creator.location}</strong></div><div><small>İçerik Dili</small><strong>{portfolio.languages.join(', ')}</strong></div><div><small>İş Birliği Formatı</small><strong>{creator.format}</strong></div></div></section>
  <section id="social" className="cp-section"><header><span className="ad-icon-box blue"><Icon name="public"/></span><div><h2>Sosyal Medya Hesapları</h2><p>Her platformun takipçi ve performans özeti</p></div><span className="ad-pill blue">Örnek Veriler</span></header><div className="cp-social-grid">{portfolio.channels.map(c=><article className="ad-card cp-social" key={c.platform}><div><span className={`cp-platform-icon ${c.platform.toLowerCase()}`}><Icon name={c.platform==='YouTube'?'smart_display':c.platform==='TikTok'?'music_note':'photo_camera'}/></span><div><h3>{c.platform}</h3><p>{c.handle}</p></div><span className="cp-account-label">Demo Hesap</span></div><strong>{number(c.followers)}<small>{c.platform==='YouTube'?'Abone':'Takipçi'}</small></strong><div className="cp-social-metrics"><Metric label="Ort. İçerik İzlenmesi" value={number(c.views)}/><Metric label="Etkileşim Oranı" value={`%${c.engagement.toLocaleString('tr-TR')}`}/></div></article>)}</div></section>
  <section id="statistics" className="ad-card cp-section"><header><span className="ad-icon-box blue"><Icon name="monitoring"/></span><div><h2>İçerik Performansı</h2><p>Son 30 gün · İçerik başına ortalama değerler</p></div><span className="ad-pill blue">Örnek Analitik</span></header><div className="cp-content-grid">{portfolio.contentMetrics.map(m=><article key={`${m.format}-${m.platform}`}><div><Icon name={m.format==='Story'?'amp_stories':m.format==='Post'?'photo_library':'movie'}/><span>{m.format}<small>{m.platform}</small></span></div><strong>{number(m.views)}<small>Ortalama görüntüleme</small></strong><dl><div><dt>Erişim</dt><dd>{number(m.reach)}</dd></div><div><dt>Beğeni</dt><dd>{number(m.likes)}</dd></div>{m.saves>0&&<div><dt>Kaydetme</dt><dd>{number(m.saves)}</dd></div>}<div><dt>Paylaşılan içerik</dt><dd>{m.count}</dd></div></dl></article>)}</div><p className="cp-data-note"><Icon name="info"/>Görüntüleme tekrar izlemeleri, erişim farklı kullanıcıları ifade eder. Sayılar demo veridir; sosyal medya hesapları bağlı değildir.</p></section>
  <section id="portfolio" className="cp-section"><header><span className="ad-icon-box blue"><Icon name="collections_bookmark"/></span><div><h2>Portföy & Yapılan İşler</h2><p>İçerik örnekleri, teslimatlar ve kampanya sonuçları</p></div><span className="ad-pill blue">{works.length} Örnek İş</span></header><div className="cp-filters" role="group" aria-label="Portföy format filtresi">{['','Story','Reels','Post','Video'].map(f=><button key={f} aria-pressed={format===f} onClick={()=>filter(f)}>{f||'Tüm İşler'}</button>)}</div><div className="cp-works">{works.map(w=><article className="ad-card cp-work" key={w.id}><button className="cp-work-image" aria-label={`${w.title} çalışmasını incele`} onClick={()=>{setWork(w);dialog.current?.showModal();}}><Image src={w.image} alt={w.title} width={600} height={400}/><span>{w.format} · Örnek İş</span><Icon name="open_in_full"/></button><div><small>{w.brand} · {new Date(`${w.date}T12:00:00+03:00`).toLocaleDateString('tr-TR')}</small><h3>{w.title}</h3><p>{w.description}</p><div className="cp-work-results"><Metric label="Görüntüleme" value={number(w.views)}/><Metric label="Erişim" value={number(w.reach)}/><Metric label="Tıklama" value={number(w.clicks)}/></div><button className="im-secondary im-full" onClick={()=>{setWork(w);dialog.current?.showModal();}}>İş Detayını İncele<Icon name="arrow_forward"/></button></div></article>)}</div>{!works.length&&<div className="ad-card cp-empty"><Icon name="collections"/><h3>Bu formatta örnek çalışma yok</h3><p>Diğer içerik formatlarını inceleyebilirsiniz.</p><button className="im-secondary" onClick={()=>filter('')}>Tüm İşleri Göster</button></div>}</section>
  <section id="audience" className="ad-card cp-section"><header><span className="ad-icon-box blue"><Icon name="groups"/></span><div><h2>Hedef Kitle</h2><p>İş birliği planlamak için örnek kitle dağılımı</p></div></header><div className="cp-audience"><div><h3>Yaş Dağılımı</h3>{portfolio.audience.map(a=><div key={a.label}><span>{a.label}<b>%{a.percent}</b></span><progress value={a.percent} max={100}/></div>)}</div><div className="cp-audience-summary"><Icon name="location_on"/><h3>Türkiye Ağırlıklı Kitle</h3><p>İçerik kategorisi: <strong>{creator.category}</strong></p><p>Öne çıkan hedef kitle: <strong>{creator.audience}</strong></p><p className="cp-muted">Konum ve kitle bilgileri bu profil için hazırlanmış örnek veridir.</p></div></div></section>
  </div><aside className="ad-card cp-collaboration" aria-label="İş birliği özeti"><span className="ad-icon-box blue"><Icon name="handshake"/></span><h2>Birlikte Bir Hikâye Yazın</h2><p>Ürününüzü {creator.name.split(' ')[0]}’in içerik tarzıyla buluşturacak bir kampanya hazırlayın.</p><div className="cp-package"><small>Örnek İçerik Paketi</small><strong>{creator.format}</strong><span>{creator.fee?money(creator.fee):'Hediye Ürün İş Birliği'}</span></div><ul><li><Icon name="check_circle"/>Ürüne uygun içerik planı</li><li><Icon name="check_circle"/>Net teslimat beklentileri</li><li><Icon name="check_circle"/>Kampanya durum takibi</li></ul><Link className="im-secondary im-full" href={storeRoutes.messages(store.slug,`creator:${creator.id}`)}>Sohbeti Aç</Link><Link className="ad-button im-full" href={storeRoutes.influencerOffer(store.slug,creator.id)}>İş Birliği Hazırla<Icon name="arrow_forward"/></Link><p className="cp-muted">Teklif hazırlama yerel demo kampanya formunu açar. İçerik üreticiye gerçek mesaj gönderilmez.</p><Link className="cp-back-link" href={storeRoutes.influencer(store.slug)}>Diğer İçerik Üreticilerini Keşfet</Link></aside></div>
  {notice&&<div className="ad-notice" role="status"><Icon name="info"/><span>{notice}</span><button aria-label="Bildirimi kapat" onClick={()=>setNotice('')}><Icon name="close"/></button></div>}
 </AdminShell>;
}
function Metric({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>;}
