"use client";
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import {replaceLocalQuery} from "../utils/local-query";
import { AdminShell } from '../components/admin-shell';
import type { AdminStore } from '../mocks/dashboard';
import { creators, campaignProducts, initialCampaigns, campaignStatusLabels } from '../mocks/influencer';
import type { Campaign, Creator } from '../types/influencer';
import { campaignIssue, csvCell, filterCreators, isCampaigns, nextCampaignStatus } from '../utils/influencer';
import { storeRoutes } from '@/config/store-routes';
import '../influencer.css';
const money=(cents:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(cents/100);
const compact=(n:number)=>new Intl.NumberFormat('tr-TR',{notation:'compact',maximumFractionDigits:1}).format(n);
function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;}
type Mode='profile'|'offer'|'campaigns'|'campaign'|'consultant';
const blankOffer={name:'',kind:'paid' as 'paid'|'gift',productId:'cardigan',quantity:1,fee:'8500',commission:10,brief:''};
export function InfluencerScreen({store}:{store:AdminStore}) {
  const params=useSearchParams(),dialog=useRef<HTMLDialogElement>(null);
  const [campaigns,setCampaigns]=useState<Campaign[]>(initialCampaigns),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
  const [mode,setMode]=useState<Mode>('profile'),[creator,setCreator]=useState(creators[0]),[tab,setTab]=useState('overview'),[activeId,setActiveId]=useState('CMP-1001');
  const [offer,setOffer]=useState(blankOffer),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[confirmCancel,setConfirmCancel]=useState(false),[advice,setAdvice]=useState('');
  const [query,setQuery]=useState(params.get('q')||'');
  const key=`alceix:influencer:${store.slug}`;
  const openedOffer=useRef(false);
  useEffect(()=>{if(!ready||openedOffer.current||params.get('offer')!=='1')return;const selected=creators.find(c=>c.id===params.get('creator'));if(!selected)return;openedOffer.current=true;setCreator(selected);setOffer({...blankOffer,kind:selected.fee?'paid':'gift',fee:String(selected.fee/100)});setMode('offer');dialog.current?.showModal();},[params,ready]);
  useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const parsed:unknown=JSON.parse(raw);if(isCampaigns(parsed,creators.map(c=>c.id),campaignProducts.map(p=>p.id)))setCampaigns(parsed);else setNotice('Geçersiz kampanya kaydı atlandı; örnek kayıtlar gösteriliyor.');}}catch{setNotice('Kampanyalar okunamadı; örnek kayıtlar gösteriliyor.');}setReady(true);},[key]);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  useEffect(()=>setQuery(params.get('q')||''),[params]);
  function save(next:Campaign[]){if(!isCampaigns(next,creators.map(c=>c.id),campaignProducts.map(p=>p.id))){setError('Kampanya kayıt sınırına ulaşıldı veya kayıt geçersiz.');return false;}try{localStorage.setItem(key,JSON.stringify(next));setCampaigns(next);return true;}catch{setError('Kayıt saklanamadı. Tarayıcı depolama alanını kontrol edin.');return false;}}
  function open(next:Mode,c?:Creator){if(c)setCreator(c);setMode(next);setTab('overview');setError('');setDiscard(false);setConfirmCancel(false);dialog.current?.showModal();}
  function openOffer(c=creators[0],kind:'paid'|'gift'=c.fee===0?'gift':'paid'){setOffer({...blankOffer,kind,fee:String(kind==='gift'?0:c.fee/100)});setDirty(false);open('offer',c);}
  function close(){if(mode==='offer'&&dirty){setDiscard(true);return;}dialog.current?.close();}
  function updateFilter(name:string,value:string){const next=new URLSearchParams(params.toString());if(value)next.set(name,value);else next.delete(name);replaceLocalQuery(`${storeRoutes.influencer(store.slug)}${next.size?`?${next}`:''}`);}
  const filters={q:params.get('q')||'',platform:params.get('platform')||'',category:params.get('category')||'',audience:params.get('audience')||'',followers:params.get('followers')||'',kind:params.get('kind')||'',sort:params.get('sort')||'engagement'};
  // Unknown query values fall back to the unfiltered view.
  if(!['Instagram','TikTok','YouTube','Twitch'].includes(filters.platform))filters.platform='';
  if(!['Moda','Yaşam','Teknoloji'].includes(filters.category))filters.category='';
  if(!['Kadın','Erkek','Karma'].includes(filters.audience))filters.audience='';
  if(!['micro','macro'].includes(filters.followers))filters.followers='';
  if(!['gift','paid'].includes(filters.kind))filters.kind='';
  const filtered=filterCreators(creators,filters),active=campaigns.find(c=>c.id===activeId);
  const activeCreator=active?creators.find(c=>c.id===active.creatorId):undefined;
  const ongoing=campaigns.filter(c=>!['completed','cancelled'].includes(c.status));
  function submitOffer(e:React.FormEvent){e.preventDefault();const amount=offer.fee.trim().replace(',','.');const fee=/^\d{1,6}(\.\d{1,2})?$/.test(amount)?Math.round(Number(amount)*100):-1;
    const input={...offer,creatorId:creator.id,fee:offer.kind==='gift'?0:fee};const issue=campaignIssue(input);if(issue){setError(issue);return;}
    const campaign:Campaign={...input,name:input.name.trim(),brief:input.brief.trim(),id:`CMP-${crypto.randomUUID()}`,status:'pending',createdAt:new Date().toISOString()};
    if(save([campaign,...campaigns])){setDirty(false);setActiveId(campaign.id);setMode('campaign');setNotice('Kampanya bu tarayıcıda oluşturuldu. İçerik üreticiye teklif veya ürün gönderilmedi.');}
  }
  function advance(){if(!active)return;const next=nextCampaignStatus(active.status);if(next&&save(campaigns.map(c=>c.id===active.id?{...c,status:next}:c)))setNotice('Kampanyanın demo durumu güncellendi. Gerçek onay veya kargo işlemi yapılmadı.');}
  function exportCsv(){const rows=[['Kampanya','İçerik üretici','Durum','Ürün adedi','Teklif (TRY)','Komisyon (%)'],...campaigns.map(c=>[c.name,creators.find(p=>p.id===c.creatorId)?.name||'',campaignStatusLabels[c.status],String(c.quantity),String(c.fee/100),String(c.commission)])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='alceix-influencer-kampanyalari.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Kampanya kayıtları için CSV indirme isteği oluşturuldu.');}
  const overlay=<dialog ref={dialog} className="ad-dialog im-dialog" aria-labelledby="im-dialog-title" onCancel={e=>{if(mode==='offer'&&dirty){e.preventDefault();setDiscard(true);}}}>
    <div className="ad-dialog-heading"><span className="ad-icon-box blue"><Icon name="campaign"/></span><button autoFocus aria-label="İş birliği penceresini kapat" onClick={close}><Icon name="close"/></button></div>
    <h2 id="im-dialog-title">{{profile:creator.name,offer:'Yeni İş Birliği / Hediye Kampanyası',campaigns:'Kampanya Yönetimi',campaign:active?.name||'Kampanya Detayı',consultant:'Influencer Danışmanı'}[mode]}</h2>
    <p className="im-muted">Demo çalışma alanı · Gerçek teklif, ödeme veya kargo gönderimi yapılmaz.</p>
    {error&&<p className="im-error" role="alert">{error}</p>}
    {discard&&<div className="im-warning"><p>Kaydedilmemiş kampanya formu bırakılacak.</p><button onClick={()=>setDiscard(false)}>Düzenlemeye Dön</button><button onClick={()=>{setDirty(false);dialog.current?.close();}}>Değişiklikleri Bırak</button></div>}
    {mode==='profile'&&<><div className="im-profile-head"><Avatar creator={creator}/><div><strong>{creator.handle}</strong><p>{creator.platform} · {creator.location}</p></div><span className="ad-pill blue">Örnek profil</span></div><div className="im-tabs" role="group" aria-label="Profil bölümleri">{[['overview','Genel Bakış'],['audience','Kitle Analizi'],['portfolio','İçerik Örnekleri']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
      {tab==='overview'&&<><p>{creator.description}</p><div className="im-profile-metrics"><Metric label="Takipçi" value={compact(creator.followers)}/><Metric label="Ort. İzlenme" value={compact(creator.views)}/><Metric label="Etkileşim" value={`%${creator.engagement}`}/></div><p><strong>İçerik paketi:</strong> {creator.format}</p><p><strong>Örnek teklif:</strong> {creator.fee?money(creator.fee):'Ürün karşılığı iş birliği'}</p></>}
      {tab==='audience'&&<><p>{creator.category} içeriklerine ilgi duyan {creator.audience.toLocaleLowerCase('tr-TR')} kitle.</p><div className="im-audience"><span>Türkiye ağırlıklı kitle <b>%82</b></span><progress value={82} max={100}/><span>18–34 yaş aralığı <b>%68</b></span><progress value={68} max={100}/></div><p className="im-muted">Kitle verileri tasarım örneğidir; sosyal platform analitiği bağlı değildir.</p></>}
      {tab==='portfolio'&&<div className="im-portfolio">{creator.images.map((src,i)=><figure key={src}><Image src={src} alt={`${creator.name} için örnek ürün içeriği ${i+1}`} width={400} height={300}/><figcaption>Örnek ürün sunumu {i+1} · {creator.format}</figcaption></figure>)}</div>}
      <button className="ad-button im-full" onClick={()=>openOffer(creator)}>İş Birliği Hazırla <Icon name="arrow_forward"/></button></>}
    {mode==='offer'&&<form onSubmit={submitOffer} onChange={()=>{setDirty(true);setError('');}} className="im-form"><label>İçerik Üretici<select value={creator.id} onChange={e=>{const c=creators.find(x=>x.id===e.target.value)!;setCreator(c);setOffer({...offer,kind:c.fee?'paid':'gift',fee:String(c.fee/100)});}}>{creators.map(c=><option key={c.id} value={c.id}>{c.name} · {c.platform}</option>)}</select></label><label>Kampanya Adı<input required maxLength={100} value={offer.name} onChange={e=>setOffer({...offer,name:e.target.value})}/></label><div className="im-form-grid"><label>İş Birliği Modeli<select value={offer.kind} onChange={e=>setOffer({...offer,kind:e.target.value as 'gift'|'paid',fee:e.target.value==='gift'?'0':String(creator.fee/100)})}><option value="paid">Ücretli İş Birliği</option><option value="gift">Hediye Ürün</option></select></label><label>Gönderilecek Ürün<select value={offer.productId} onChange={e=>setOffer({...offer,productId:e.target.value})}>{campaignProducts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Ürün Adedi<input type="number" min={1} max={5} required value={offer.quantity} onChange={e=>setOffer({...offer,quantity:Number(e.target.value)})}/></label><label>Satış Komisyonu (%)<input type="number" min={0} max={30} required value={offer.commission} onChange={e=>setOffer({...offer,commission:Number(e.target.value)})}/></label></div>{offer.kind==='paid'&&<label>Teklif Tutarı (₺)<input inputMode="decimal" required value={offer.fee} onChange={e=>setOffer({...offer,fee:e.target.value})}/></label>}<label>İçerik Beklentisi & Kampanya Notu<textarea required rows={4} maxLength={1000} value={offer.brief} onChange={e=>setOffer({...offer,brief:e.target.value})}/></label><p className="im-muted">Ürünler örnek katalogdandır. Kampanya oluşturmak stok veya cüzdan bakiyesini değiştirmez.</p><button disabled={!ready} className="ad-button" type="submit">Demo Kampanyayı Oluştur<Icon name="arrow_forward"/></button></form>}
    {mode==='campaigns'&&<><div className="im-campaign-list">{campaigns.map(c=><button key={c.id} onClick={()=>{setActiveId(c.id);setMode('campaign');setConfirmCancel(false);}}><span><strong>{c.name}</strong><small>{creators.find(x=>x.id===c.creatorId)?.name} · {c.kind==='gift'?'Hediye Ürün':money(c.fee)}</small></span><span className="ad-pill blue">{campaignStatusLabels[c.status]}</span><Icon name="chevron_right"/></button>)}</div>{!campaigns.length&&<p>Henüz kampanya yok. İlk iş birliğinizi hazırlayın.</p>}<button className="im-secondary im-full" onClick={exportCsv}><Icon name="download"/>CSV Olarak İndir</button></>}
    {mode==='campaign'&&active&&<><div className="im-profile-head">{activeCreator&&<Avatar creator={activeCreator}/>}<div><strong>{activeCreator?.name}</strong><p>{activeCreator?.platform} · {active.kind==='gift'?'Hediye ürün':money(active.fee)}</p></div><span className="ad-pill blue">{campaignStatusLabels[active.status]}</span></div><div className="im-steps">{(['pending','approved','shipped','completed'] as const).map((s,i)=><div key={s} className={active.status===s?'current':''}><span>{i+1}</span>{campaignStatusLabels[s]}</div>)}</div><dl className="im-detail"><div><dt>Ürün</dt><dd>{campaignProducts.find(p=>p.id===active.productId)?.name} × {active.quantity}</dd></div><div><dt>Satış komisyonu</dt><dd>%{active.commission}</dd></div><div><dt>İçerik beklentisi</dt><dd>{active.brief}</dd></div><div><dt>Oluşturulma</dt><dd>{new Date(active.createdAt).toLocaleDateString('tr-TR')}</dd></div></dl>{nextCampaignStatus(active.status)&&<button className="ad-button im-full" onClick={advance}>Demo: {campaignStatusLabels[nextCampaignStatus(active.status)!]} Olarak İşaretle</button>}{!['cancelled','completed'].includes(active.status)&&<button className="im-cancel" onClick={()=>setConfirmCancel(true)}>Kampanyayı İptal Et</button>}{confirmCancel&&<div className="im-warning"><p>Bu demo kampanyası iptal edilsin mi?</p><button onClick={()=>setConfirmCancel(false)}>Vazgeç</button><button onClick={()=>{if(save(campaigns.map(c=>c.id===active.id?{...c,status:'cancelled'}:c))){setConfirmCancel(false);setNotice('Demo kampanyası iptal edildi.');}}}>İptali Onayla</button></div>}<button className="im-secondary im-full" onClick={()=>setMode('campaigns')}>Tüm Kampanyalar</button></>}
    {mode==='consultant'&&<><p>Hedefinize uygun iş birliği modelini seçin.</p><div className="im-advice">{[['İlk kampanyam','Küçük bir ürün seçkisi ve net bir içerik beklentisiyle başlayın. Üreticinin kitlesi ile mağazanızın hedef kitlesini karşılaştırın.'],['Hediye ürün','Ürün deneyimi için gönderim planınızı ve beklediğiniz içeriği açıkça yazın. Ürün gönderimi yayın garantisi değildir.'],['Ücretli iş birliği','İçerik formatını, yayın tarihini ve kullanım haklarını üreticiyle görüşün. Bu ekran gerçek sözleşme veya ödeme oluşturmaz.']].map(([label,text])=><button key={label} onClick={()=>setAdvice(text)}>{label}<Icon name="arrow_forward"/></button>)}</div>{advice&&<p className="im-answer" role="status">{advice}</p>}<button className="ad-button" onClick={()=>openOffer()}>Kampanya Hazırla</button></>}
  </dialog>;
  return <AdminShell store={store} active="influencer" onNotice={setNotice} overlay={overlay}>
    <header className="im-heading"><div><small>{store.name.toLocaleUpperCase('tr-TR')} · BÜYÜME & REKLAM HUB</small><h1>Influencer Pazarlaması & İş Birliği Yönetimi</h1><p>İçerik üreticilerini keşfedin, ürünlerinizi doğru kitleyle buluşturacak kampanyaları planlayın.</p></div><div><Link className="im-secondary" href={storeRoutes.campaigns(store.slug)}>Açık Kampanyalar & Başvurular</Link><button className="im-secondary" onClick={()=>open('campaigns')}><Icon name="campaign"/>Kampanyalarım <span>{ongoing.length}</span></button><button className="ad-button" disabled={!ready} onClick={()=>openOffer()}><Icon name="add_circle"/>Yeni Reklam / Hediye Kampanyası</button></div></header>
    <section className="im-stats" aria-label="Pazarlama özeti">{[{label:'Aktif İş Birlikleri',value:`${ongoing.length} Kampanya`,note:'Yerel kampanya kayıtları',icon:'handshake'},{label:'Influencer Kaynaklı Ciro',value:'₺94.850',note:'Son 30 gün · Örnek veri',icon:'payments'},{label:'Ortalama ROAS',value:'4.8×',note:'Reklam getirisi · Örnek veri',icon:'trending_up'},{label:'Toplam Video Gösterimi',value:'1.2M',note:'İzlenme · Örnek veri',icon:'play_circle'}].map(s=><article className="ad-card" key={s.label}><div><span className="ad-icon-box blue"><Icon name={s.icon}/></span><span className="ad-pill green">Demo</span></div><small>{s.label}</small><strong>{s.value}</strong><p>{s.note}</p><div className="im-stat-line"/></article>)}</section>
    <section className="ad-card im-filters" aria-label="İçerik üretici filtreleri"><div className="im-platforms" role="group" aria-label="Platformlar">{[['','Tüm Platformlar'],['Instagram','Instagram'],['TikTok','TikTok'],['YouTube','YouTube'],['Twitch','Twitch']].map(([value,label])=><button key={value} aria-pressed={filters.platform===value} onClick={()=>updateFilter('platform',value)}><i className={`im-dot ${value.toLowerCase()}`}/>{label}<span>{value?creators.filter(c=>c.platform===value).length:creators.length}</span></button>)}<label>Sıralama<select value={['followers','fee'].includes(filters.sort)?filters.sort:'engagement'} onChange={e=>updateFilter('sort',e.target.value)}><option value="engagement">En Yüksek Etkileşim</option><option value="followers">En Çok Takipçi</option><option value="fee">En Düşük Teklif</option></select></label></div><div className="im-filter-row"><form onSubmit={e=>{e.preventDefault();updateFilter('q',query);}}><Icon name="search"/><input aria-label="İçerik üretici ara" placeholder="İçerik üretici adı, kullanıcı adı…" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/><button type="submit">Ara</button></form><Filter label="Kategori" value={filters.category} options={['Moda','Yaşam','Teknoloji']} onChange={v=>updateFilter('category',v)}/><Filter label="Hedef Kitle" value={filters.audience} options={['Kadın','Erkek','Karma']} onChange={v=>updateFilter('audience',v)}/><label>Takipçi<select value={filters.followers} onChange={e=>updateFilter('followers',e.target.value)}><option value="">Tümü</option><option value="micro">Mikro · 200 bin altı</option><option value="macro">Makro · 200 bin ve üzeri</option></select></label><label>İş Birliği<select value={filters.kind} onChange={e=>updateFilter('kind',e.target.value)}><option value="">Tümü</option><option value="gift">Hediye Ürün</option><option value="paid">Ücretli</option></select></label><button className="im-reset" aria-label="Influencer filtrelerini temizle" onClick={()=>replaceLocalQuery(storeRoutes.influencer(store.slug))}><Icon name="filter_alt_off"/></button></div></section>
    <div className="im-section-heading"><h2>Önerilen İçerik Üreticileri & İş Birlikleri <span className="ad-pill blue">{filtered.length} Eşleşme</span></h2><small>Profiller ve performanslar örnek veridir.</small></div>
    <section className="im-creators" aria-label="İçerik üreticiler">{filtered.map(c=><article className="ad-card im-creator" key={c.id}><div className="im-creator-head"><Avatar creator={c}/><div><h3>{c.name}</h3><small>{c.platform} · {c.category}</small></div><span className="ad-pill green">%{c.engagement}</span></div><p className="im-handle">{c.handle}</p><div className="im-creator-metrics"><Metric label="Takipçi" value={compact(c.followers)}/><Metric label="Ort. İzlenme" value={compact(c.views)}/><Metric label="Etkileşim" value={`%${c.engagement}`}/></div><button className="im-card-media" aria-label={`${c.name} içerik örneklerini incele`} onClick={()=>{open('profile',c);setTab('portfolio');}}>{c.images.map((src,i)=><Image key={src} src={src} alt={`${c.name} için örnek ürün sunumu ${i+1}`} width={200} height={160}/>)}<span><Icon name="play_circle"/>İçerik Örnekleri</span></button><div className="im-package"><span>{c.format}</span><strong>{c.fee?money(c.fee):'Hediye Ürün'}</strong></div><p className="im-muted">{c.fee?'Ürün + içerik paketi':'Ürün deneyimi odaklı iş birliği'}</p><button disabled={!ready} className={`ad-button im-full ${c.fee?'':'im-gift'}`} onClick={()=>openOffer(c)}><Icon name={c.fee?'handshake':'redeem'}/>{c.fee?'İş Birliği Teklifi Hazırla':'Hediye Ürün Hazırla'}</button><Link className="im-profile-button" href={storeRoutes.creator(store.slug,c.id)}>Tüm Detaylar<Icon name="chevron_right"/></Link></article>)}</section>
    {!filtered.length&&<div className="ad-card im-empty"><Icon name="search_off"/><h2>İçerik üretici bulunamadı</h2><p>Farklı filtrelerle tekrar deneyin.</p><button className="im-secondary" onClick={()=>replaceLocalQuery(storeRoutes.influencer(store.slug))}>Filtreleri Temizle</button></div>}
    <section className="im-bottom"><article className="ad-card im-how"><h2><Icon name="lightbulb"/>Nasıl Çalışır?</h2>{[['İçerik üreticisini seçin','Kitlesini, içerik formatını ve ürün uyumunu inceleyin.'],['İş birliğini hazırlayın','Ürün, teklif ve içerik beklentinizi belirleyin.'],['Kampanyayı takip edin','Onay, gönderim ve tamamlanma adımlarını yönetin.']].map(([title,text],i)=><div key={title}><span>{i+1}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}<p className="im-demo">Alceix örnek iş birliği akışı · Gerçek mesajlaşma bağlı değildir.</p></article><article className="ad-card im-ongoing"><header><h2><Icon name="local_shipping"/>Devam Eden Kampanyalar</h2><button onClick={()=>open('campaigns')}>Tümünü Gör ({ongoing.length})</button></header>{ongoing.slice(0,3).map(c=><button key={c.id} onClick={()=>{setActiveId(c.id);open('campaign');}}><span className="im-mini-avatar">{creators.find(p=>p.id===c.creatorId)?.initials}</span><span><strong>{creators.find(p=>p.id===c.creatorId)?.name}</strong><small>{c.name}</small></span><span className="ad-pill green">{campaignStatusLabels[c.status]}</span></button>)}{!ongoing.length&&<p>Devam eden kampanyanız yok.</p>}<button className="im-export" onClick={exportCsv}><Icon name="download"/>Kampanya Kayıtlarını İndir (.CSV)</button></article><article className="ad-card im-consultant"><span className="ad-icon-box blue"><Icon name="support_agent"/></span><h2>Influencer Danışmanı</h2><small>Mağazanız için doğru iş birliği</small><p>İlk kampanyanızı planlayın, hediye ürün ve ücretli içerik modelleri hakkında rehberleri inceleyin.</p><span className="ad-pill blue">Yerel demo rehberi</span><button className="ad-button" onClick={()=>open('consultant')}>Görüşmeye Başla<Icon name="arrow_forward"/></button></article></section>
    {notice&&<div className="ad-notice" role="status"><Icon name="info"/><span>{notice}</span><button aria-label="Bildirimi kapat" onClick={()=>setNotice('')}><Icon name="close"/></button></div>}
  </AdminShell>;
}
function Avatar({creator}:{creator:Creator}){return creator.photo?<Image className="im-avatar" src={creator.photo} alt={creator.name} width={44} height={44}/>:<span className="im-avatar im-initials">{creator.initials}</span>;}
function Metric({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>;}
function Filter({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Tümü</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>;}
