"use client";
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { AdminShell } from '../components/admin-shell';
import type { AdminStore } from '../mocks/dashboard';
import { demoProducts } from '../mocks/products';
import { defaultStudioSettings, initialStudioState, studioOptions, studioScenes, variantLabels } from '../mocks/studio';
import { isAdminProduct } from '../utils/product';
import { studioCost, generationIssue, isStudioImage, isStudioSettings, isStudioState, uploadImageIssue } from '../utils/studio';
import type { AdminProduct } from '../types/product';
import type { StudioEntry, StudioSettings } from '../types/studio';
import { storeRoutes } from '@/config/store-routes';
import '../studio.css';
function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;}
type Modal='catalog'|'credits'|'batch'|'gallery'|'zoom'|'compare'|'publish';
export function StudioScreen({store}:{store:AdminStore}) {
 const params=useSearchParams(),dialog=useRef<HTMLDialogElement>(null),fileInput=useRef<HTMLInputElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),uploadReader=useRef<FileReader|null>(null);
 const [products,setProducts]=useState<AdminProduct[]>(demoProducts),[productId,setProductId]=useState('demo-product-1'),[sourceOverride,setSourceOverride]=useState('');
 const [studio,setStudio]=useState(initialStudioState),[settings,setSettings]=useState(defaultStudioSettings),[activeId,setActiveId]=useState('ST-demo'),[variant,setVariant]=useState(0);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[modal,setModal]=useState<Modal>('catalog'),[query,setQuery]=useState(''),[batch,setBatch]=useState<string[]>([]),[showSource,setShowSource]=useState(false);
 const key=`alceix:studio:${store.slug}`,productKey=`alceix:products:${store.slug}`;
 useEffect(()=>{try{const raw=localStorage.getItem(productKey);let catalog=demoProducts;if(raw){const parsed:unknown=JSON.parse(raw);if(Array.isArray(parsed)&&parsed.length<=1000&&parsed.every(isAdminProduct))catalog=parsed;else setNotice('Yerel katalog geçersiz; örnek ürünler gösteriliyor.');}setProducts(catalog);const requested=params.get('product');setProductId(catalog.find(p=>p.id===requested)?.id||catalog[0]?.id||'');const saved=localStorage.getItem(key);if(saved){const parsed:unknown=JSON.parse(saved);if(isStudioState(parsed)){setStudio(parsed);setActiveId(parsed.entries[0]?.id||'');}else setNotice('Stüdyo kaydı geçersiz; örnek galeri gösteriliyor.');}}catch{setNotice('Yerel kayıtlar okunamadı; örnek veriler gösteriliyor.');}setReady(true);return()=>{if(timer.current)clearTimeout(timer.current);uploadReader.current?.abort();};},[key,productKey,params]);
 const product=products.find(p=>p.id===productId),source=sourceOverride||(product?.images.find(isStudioImage)||'');
 const result=studio.entries.find(e=>e.id===activeId),image=result?.variants[variant]||'';
 function save(next:typeof studio){if(!isStudioState(next)){setError('Stüdyo kaydı geçersiz. Ayarları kontrol edin.');return false;}try{localStorage.setItem(key,JSON.stringify(next));setStudio(next);return true;}catch{setError('Tarayıcıya kaydedilemedi. Daha küçük bir görsel kullanın veya depolama alanını kontrol edin.');return false;}}
 function open(next:Modal){setModal(next);setError('');if(next==='catalog')setQuery('');if(next==='batch')setBatch(product?[product.id]:[]);dialog.current?.showModal();}
 function choose(p:AdminProduct){setProductId(p.id);setSourceOverride('');dialog.current?.close();setError('');}
 async function upload(file?:File){if(!file||busy||uploading)return;const issue=uploadImageIssue(file.type,file.size);if(issue){setError(issue);return;}setUploading(true);try{const value=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();uploadReader.current=reader;const timeout=setTimeout(()=>{reader.abort();reject(new Error('timeout'));},15000);reader.onload=()=>{clearTimeout(timeout);if(typeof reader.result==='string')resolve(reader.result);else reject();};reader.onerror=()=>{clearTimeout(timeout);reject();};reader.onabort=()=>{clearTimeout(timeout);reject();};reader.readAsDataURL(file);});const img=document.createElement('img');img.src=value;await img.decode();if(!isStudioImage(value))throw new Error();setSourceOverride(value);setError('');setNotice('Kaynak görsel seçildi. Dosya yalnızca bu tarayıcıda kullanılır.');}catch{setError('Görsel okunamadı veya okuma iptal edildi. Daha küçük bir PNG, JPG veya WebP ile tekrar deneyin.');}finally{setUploading(false);uploadReader.current=null;if(fileInput.current)fileInput.current.value='';}}
 function produce(ids:string[]){if(busy||uploading||!ready)return;const selected=ids.map(id=>products.find(p=>p.id===id)).filter((p):p is AdminProduct=>!!p);const issue=generationIssue(studio.credits,selected.length,selected.every(p=>!!(p.id===productId?source:p.images.find(isStudioImage))),isStudioSettings(settings));if(issue){setError(issue);return;}if(studio.entries.length+selected.length>30){setError('Demo galeri en fazla 30 üretim kaydı tutabilir.');return;}setBusy(true);setError('');dialog.current?.close();
  timer.current=setTimeout(()=>{const entries:StudioEntry[]=selected.map(p=>{const original=p.id===productId?source:p.images.find(isStudioImage)!;const variants=p.category==='Giyim'&&settings.mode==='model'?['/influencer/selin-yilmaz.jpg','/dropshipping/supplier-knit.jpg','/dropshipping/store-knit.jpg','/storefront/gallery/cardigan-alternate.png']:[original,p.images.filter(isStudioImage)[1]||original,original,original];return {id:`ST-${crypto.randomUUID()}`,productId:p.id,productName:p.name,source:original,variants,settings:{...settings},createdAt:new Date().toISOString()};});if(save({credits:studio.credits-selected.length*studioCost,entries:[...entries,...studio.entries]})){setActiveId(entries[0].id);setVariant(0);setShowSource(false);setNotice(`${selected.length*4} demo varyasyon hazırlandı. Örnek görseller kullanıldı; gerçek AI üretimi veya ücret tahsilatı yapılmadı.`);}setBusy(false);timer.current=null;},700);
 }
 function cancel(){if(timer.current)clearTimeout(timer.current);timer.current=null;setBusy(false);setNotice('Demo hazırlama iptal edildi; kredi kullanılmadı.');}
 async function download(){if(!image)return;try{const response=await fetch(image);if(!response.ok)throw new Error();const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`alceix-${result?.productId||'gorsel'}-${variant+1}.${blob.type.includes('png')?'png':blob.type.includes('webp')?'webp':'jpg'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Örnek görsel için indirme isteği oluşturuldu.');}catch{setError('Görsel indirilemedi. Tekrar deneyin.');}}
 function publish(asCover:boolean){if(!result||!isStudioImage(image))return;try{const raw=localStorage.getItem(productKey);let latest=products;if(raw){const parsed:unknown=JSON.parse(raw);if(!Array.isArray(parsed)||!parsed.every(isAdminProduct))throw new Error();latest=parsed;}const target=latest.find(p=>p.id===result.productId);if(!target){setError('Bu ürün artık katalogda bulunmuyor. Başka bir ürün seçin.');return;}const images=asCover?[image,...target.images.filter(src=>src!==image)]:[...target.images.filter(src=>src!==image),image];const next=latest.map(p=>p.id===target.id?{...p,images}:p);localStorage.setItem(productKey,JSON.stringify(next));setProducts(next);dialog.current?.close();setNotice(asCover?'Örnek görsel yerel ürün kataloğunun ana fotoğrafı yapıldı.':'Örnek görsel yerel ürün kataloğuna eklendi.');}catch{setError('Ürün görseli kaydedilemedi. Katalog kaydını ve tarayıcı depolama alanını kontrol edin.');}}
 function view(entry:StudioEntry){setActiveId(entry.id);setVariant(0);setShowSource(false);dialog.current?.close();setNotice(`${entry.productName} arşivden açıldı.`);}
 const catalog=products.filter(p=>`${p.name} ${p.sku}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')));
 const overlay=<dialog ref={dialog} className={`ad-dialog st-dialog${modal==='zoom'||modal==='compare'?' st-wide':''}`} aria-labelledby="st-dialog-title"><div className="ad-dialog-heading"><span className="ad-icon-box blue"><Icon name="auto_fix_high"/></span><button autoFocus aria-label="Stüdyo penceresini kapat" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></div><h2 id="st-dialog-title">{{catalog:'Kaynak Ürün Seçimi',credits:'Demo Kredi Yönetimi',batch:'Toplu Varyasyon Hazırlama',gallery:'Görsel Galerisi',zoom:'Görsel Önizleme',compare:'Öncesi / Sonrası',publish:'Ürün Kataloğuna Aktar'}[modal]}</h2><p className="st-muted">Demo stüdyo · AI servisi, gerçek 4K üretim veya ücretli kredi sistemi bağlı değildir.</p>{error&&<p role="alert" className="st-error">{error}</p>}
 {modal==='catalog'&&<><label className="st-search">Ürün Ara<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün adı veya SKU"/></label><div className="st-catalog">{catalog.map(p=><button key={p.id} onClick={()=>choose(p)}>{p.images.find(isStudioImage)&&<Image src={p.images.find(isStudioImage)!} alt={p.name} width={55} height={65}/>}<span><strong>{p.name}</strong><small>{p.sku} · {p.stock} adet</small></span><Icon name="chevron_right"/></button>)}</div>{!catalog.length&&<p>Ürün bulunamadı.</p>}<Link className="ad-button" href={storeRoutes.products(store.slug)}>Ürün Yönetimini Aç</Link></>}
 {modal==='credits'&&<><div className="st-credit-summary"><Icon name="bolt"/><strong>{studio.credits} Demo Kredi</strong></div><p>Her ürün için 4 örnek varyasyon: {studioCost} demo kredi. Gerçek satın alma veya ödeme işlemi yapılmaz.</p><button className="ad-button" disabled={studio.credits>9900} onClick={()=>{if(save({...studio,credits:studio.credits+100})){setNotice('100 demo kredi eklendi. Ücret alınmadı.');dialog.current?.close();}}}>100 Demo Kredi Ekle</button></>}
 {modal==='batch'&&<><p>En fazla 3 ürün seçin. Her ürün için 4 demo varyasyon hazırlanır.</p><div className="st-batch">{products.map(p=><label key={p.id}><input type="checkbox" checked={batch.includes(p.id)} disabled={!batch.includes(p.id)&&batch.length>=3} onChange={e=>setBatch(e.target.checked?[...batch,p.id]:batch.filter(id=>id!==p.id))}/><span>{p.name}<small>{p.sku}</small></span></label>)}</div><p className="st-muted">{batch.length} ürün · {batch.length*studioCost} demo kredi</p><button className="ad-button" disabled={!batch.length||busy} onClick={()=>produce(batch)}>Seçili Ürünleri Hazırla</button></>}
 {modal==='gallery'&&<div className="st-gallery-modal">{studio.entries.map(e=><button key={e.id} onClick={()=>view(e)}><Image src={e.variants[0]} alt={e.productName} width={160} height={200}/><strong>{e.productName}</strong><small>{new Date(e.createdAt).toLocaleDateString('tr-TR')} · 4 örnek varyasyon</small></button>)}{!studio.entries.length&&<p>Galeriniz henüz boş.</p>}</div>}
 {modal==='zoom'&&image&&<Image className="st-zoom" src={image} alt={`${result?.productName} örnek varyasyon`} width={800} height={1000}/>}
 {modal==='compare'&&result&&<div className="st-comparison"><figure><Image src={result.source} alt="Kaynak ürün görseli" width={400} height={500}/><figcaption>Kaynak Görsel</figcaption></figure><figure><Image src={image} alt="Örnek sonuç görseli" width={400} height={500}/><figcaption>Demo Sonuç · Gerçek AI üretimi değil</figcaption></figure></div>}
 {modal==='publish'&&result&&<><p><strong>{result.productName}</strong> ürününe seçili örnek görseli ekleyin. Ürünün satış durumu değişmez; genel mağaza vitrini bu yerel katalog kaydına henüz bağlı değildir.</p><div className="st-publish-preview"><Image src={image} alt="Kataloğa aktarılacak görsel" width={150} height={180}/><div><button className="ad-button" onClick={()=>publish(true)}>Katalog Ana Fotoğrafı Yap</button><button className="st-secondary" onClick={()=>publish(false)}>Ek Görsel Olarak Ekle</button></div></div></>}
 </dialog>;
 return <AdminShell store={store} active="studio" overlay={overlay} onNotice={setNotice}>
 <header className="st-heading"><div><small>Dashboard / Ürün Yönetimi / AI Görsel & Sanal Manken Stüdyosu</small><h1>AI Sanal Manken & Ürün Görsel Stüdyosu <span className="ad-pill blue">Demo Stüdyo</span></h1><p>Ürünlerinizi farklı model ve sahne seçenekleriyle sunmak için görsel iş akışınızı hazırlayın.</p></div><div className="st-header-actions"><button className="st-credits" disabled={!ready||busy} onClick={()=>open('credits')}><Icon name="bolt"/><span>Mevcut Demo Kredi<strong>{studio.credits}</strong></span><b>+ Ekle</b></button><button className="st-secondary" disabled={!ready||busy} onClick={()=>open('batch')}><Icon name="layers"/>Toplu Üretim</button><button className="st-secondary" onClick={()=>open('gallery')}><Icon name="photo_library"/>Galeri ({studio.entries.length})</button></div></header>
 <div className="st-layout"><div className="st-controls"><div className="st-mode-tabs" role="group" aria-label="Stüdyo modu">{[['model','Manken Giydirme','person'],['scene','Sahne & Işık','wb_sunny'],['upscale','Netleştirme','auto_awesome']].map(([id,title,icon])=><button key={id} disabled={busy} aria-pressed={settings.mode===id} onClick={()=>setSettings({...settings,mode:id as StudioSettings['mode']})}><Icon name={icon}/>{title}</button>)}</div>
 <section className="ad-card st-source"><header><h2><Icon name="inventory_2"/>Kaynak Ürün Görseli</h2><button disabled={busy} onClick={()=>open('catalog')}>Katalogdan Değiştir<Icon name="expand_more"/></button></header><div>{source?<Image src={source} alt={product?.name||'Yüklenen kaynak görsel'} width={60} height={75}/>:<Icon name="image"/>}<span><strong>{product?.name||'Kaynak ürün seçin'}</strong><small>{product?.sku} · {product?.category}</small><small>{sourceOverride?'Yüklenen görsel':'Yerel katalog görseli'}</small></span></div><button className="st-upload" disabled={busy||uploading} onClick={()=>fileInput.current?.click()}><Icon name="upload"/>{uploading?'Görsel okunuyor…':'Kendi Görselini Yükle'}</button><input hidden type="file" ref={fileInput} accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])}/>{uploading&&<button className="st-upload" onClick={()=>uploadReader.current?.abort()}>Dosya Okumayı İptal Et</button>}<small className="st-muted">PNG, JPG, WebP · En fazla 2 MB</small></section>
 <fieldset disabled={busy||uploading} className="st-settings-fieldset"><section className="ad-card st-model"><header><h2><Icon name="accessibility_new"/>Sanal Manken & Tipoloji</h2><span>Örnek model ayarları</span></header>{(['gender','appearance','size','age','pose'] as const).map(field=><div className="st-choice" key={field}><span>{{gender:'Manken Cinsiyeti',appearance:'Model Görünümü',size:'Beden Ölçüsü',age:'Manken Yaşı',pose:'Poz & Kamera Açısı'}[field]}</span><div role="group" aria-label={{gender:'Manken cinsiyeti',appearance:'Model görünümü',size:'Beden ölçüsü',age:'Manken yaşı',pose:'Poz ve kamera açısı'}[field]}>{studioOptions[field].map(value=><button type="button" key={value} aria-pressed={settings[field]===value} onClick={()=>setSettings({...settings,[field]:value})}>{value}</button>)}</div></div>)}</section>
 <section className="ad-card st-scene"><header><h2><Icon name="wb_sunny"/>Sahne & Işık Atmosferi</h2><span className="st-green">Sahne önizlemeleri</span></header><div className="st-scenes" role="group" aria-label="Sahne seçimi">{studioScenes.map(s=><button key={s.id} type="button" aria-pressed={settings.scene===s.id} onClick={()=>setSettings({...settings,scene:s.id})}><Image src={s.image} alt="" width={180} height={110}/><span><strong>{s.name}</strong><small>{s.note}</small></span></button>)}</div><label>Detaylı Ortam İpucu<textarea rows={3} maxLength={600} value={settings.prompt} onChange={e=>setSettings({...settings,prompt:e.target.value})}/></label><div className="st-ratio"><label>En / Boy Oranı<select value={settings.ratio} onChange={e=>setSettings({...settings,ratio:e.target.value})}>{studioOptions.ratio.map(r=><option key={r}>{r}</option>)}</select></label><span>4K servis bağlantısı bekleniyor</span></div></section></fieldset>
 {error&&<p className="st-error" role="alert">{error}</p>}<button className="ad-button st-generate" disabled={!ready||busy||uploading||!product} onClick={()=>produce([productId])}><Icon name="auto_awesome"/>{busy?'Demo Varyasyonlar Hazırlanıyor…':'4 Demo Varyasyon Hazırla'}<span>{studioCost} Demo Kredi</span></button>{busy&&<button className="st-secondary st-cancel" onClick={cancel}>Hazırlamayı İptal Et</button>}<p className="st-pro-tip"><Icon name="lightbulb"/><span>Pro ipucu: Düz zemin ve net ürün görselleri kullanın. Bu prototipte ayarlar gerçek görsel üretimine uygulanmaz.</span></p></div>
 <section className="ad-card st-result" aria-label="Üretim sonucu"><header><div><h2><i/>Son Üretim Sonucu <span className="ad-pill blue">Varyasyon {variant+1}</span></h2><p>{result?.productName||'Henüz sonuç yok'} · Örnek görsel</p></div><div><button className="st-secondary" disabled={!result} onClick={()=>open('compare')}><Icon name="compare"/>Öncesi / Sonrası</button><button className="st-secondary" disabled={!image} onClick={()=>void download()}><Icon name="download"/>Görsel İndir</button></div></header>
 <div className="st-main-image" style={{aspectRatio:result?.settings.ratio.replace(':',' / ')||'4 / 5'}}>{image?<Image src={showSource&&result?result.source:image} alt={showSource?'Kaynak ürün görseli':`${result?.productName} demo varyasyon ${variant+1}`} width={900} height={1100} priority/>:<div className="st-empty"><Icon name="auto_fix_high"/><h3>İlk görselinizi hazırlayın</h3><p>Bir ürün ve sahne seçerek başlayın.</p></div>}<span className="st-image-badge"><Icon name="verified"/>Alceix Stüdyo · Demo Önizleme</span>{busy&&<div className="st-processing" role="status"><Icon name="auto_awesome"/>Örnek varyasyonlar hazırlanıyor…</div>}<div className="st-image-toolbar"><button aria-label="Görseli büyüt" disabled={!image} onClick={()=>open('zoom')}><Icon name="zoom_in"/></button><button aria-label="Kaynak görseli göster" aria-pressed={showSource} disabled={!result} onClick={()=>setShowSource(!showSource)}><Icon name="compare"/></button><button aria-label="Seçili görseli indir" disabled={!image} onClick={()=>void download()}><Icon name="download"/></button><button className="ad-button" disabled={!image||busy} onClick={()=>open('publish')}><Icon name="storefront"/>Ürün Kataloğuna Aktar</button></div></div>
 <div className="st-variants-heading"><h3>Tüm Varyasyonlar ({result?.variants.length||0})</h3><small>Önizlemek için seçin</small></div><div className="st-variants">{result?.variants.map((src,i)=><button key={i} aria-pressed={variant===i} aria-label={`Varyasyon ${i+1}: ${variantLabels[i]}`} onClick={()=>{setVariant(i);setShowSource(false);}}><Image src={src} alt={`${variantLabels[i]} örnek görsel`} width={180} height={200}/><strong>{i+1}. {variantLabels[i]}</strong><small>{variant===i?'Aktif Önizleme':'Örnek Varyasyon'}</small></button>)}</div><div className="st-cover"><span className="ad-icon-box solid"><Icon name="photo"/></span><div><h3>Seçili görseli ürününüzde kullanın</h3><p>Yerel ürün kataloğunda ana fotoğraf veya ek görsel olarak kaydedin.</p></div><button disabled={!image||busy} onClick={()=>open('publish')}>Ana Fotoğraf Yap<Icon name="arrow_forward"/></button></div></section></div>
 <section className="st-archive"><header><div><h2><Icon name="photo_library"/>Daha Önce Hazırlananlar · {store.name}</h2><p>Bu tarayıcıda saklanan demo görsel arşivi</p></div><button onClick={()=>open('gallery')}>Tüm Arşivi Gör<Icon name="arrow_forward"/></button></header><div className="st-archive-grid">{studio.entries.slice(0,5).map(e=><button key={e.id} onClick={()=>view(e)}><Image src={e.variants[0]} alt={e.productName} width={180} height={220}/><strong>{e.productName}</strong><small>{new Date(e.createdAt).toLocaleDateString('tr-TR')} · Demo</small></button>)}<Link href={storeRoutes.products(store.slug)}><Icon name="add_photo_alternate"/><strong>Yeni Ürün Ekle</strong><span>Kataloğunuzu hazırlayıp stüdyoya dönün.</span></Link></div></section>{notice&&<div className="ad-notice" role="status"><Icon name="info"/><span>{notice}</span><button aria-label="Bildirimi kapat" onClick={()=>setNotice('')}><Icon name="close"/></button></div>}</AdminShell>;
}
