export const storeRoutes = {
  reviews:(slug:string)=>`/${encodeURIComponent(slug)}/admin/degerlendirmeler`,
  profile: (slug:string) => `/${encodeURIComponent(slug)}/admin/profil`,
  team: (slug:string) => `/${encodeURIComponent(slug)}/admin/ekip`,
  campaigns: (slug:string, campaign?:string) => `/${encodeURIComponent(slug)}/admin/kampanyalar${campaign ? `?${new URLSearchParams({campaign})}` : ''}`,
  messages: (slug:string, thread?:string) => `/${encodeURIComponent(slug)}/admin/mesajlar${thread ? `?${new URLSearchParams({thread})}` : ''}`,
  storefront: (slug: string) => `/${encodeURIComponent(slug)}`,
  admin: (slug: string) => `/${encodeURIComponent(slug)}/admin`,
  orders: (slug: string) => `/${encodeURIComponent(slug)}/admin/siparisler`,
  order: (slug: string, orderId: string) => `/${encodeURIComponent(slug)}/admin/siparisler/${encodeURIComponent(orderId)}`,
  design: (slug: string) => `/${encodeURIComponent(slug)}/admin/vitrin`,
  designPreview: (slug: string, version: "draft" | "published" = "draft") => `/${encodeURIComponent(slug)}/admin/vitrin/onizleme?${new URLSearchParams({version})}`,
  studio: (slug: string, productId?: string) => `/${encodeURIComponent(slug)}/admin/studyo${productId ? `?${new URLSearchParams({product:productId})}` : ""}`,
  creator: (slug: string, creatorId: string) => `/${encodeURIComponent(slug)}/admin/influencer/${encodeURIComponent(creatorId)}`,
  influencerOffer: (slug: string, creatorId: string) => `/${encodeURIComponent(slug)}/admin/influencer?${new URLSearchParams({creator:creatorId,offer:"1"})}`,
  influencer: (slug: string) => `/${encodeURIComponent(slug)}/admin/influencer`,
  support: (slug: string) => `/${encodeURIComponent(slug)}/admin/destek`,
  suppliers: (slug: string) => `/${encodeURIComponent(slug)}/admin/tedarik`,
  supplier: (slug: string, supplierId: string) => `/${encodeURIComponent(slug)}/admin/tedarik/${encodeURIComponent(supplierId)}`,
  supplierProduct: (slug: string, supplierId: string, productId: string) => `/${encodeURIComponent(slug)}/admin/tedarik/${encodeURIComponent(supplierId)}/urun/${encodeURIComponent(productId)}`,
  customers: (slug: string) => `/${encodeURIComponent(slug)}/admin/musteriler`,
  finance: (slug: string) => `/${encodeURIComponent(slug)}/admin/finans`,
  products: (slug: string) => `/${encodeURIComponent(slug)}/admin/urunler`,
  settings: (slug: string) => `/${encodeURIComponent(slug)}/admin/ayarlar`,
  dashboard: (slug: string) => `/${encodeURIComponent(slug)}/admin/dashboard`,
};
