import type {Administration,MemberControl,ThreadControl} from '../types/administration';
import type {ManagementAccount} from '@/types/management-snapshot';
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown,max:number)=>typeof v==='string'&&v.length<=max;
export function isAdministration(value:unknown,accounts:string[],threads:string[]):value is Administration{if(!record(value)||!Array.isArray(value.members)||!Array.isArray(value.threads)||!Array.isArray(value.audit)||value.members.length>accounts.length||value.threads.length>threads.length||value.audit.length>300)return false;return new Set(value.members.map(m=>m?.accountId)).size===value.members.length&&value.members.every(m=>record(m)&&accounts.includes(String(m.accountId))&&['active','review','paused'].includes(String(m.status))&&typeof m.verified==='boolean'&&text(m.note,2000))&&new Set(value.threads.map(t=>t?.threadId)).size===value.threads.length&&value.threads.every(t=>record(t)&&threads.includes(String(t.threadId))&&typeof t.flagged==='boolean'&&text(t.note,2000))&&new Set(value.audit.map(a=>a?.id)).size===value.audit.length&&value.audit.every(a=>record(a)&&text(a.id,100)&&typeof a.target==='string'&&(accounts.includes(a.target)||threads.includes(a.target))&&text(a.action,150)&&typeof a.reason==='string'&&a.reason.trim().length>=5&&a.reason.length<=2000&&typeof a.createdAt==='string'&&Number.isFinite(Date.parse(a.createdAt)));}
export function setMemberControl(current:Administration,control:MemberControl,reason:string,ids:string[],auditId:string,now:string):Administration{if(!ids.includes(control.accountId)||reason.trim().length<5||reason.length>2000)throw new Error('Üye ve en az 5 karakterlik işlem gerekçesini kontrol edin.');return {...current,members:[...current.members.filter(m=>m.accountId!==control.accountId),control],audit:[{id:auditId,target:control.accountId,action:'Üye yönetim kaydı güncellendi',reason:reason.trim(),createdAt:now},...current.audit].slice(0,300)};}
export function setThreadControl(current:Administration,control:ThreadControl,ids:string[],auditId:string,now:string):Administration{if(!ids.includes(control.threadId)||control.note.trim().length<5||control.note.length>2000)throw new Error('Görüşme ve en az 5 karakterlik inceleme notunu kontrol edin.');return {...current,threads:[...current.threads.filter(t=>t.threadId!==control.threadId),control],audit:[{id:auditId,target:control.threadId,action:control.flagged?'Görüşme incelemeye alındı':'Görüşme incelemesi kapatıldı',reason:control.note.trim(),createdAt:now},...current.audit].slice(0,300)};}
export const kindLabels={store:'Mağaza',supplier:'Tedarikçi',creator:'Influencer'};
export const statusLabels={active:'Aktif',review:'İncelemede',paused:'Demo Askıya Alındı'};
export const money=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n/100);
export function accountVolume(account:ManagementAccount){return account.orders.filter(o=>o.status!=='cancelled').reduce((sum,o)=>sum+o.amountCents,0);}
export function csvExport(rows:string[][]){const cell=(s:string)=>'"'+(/^[\s]*[=+@\-]/.test(s)?"'":"")+s.replaceAll('"','""')+'"';return '\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n');}
export function queryTarget(search:string,key:string,value:string){const p=new URLSearchParams(search);if(!value||value==='all')p.delete(key);else p.set(key,value);if(key!=='page')p.delete('page');return p.toString();}
export function safePage(value:string|null,total:number){const n=Number(value||1),max=Math.max(1,Math.ceil(total/8));return Number.isSafeInteger(n)&&n>0?Math.min(n,max):1;}
