import type {Commercial,CommissionEntry,CommissionPolicy,ReferralCode,ReferralConversion} from '../types/commercial';
import type {ManagementAccount} from '@/types/management-snapshot';
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown,max:number)=>typeof v==='string'&&v.length<=max;
const integer=(v:unknown,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(v)&&Number(v)>=0&&Number(v)<=max;
const date=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const list=(v:unknown,max:number,check:(v:unknown)=>boolean)=>Array.isArray(v)&&v.length<=max&&v.every(check);
const dateOnly=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&date(v)&&new Date(v).toISOString().slice(0,10)===v;
const unique=(v:{id:string}[])=>new Set(v.map(x=>x.id)).size===v.length;
export const percent=(bps:number)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(bps/100)+'%';
export function parseBps(value:string){if(!/^\d{1,3}([.,]\d{1,2})?$/.test(value.trim()))throw new Error('0–100 arasında, en fazla iki ondalıklı oran girin.');const n=Math.round(Number(value.replace(',','.'))*100);if(n>10000)throw new Error('Oran 0–100 arasında olmalı.');return n;}
export function currentRate(account:ManagementAccount,policies:CommissionPolicy[]){return policies.find(p=>p.accountId===account.id)?.bps??(account.kind==='store'?300:0);}
export function commissionLedger(accounts:ManagementAccount[],policies:CommissionPolicy[],existing:CommissionEntry[],now:string){const next=[...existing];for(const a of accounts){const records=a.kind==='creator'?a.works.filter(w=>w.status==='Tamamlandı').map(w=>({id:w.id,amount:w.amountCents,quantity:0,booked:false,kind:'work' as const,createdAt:now})):a.orders.filter(o=>o.status!=='cancelled').map(o=>({id:o.id,amount:o.amountCents,quantity:o.quantity,booked:a.kind==='store'&&o.status==='delivered'&&o.payment==='Ödendi',kind:'order' as const,createdAt:o.createdAt||now}));for(const r of records){const id=`${a.id}~${r.kind}~${r.id}`;if(next.some(e=>e.id===id))continue;const bps=currentRate(a,policies);next.push({id,accountId:a.id,sourceId:r.id,kind:r.kind,amountCents:r.amount,quantity:r.quantity,bps,commissionCents:Math.round(r.amount*bps/10000),booked:r.booked,createdAt:r.createdAt});}}return next;}
export function accountFinancials(account:ManagementAccount,ledger:CommissionEntry[]){const rows=ledger.filter(e=>e.accountId===account.id&&(e.kind==='order'?account.orders.some(o=>o.id===e.sourceId&&o.status!=='cancelled'):account.works.some(w=>w.id===e.sourceId&&w.status==='Tamamlandı')));return {rows,grossCents:rows.reduce((s,e)=>s+e.amountCents,0),units:rows.reduce((s,e)=>s+e.quantity,0),commissionCents:rows.filter(e=>e.booked).reduce((s,e)=>s+e.commissionCents,0),estimatedCommissionCents:rows.reduce((s,e)=>s+e.commissionCents,0),netEstimateCents:rows.reduce((s,e)=>s+e.amountCents-e.commissionCents,0)};}
export function codeIssue(code:ReferralCode,codes:ReferralCode[]){return !/^[A-Z0-9][A-Z0-9_-]{2,31}$/.test(code.code)||codes.some(c=>c.id!==code.id&&c.code===code.code)?'3–32 karakterlik benzersiz bir kod girin.':!code.title.trim()?'Kampanya adı gereklidir.':!dateOnly(code.startsOn)||!dateOnly(code.endsOn)||code.endsOn<code.startsOn?'Geçerli başlangıç ve bitiş tarihleri girin.':'';}
export function makeConversion(c:ReferralCode,customerId:string,base:number,existing:ReferralConversion[],id:string,now:string):ReferralConversion{if(c.kind!=='referral'||!c.active||now.slice(0,10)<c.startsOn||now.slice(0,10)>c.endsOn)throw new Error('Aktif ve tarih aralığı uygun bir referans kodu seçin.');if(c.ownerId===customerId||existing.some(x=>x.customerId===customerId&&x.status!=='rejected'))throw new Error('Kendi hesabını yönlendiremezsin; bu müşteri zaten bir referansa bağlı.');if(!integer(base))throw new Error('Geçerli komisyon baz tutarı girin.');return {id,codeId:c.id,customerId,status:'registered',commissionBaseCents:base,rewardBps:c.rewardBps,rewardCents:Math.round(base*c.rewardBps/10000),createdAt:now};}
export function conversionTransition(c:ReferralConversion,status:ReferralConversion['status']){if(c.status==='paid'||!({registered:['qualified','rejected'],qualified:['paid','rejected'],rejected:[]} as Record<string,string[]>)[c.status]?.includes(status))throw new Error('Bu referans kaydı için geçersiz durum geçişi.');return {...c,status};}
export function isCommercial(v:unknown,ids:string[],reviews:string[]):v is Commercial{if(!obj(v))return false;
 if(!list(v.policies,ids.length,p=>obj(p)&&ids.includes(String(p.accountId))&&integer(p.bps,10000)&&date(p.effectiveAt)&&typeof p.reason==='string'&&p.reason.trim().length>=5&&p.reason.length<=1000)||new Set((v.policies as CommissionPolicy[]).map(p=>p.accountId)).size!==(v.policies as unknown[]).length)return false;
 if(!list(v.ledger,5000,e=>obj(e)&&text(e.id,250)&&ids.includes(String(e.accountId))&&text(e.sourceId,100)&&['order','work'].includes(String(e.kind))&&integer(e.amountCents)&&integer(e.quantity,100000)&&integer(e.bps,10000)&&integer(e.commissionCents)&&e.commissionCents===Math.round(Number(e.amountCents)*Number(e.bps)/10000)&&typeof e.booked==='boolean'&&date(e.createdAt)))return false;
 if(!list(v.codes,300,c=>obj(c)&&text(c.id,100)&&ids.includes(String(c.ownerId))&&text(c.code,32)&&text(c.title,150)&&['referral','campaign'].includes(String(c.kind))&&integer(c.rewardBps,10000)&&integer(c.discountBps,10000)&&typeof c.active==='boolean'&&date(c.startsOn)&&date(c.endsOn)&&!codeIssue(c as ReferralCode,[])))return false;
 const codes=v.codes as ReferralCode[];
 if(!list(v.conversions,1000,c=>obj(c)&&text(c.id,100)&&ids.includes(String(c.customerId))&&['registered','qualified','rejected','paid'].includes(String(c.status))&&integer(c.commissionBaseCents)&&integer(c.rewardBps,10000)&&integer(c.rewardCents)&&c.rewardCents===Math.round(Number(c.commissionBaseCents)*Number(c.rewardBps)/10000)&&date(c.createdAt)&&codes.some(code=>code.id===c.codeId&&code.kind==='referral'&&code.ownerId!==c.customerId)))return false;
 if(!list(v.moderation,2000,m=>obj(m)&&reviews.includes(String(m.key))&&['visible','review','hidden'].includes(String(m.status))&&typeof m.note==='string'&&m.note.trim().length>=5&&m.note.length<=1000)||new Set((v.moderation as {key:string}[]).map(m=>m.key)).size!==(v.moderation as unknown[]).length)return false;
 const conversions=v.conversions as ReferralConversion[];return unique(v.ledger as CommissionEntry[])&&unique(codes)&&new Set(codes.map(c=>c.code)).size===codes.length&&unique(conversions)&&new Set(conversions.filter(c=>c.status!=='rejected').map(c=>c.customerId)).size===conversions.filter(c=>c.status!=='rejected').length&&list(v.events,300,e=>obj(e)&&text(e.id,100)&&text(e.actor,100)&&text(e.action,300)&&date(e.createdAt));
}
