import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const url=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const rules=await import(url(fs.readFileSync(new URL('./commercial.ts',import.meta.url),'utf8')));
const ops=await import(url(fs.readFileSync(new URL('./operations.ts',import.meta.url),'utf8')));
const a={id:'store:firmaadi',kind:'store',orders:[{id:'1',amountCents:10000,quantity:2,status:'delivered',payment:'Ödendi',createdAt:'2026-10-01T10:00:00Z'}],works:[]};
const code={id:'c1',ownerId:a.id,code:'HEER-2026',title:'Heer Referansı',kind:'referral',rewardBps:1000,discountBps:0,startsOn:'2026-01-01',endsOn:'2027-01-01',active:true};
test('commission basis points support decimals and reject invalid percentages',()=>{assert.equal(rules.parseBps('2,75'),275);assert.equal(rules.parseBps('0'),0);for(const v of ['101','-1','2.751','NaN',''])assert.throws(()=>rules.parseBps(v));});
test('changing account rate affects new rows only; existing cents and rate remain stable',()=>{const first=rules.commissionLedger([a],[],[],'2026-10-07T00:00:00Z'),policy=[{accountId:a.id,bps:1000}];const next=rules.commissionLedger([{...a,orders:[...a.orders,{...a.orders[0],id:'2'}]}],policy,first,'2026-10-08T00:00:00Z');assert.equal(first[0].bps,300);assert.equal(next[0].commissionCents,300);assert.equal(next[1].commissionCents,1000);assert.equal(first.length,1);assert.equal(rules.accountFinancials(a,next).units,2);});
test('cancelled sales and unfinished influencer proposals do not inflate financial totals',()=>{const ledger=rules.commissionLedger([a],[],[],'2026-10-07T00:00:00Z');assert.equal(rules.accountFinancials({...a,orders:[{...a.orders[0],status:'cancelled'}]},ledger).grossCents,0);assert.equal(rules.commissionLedger([{id:'creator:melis',kind:'creator',orders:[],works:[{id:'w1',amountCents:50000,status:'Yanıt Bekliyor'}]}],[],[],'2026-10-07T00:00:00Z').length,0);});
test('codes are unique and reject invalid calendar dates',()=>{assert.equal(rules.codeIssue(code,[]),'');assert.notEqual(rules.codeIssue({...code,id:'other'},[code]),'');assert.notEqual(rules.codeIssue({...code,startsOn:'2026-02-30'},[]),'');});
test('referrals reject self attribution, duplicate customers, inactive and expired codes',()=>{const now='2026-10-07T00:00:00Z',first=rules.makeConversion(code,'creator:melis',10000,[],'r1',now);assert.equal(first.rewardCents,1000);assert.throws(()=>rules.makeConversion(code,a.id,10000,[],'r2',now));assert.throws(()=>rules.makeConversion(code,'creator:melis',10000,[first],'r2',now));assert.throws(()=>rules.makeConversion({...code,active:false},'creator:melis',10000,[],'r2',now));assert.throws(()=>rules.makeConversion({...code,endsOn:'2026-01-02'},'creator:melis',10000,[],'r2',now));});
test('referral reward snapshots are preserved and paid records cannot be approved twice',()=>{const first=rules.makeConversion(code,'creator:melis',10000,[],'r1','2026-10-07T00:00:00Z');const qualified=rules.conversionTransition(first,'qualified'),paid=rules.conversionTransition(qualified,'paid');assert.equal(paid.rewardBps,1000);assert.throws(()=>rules.conversionTransition(paid,'paid'));assert.throws(()=>rules.conversionTransition(first,'paid'));});
test('commercial records reject foreign accounts and fabricated reward amounts',()=>{const ledger=rules.commissionLedger([a],[],[],'2026-10-07T00:00:00Z'),conversion=rules.makeConversion(code,'creator:melis',10000,[],'r1','2026-10-07T00:00:00Z'),valid={policies:[],ledger,codes:[code],conversions:[conversion],moderation:[],events:[]};assert.equal(rules.isCommercial(valid,[a.id,'creator:melis'],[]),true);assert.equal(rules.isCommercial({...valid,conversions:[{...conversion,rewardCents:1001}]},[a.id,'creator:melis'],[]),false);assert.equal(rules.isCommercial({...valid,ledger:[{...ledger[0],accountId:'unknown'}]},[a.id,'creator:melis'],[]),false);});
test('legacy owner page migration preserves existing staff and grants only the new owner pages',()=>{const pages=Object.keys(ops.pageLabels).filter(p=>!['reviews','referrals'].includes(p));const old={staff:[{id:'owner',pages},{id:'support',pages:['support']}]},next=ops.migrateOperations(old);assert.equal(next.staff[0].pages.length,pages.length+2);assert.deepEqual(next.staff[1].pages,['support']);assert.deepEqual(old.staff[0].pages,pages);});

test('seed referral codes remain unique when store and supplier share the same slug',async()=>{const rulesUrl=url(fs.readFileSync(new URL('./commercial.ts',import.meta.url),'utf8'));const mocks=await import(url(fs.readFileSync(new URL('../mocks/commercial.ts',import.meta.url),'utf8').replace("'../utils/commercial'",JSON.stringify(rulesUrl))));const accounts=[a,{id:'supplier:firmaadi',kind:'supplier',slug:'firmaadi',name:'Supplier',orders:[],works:[]},{id:'store:luma-studio',kind:'store',slug:'luma-studio',name:'Luma',orders:[],works:[]},{id:'creator:melis',kind:'creator',slug:'melis',name:'Melis',orders:[],works:[]}].map(x=>({...x,slug:x.slug||'firmaadi',name:x.name||'Heer'}));const seed=mocks.initialCommercial(accounts,'2026-10-07T00:00:00Z');assert.equal(rules.isCommercial(seed,accounts.map(x=>x.id),[]),true);assert.equal(new Set(seed.codes.map(c=>c.code)).size,seed.codes.length);});
