import type {Operations,PageKey,Staff,StaffRole,Broadcast,Payout} from '../types/operations';
import type {ManagementAccount} from '@/types/management-snapshot';
export const pageLabels:Record<PageKey,string>={overview:'Genel Bakış',members:'Üyeler & Firmalar',sales:'Satışlar & Siparişler',works:'İş Birlikleri',messages:'Platform Görüşmeleri',audit:'İşlem Geçmişi',team:'Ekip & Yetkiler',smtp:'SMTP Yönetimi',sms:'Toplu SMS',email:'Toplu E-posta',support:'Destek & Şikayetler',live:'Canlı Destek',finance:'Finans & Bakiyeler',reviews:'Değerlendirmeler',referrals:'Kampanya & Referans'};
export const roleLabels:Record<StaffRole,string>={owner:'Ana Yönetici',operations:'Operasyon',support:'Destek Uzmanı',finance:'Finans Uzmanı',marketing:'Pazarlama',custom:'Özel Yetkiler'};
export const rolePages:Record<StaffRole,PageKey[]>={owner:Object.keys(pageLabels) as PageKey[],operations:['overview','members','sales','works','messages'],support:['overview','members','support','live','reviews'],finance:['overview','sales','finance','referrals'],marketing:['overview','works','email','sms','referrals'],custom:['overview']};
export function pageForPath(path:string):PageKey{const segment=path.split('/')[2]||'';return ({uyeler:'members',magazalar:'members',tedarikciler:'members',influencerlar:'members',satislar:'sales','is-birlikleri':'works',mesajlar:'messages','islem-gecmisi':'audit',ekip:'team',smtp:'smtp',sms:'sms',eposta:'email',destek:'support','canli-destek':'live',finans:'finance',degerlendirmeler:'reviews',referanslar:'referrals'} as Record<string,PageKey>)[segment]||'overview';}
export function canAccess(staff:Staff|undefined,page:PageKey,write=false){return !!staff&&staff.status==='active'&&staff.pages.includes(page)&&(!write||staff.write);}
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown,max=200)=>typeof v==='string'&&v.length<=max;
export const validEmail=(v:string)=>v.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
export const validPhone=(v:string)=>/^\+90[1-9]\d{9}$/.test(v);
const array=(v:unknown,max:number,predicate:(v:unknown)=>boolean)=>Array.isArray(v)&&v.length<=max&&v.every(predicate);
const unique=(list:{id:string}[])=>new Set(list.map(x=>x.id)).size===list.length;
export function smtpIssue(s:Operations['smtp']){if(!s.host)return '';return !/^[A-Za-z0-9.-]{3,253}$/.test(s.host)||![465,587].includes(s.port)||s.security!==(s.port===465?'tls':'starttls')||!validEmail(s.fromEmail)||!validEmail(s.replyTo)||!s.fromName.trim()?'Sunucu, 465/TLS veya 587/STARTTLS ve gönderen adreslerini kontrol edin.':'';}
export function isOperations(v:unknown,accountIds:string[]):v is Operations{
 if(!record(v)||!array(v.staff,100,s=>record(s)&&text(s.id,100)&&text(s.name,100)&&String(s.name).trim().length>0&&typeof s.email==='string'&&validEmail(s.email)&&Object.keys(roleLabels).includes(String(s.role))&&['active','invited','paused'].includes(String(s.status))&&typeof s.write==='boolean'&&array(s.pages,Object.keys(pageLabels).length,p=>typeof p==='string'&&Object.hasOwn(pageLabels,p))&&new Set(s.pages as unknown[]).size===(s.pages as unknown[]).length))return false;
 const staff=v.staff as Staff[];const owner=staff.find(s=>s.id==='owner');if(!unique(staff)||new Set(staff.map(s=>s.email.toLowerCase())).size!==staff.length||!owner||owner.role!=='owner'||owner.status!=='active'||!owner.write||owner.pages.length!==Object.keys(pageLabels).length||staff.some(s=>s.id!=='owner'&&s.role==='owner'))return false;
 if(!record(v.smtp)||!['host','fromName','fromEmail','replyTo','username'].every(k=>text((v.smtp as Record<string,unknown>)[k],254))||![465,587].includes(Number(v.smtp.port))||!['tls','starttls'].includes(String(v.smtp.security))||smtpIssue(v.smtp as Operations['smtp'])||typeof v.smsSender!=='string'||!/^[A-Za-z0-9 ]{2,11}$/.test(v.smsSender))return false;
 if(!array(v.broadcasts,200,b=>record(b)&&text(b.id,100)&&['email','sms'].includes(String(b.channel))&&text(b.title,150)&&text(b.body,4000)&&['draft','queued','cancelled'].includes(String(b.status))&&typeof b.consent==='boolean'&&text(b.createdAt,40)&&Number.isFinite(Date.parse(String(b.createdAt)))&&array(b.recipients,500,r=>typeof r==='string'&&(b.channel==='email'?validEmail(r):validPhone(r)))&&!broadcastIssue(b as Broadcast)&&(b.status!=='queued'||(b.consent&&String(b.body).trim().length>0&&(b.recipients as string[]).length>0))))return false;
 if(!array(v.ticketReviews,300,t=>record(t)&&text(t.ticketId,200)&&['open','waiting','resolved'].includes(String(t.status))&&['normal','high'].includes(String(t.priority))&&typeof t.assignee==='string'&&(!t.assignee||staff.some(s=>s.id===t.assignee))&&text(t.note,2000)&&array(t.replies,100,m=>record(m)&&text(m.id,100)&&text(m.sender,100)&&text(m.body,4000))))return false;
 if(!array(v.live,100,t=>record(t)&&text(t.id,100)&&text(t.name,100)&&text(t.subject,200)&&['store','supplier','creator','buyer'].includes(String(t.source))&&['waiting','active','closed'].includes(String(t.status))&&typeof t.assignee==='string'&&(!t.assignee||staff.some(s=>s.id===t.assignee))&&array(t.messages,100,m=>record(m)&&text(m.id,100)&&text(m.sender,100)&&text(m.body,4000))))return false;
 if(!array(v.payouts,300,p=>record(p)&&text(p.id,100)&&accountIds.includes(String(p.accountId))&&Number.isSafeInteger(p.amountCents)&&Number(p.amountCents)>0&&['pending','approved','recorded'].includes(String(p.status))&&text(p.reference,150)&&text(p.createdAt,40)&&Number.isFinite(Date.parse(String(p.createdAt)))&&(p.status!=='recorded'||String(p.reference).trim().length>=5)))return false;
 return array(v.events,300,e=>record(e)&&text(e.id,100)&&text(e.actor,100)&&text(e.action,300)&&text(e.createdAt,40)&&Number.isFinite(Date.parse(String(e.createdAt))))&&unique(v.broadcasts as Broadcast[])&&unique(v.payouts as Payout[])&&unique(v.live as Operations['live'])&&new Set((v.ticketReviews as Operations['ticketReviews']).map(t=>t.ticketId)).size===(v.ticketReviews as unknown[]).length;
}
export function recipientList(value:string,channel:'email'|'sms'){const recipients=[...new Set(value.split(/[\n,;]+/).map(s=>s.trim()).filter(Boolean))];if(!recipients.length||recipients.length>500||recipients.some(r=>channel==='email'?!validEmail(r):!validPhone(r)))throw new Error(channel==='email'?'1–500 geçerli e-posta adresi girin.':'1–500 telefon numarasını +905XXXXXXXXX biçiminde girin.');return recipients;}
export function broadcastIssue(b:Broadcast){return !b.title.trim()||!b.body.trim()?'Başlık ve mesaj gereklidir.':b.channel==='sms'&&b.body.length>480?'SMS metni en fazla 480 karakter olabilir.':b.status==='queued'&&!b.consent?'İzinli alıcı onayını işaretleyin.':'';}
export function payoutTransition(p:Payout,next:Payout['status'],reference:string){if(p.status==='recorded'||(p.status==='pending'&&next!=='approved')||(p.status==='approved'&&next!=='recorded')||(next==='recorded'&&reference.trim().length<5))throw new Error('Aktarım sırasını ve en az 5 karakterlik kayıt referansını kontrol edin.');return {...p,status:next,reference:reference.trim()};}
export function financeSummary(accounts:ManagementAccount[]){const retail=accounts.filter(a=>a.kind==='store').flatMap(a=>a.orders).filter(o=>o.status!=='cancelled'),wholesale=accounts.filter(a=>a.kind==='supplier').flatMap(a=>a.orders).filter(o=>o.status!=='cancelled');return {retailCents:retail.reduce((s,o)=>s+o.amountCents,0),wholesaleCents:wholesale.reduce((s,o)=>s+o.amountCents,0),commissionCents:retail.filter(o=>o.status==='delivered'&&o.payment==='Ödendi').reduce((s,o)=>s+Math.round(o.amountCents*3/100),0),pendingCommissionCents:retail.filter(o=>o.status!=='delivered').reduce((s,o)=>s+Math.round(o.amountCents*3/100),0)};}

export function migrateOperations(value:unknown):unknown{if(!record(value)||!Array.isArray(value.staff))return value;const legacy=Object.keys(pageLabels).filter(p=>p!=='reviews'&&p!=='referrals');return {...value,staff:value.staff.map(s=>record(s)&&s.id==='owner'&&Array.isArray(s.pages)&&s.pages.length===legacy.length&&legacy.every(p=>(s.pages as unknown[]).includes(p))?{...s,pages:Object.keys(pageLabels)}:s)};}
