import Image from "next/image";
import Link from "next/link";
import { MarketingPage } from "@/components/layout/marketing-page";
import { PageIntro } from "@/components/layout/page-intro";
import { routes } from "@/config/routes";
import { explorePages, type ExploreSlug } from "../data/pages";
import { getStore } from "@/modules/storefront/data/stores";
import "../explore.css";

export function ExploreScreen({ slug }: { slug: ExploreSlug }) {
  const page = explorePages[slug];
  return <MarketingPage className="explore-page"><PageIntro eyebrow={slug === "iletisim" ? "İletişim" : "Alceix’i Keşfedin"} title={page.title} description={page.lead}><div className="explore-intro-actions"><Link href={slug === "iletisim" ? "mailto:destek@alceix.com" : routes.register} className="public-button">{slug === "iletisim" ? "Ekibimize Yazın" : "Mağaza Aç"}<span className="material-symbols-outlined" aria-hidden="true">arrow_forward</span></Link><Link href="/luma-studio" className="public-button public-button-light">Örnek Mağazayı İncele</Link></div></PageIntro>
    <section className="public-section"><div className="public-container"><div className="explore-overview"><div><span className="public-icon"><span className="material-symbols-outlined" aria-hidden="true">{page.icon}</span></span><h2>{slug === "iletisim" ? "Birlikte doğru adımı bulalım." : "Sizin için bir başlangıç noktası."}</h2><p className="public-section-description">{page.lead}</p><div className="explore-steps">{page.steps.map((step, index) => <div key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></div>)}</div></div><div className="explore-visual"><Image src={page.image} alt={slug === "is-birlikleri" ? "Tedarik ve lojistik için örnek depo görünümü" : "Alceix mağaza seçkisinden örnek ürün"} width={600} height={600} sizes="(min-width: 768px) 50vw, 100vw" /><span>ALCEIX · FİKRİNİZDEN VİTRİNİNİZE</span></div></div><div className="explore-cards">{page.cards.map((card, index) => <Link href={card.href} key={card.title} className="explore-card"><span className="explore-card-number">0{index + 1}</span><h3>{card.title}</h3><p>{card.description}</p><span className="explore-card-link">İncele <span className="material-symbols-outlined" aria-hidden="true">north_east</span></span></Link>)}</div></div></section>
    {slug === "urun-vitrinleri" && <section className="public-section public-section-soft"><div className="public-container"><span className="public-eyebrow">Örnek Ürün Sunumları</span><h2 className="explore-product-title">Dört kategori, özenli bir seçki.</h2><div className="explore-products">{getStore("luma-studio")?.products.map(product => <Link key={product.id} href="/luma-studio#products"><Image src={product.image} alt={product.name} width={400} height={480} sizes="(min-width: 768px) 25vw, 50vw" /><small>{product.category}</small><h3>{product.name}</h3><strong>{new Intl.NumberFormat("tr-TR", {style:"currency",currency:"TRY",maximumFractionDigits:0}).format(product.price)}</strong></Link>)}</div><p className="explore-demo-note">Örnek ürünler ve fiyatlar · Demo vitrinde ödeme alınmaz.</p></div></section>}
    <section className="public-section public-section-soft"><div className="public-container"><div className="explore-faq-heading"><span className="public-eyebrow">Merak Ettikleriniz</span><h2>Başlamadan önce.</h2></div><div className="faq-results">{page.questions.map(item => <details key={item.question} className="faq-item"><summary>{item.question}<span className="material-symbols-outlined" aria-hidden="true">expand_more</span></summary><p className="faq-answer">{item.answer}</p></details>)}</div><div className="explore-intro-actions"><Link href={routes.faq} className="public-button public-button-light">Tüm Soruları İncele</Link><Link href={routes.contact} className="public-button">İletişime Geç</Link></div></div></section>
  </MarketingPage>;
}
