import Image from "next/image";
import Link from "next/link";
import { MarketingPage } from "@/components/layout/marketing-page";
import { routes } from "@/config/routes";
import { blogPosts, readingMinutes, type BlogPost } from "../data/posts";
import "../blog.css";
export function ArticleScreen({ post }: { post: BlogPost }) {
  return <MarketingPage className="blog-page"><header className="blog-article-header"><div className="public-container"><nav className="public-breadcrumb" aria-label="Sayfa yolu"><Link href={routes.home}>Ana Sayfa</Link><span aria-hidden="true">/</span><Link href={routes.blog}>Blog</Link><span aria-hidden="true">/</span><span>{post.category}</span></nav><div className="blog-article-title"><span className="blog-category">{post.category}</span><h1>{post.title}</h1><p>{post.excerpt}</p><div className="blog-meta">Alceix Editör Ekibi <span>·</span> {readingMinutes(post)} dk okuma</div></div></div></header><div className="public-container"><Image className="blog-article-cover" src={post.image} alt={`${post.category} konusundan örnek ürün veya çalışma alanı`} width={1200} height={650} priority sizes="(min-width: 1200px) 1200px, 100vw" /></div><div className="public-container blog-article-layout"><aside className="blog-toc"><span>BU YAZIDA</span><nav aria-label="Yazı içindekiler">{post.sections.map((section,index) => <a key={section.id} href={`#${section.id}`}><small>0{index+1}</small>{section.title}</a>)}</nav><Link href={routes.blog}>← Tüm Yazılar</Link></aside><article className="blog-article-body">{post.sections.map(section => <section key={section.id} id={section.id}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="blog-article-cta"><span className="public-eyebrow">Alceix ile Keşfedin</span><h2>Bir fikri vitrinde görmek ister misiniz?</h2><p>Örnek mağazada ürün kartlarını ve detaylarını inceleyin.</p><Link href="/luma-studio" className="public-button">Örnek Mağazayı İncele <span aria-hidden="true">→</span></Link></div></article></div><section className="public-section public-section-soft"><div className="public-container"><span className="public-eyebrow">Okumaya Devam Edin</span><h2 className="blog-related-heading">İlginizi çekebilir.</h2><div className="blog-grid">{blogPosts.filter(item => item.slug !== post.slug).map(item => <Link className="blog-card" key={item.slug} href={`/blog/${item.slug}`}><Image src={item.image} alt={`${item.category} rehberinden örnek görsel`} width={600} height={420} sizes="(min-width: 768px) 33vw, 100vw" /><div><span className="blog-category">{item.category}</span><h3>{item.title}</h3><p>{item.excerpt}</p><strong>Yazıyı Oku →</strong></div></Link>)}</div></div></section></MarketingPage>;
}
