"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { blogPosts, readingMinutes } from "../data/posts";
const normalize = (value: string) => value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i");
export function BlogList() {
  const [category, setCategory] = useState("Tüm Yazılar");
  const [search, setSearch] = useState("");
  const categories = ["Tüm Yazılar", ...new Set(blogPosts.map(post => post.category))];
  const posts = blogPosts.filter(post => (category === "Tüm Yazılar" || category === post.category) && normalize(`${post.title} ${post.excerpt}`).includes(normalize(search.trim())));
  const featured = blogPosts[0];
  return <><section className="public-section"><div className="public-container"><Link className="blog-feature" href={`/blog/${featured.slug}`}><Image src={featured.image} alt="Mağaza seçkisine örnek triko ürün" width={700} height={500} sizes="(min-width: 768px) 50vw, 100vw" /><div><span className="public-eyebrow">Editörün Seçimi</span><span className="blog-category">{featured.category}</span><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="blog-meta">Alceix Editör Ekibi <span>·</span> {readingMinutes(featured)} dk okuma</div><strong>Yazıyı Oku <span aria-hidden="true">→</span></strong></div></Link></div></section><section className="public-section public-section-soft" id="blog-yazilari"><div className="public-container"><div className="blog-list-heading"><div><span className="public-eyebrow">Alceix Rehberleri</span><h2>Bir sonraki adımınız için.</h2></div><label className="blog-search"><span className="material-symbols-outlined" aria-hidden="true">search</span><span className="sr-only">Blog yazılarında ara</span><input type="search" placeholder="Bir konu ara…" value={search} onChange={event => setSearch(event.target.value)} /></label></div><div className="blog-categories" role="group" aria-label="Blog kategorileri">{categories.map(item => <button key={item} type="button" aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div><p className="blog-result-count" role="status">{posts.length} yazı bulundu</p><div className="blog-grid">{posts.map(post => <Link key={post.slug} className="blog-card" href={`/blog/${post.slug}`}><Image src={post.image} alt={`${post.category} rehberi için örnek görsel`} width={600} height={420} sizes="(min-width: 768px) 33vw, 100vw" /><div><span className="blog-category">{post.category}</span><h3>{post.title}</h3><p>{post.excerpt}</p><div className="blog-meta">{readingMinutes(post)} dk okuma <span>·</span> Alceix</div><strong>Yazıyı Oku <span aria-hidden="true">↗</span></strong></div></Link>)}</div>{!posts.length && <div className="blog-empty"><h3>Bu konuda bir yazı bulamadık.</h3><p>Aramanızı değiştirin veya diğer kategorilere göz atın.</p><button className="public-button" type="button" onClick={() => {setSearch("");setCategory("Tüm Yazılar");}}>Tüm Yazıları Göster</button></div>}</div></section></>;
}
